src/main/default/objects/aforza__Visit__c/aforza__Visit__c.object-meta.xml
<CustomObject>
    <description>A purposeful on-site meeting at an account.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>VIS-{00000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Visit__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the visit is taking place at.</description>
    <inlineHelpText>The account the visit is taking place at.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the visit.</description>
    <inlineHelpText>The current status of the visit.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Ring Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/ImageViewerControllerTest.cls
@IsTest
private class ImageViewerControllerTest {

    @IsTest
    private static void setupData() {
        Account newAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );
        aforza__Audit__c newAudit = (aforza__Audit__c) TdfSObjectFactory.insertSObject(
            new aforza__Audit__c(aforza__Account__c = newAccount.Id)
        );
        aforza__Audit_Asset__c newAsset = (aforza__Audit_Asset__c) TdfSObjectFactory.insertSObject(
            new aforza__Audit_Asset__c(aforza__Audit__c = newAudit.Id)
        );
        aforza__Visit__c newVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(
                aforza__Account__c = newAccount.Id,
                aforza__Status__c = 'Completed',
                RecordTypeId = RecordTypes.VISIT_REMOTE_VISIT_ID
            )
        );

        ContentVersion newContentVersion = (ContentVersion) TdfSObjectFactory.insertSObject(new ContentVersion());

        ContentVersion contentVersionDocId = [
                SELECT Id, Title, ContentDocumentId
                FROM ContentVersion
                WHERE Id = :newContentVersion.Id
                LIMIT 1
        ];

        TdfSObjectFactory.insertSObject(
            new ContentDocumentLink(
                LinkedEntityId = newAudit.Id,
                ContentDocumentId = contentVersionDocId.contentdocumentid,
                ShareType = 'V'
            )
        );
        TdfSObjectFactory.insertSObject(
            new ContentDocumentLink(
                LinkedEntityId = newAsset.Id,
                ContentDocumentId = contentVersionDocId.contentdocumentid,
                ShareType = 'V'
            )
        );
        TdfSObjectFactory.insertSObject(
            new ContentDocumentLink(
                LinkedEntityId = newVisit.Id,
                ContentDocumentId = contentVersionDocId.contentdocumentid,
                ShareType = 'V'
            )
        );

        Test.startTest();
        ImageViewerController.GenericObjectDTO result = ImageViewerController.getImageFiles(null, null, null, null, null, null);
        Test.stopTest();

        System.assertEquals(3, result.genericDto.size());
    }
}