src/main/default/objects/aforza__Visit__c/aforza__Visit__c.object-meta.xml
<CustomObject>
    <description>A purposeful on-site meeting at an account.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>VIS-{00000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Visit__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the visit is taking place at.</description>
    <inlineHelpText>The account the visit is taking place at.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the visit.</description>
    <inlineHelpText>The current status of the visit.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Ring Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of visit.</description>
    <inlineHelpText>The type of visit.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outlet Visit</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
            <value>
                <fullName>Video Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/VisitTriggerHandlerTest.cls
/**
 * Created by magdalena.stanciu on 28.11.2022.
 */

@IsTest
private class VisitTriggerHandlerTest {
    @IsTest
    static void testVisitInsert_ExistingCompletedVisitsWithNotes() {
        Account newAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        aforza__Visit__c existingVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(RecordTypeId = RecordTypes.VISIT_DIRECT_VISIT_ID, aforza__Account__c = newAccount.Id,
                aforza__Type__c = 'Outlet Visit', aforza__Status__c = 'Completed'));

        List<ContentVersion> newDocs = (List<ContentVersion>) TdfSObjectFactory.insertSObjects(
            new ContentVersion(PathOnClient = 'Test.sNote'), 5);

        List<ContentVersion> insertedDocs = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id IN :newDocs];

        for (Integer index = 0; index < insertedDocs.size(); index++) {
            TdfSObjectFactory.insertSObject(new ContentDocumentLink(LinkedEntityId = existingVisit.Id,
                ContentDocumentId = insertedDocs[index].ContentDocumentId));
        }

        Test.startTest();
        aforza__Visit__c newVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(RecordTypeId = RecordTypes.VISIT_DIRECT_VISIT_ID, aforza__Account__c = newAccount.Id,
                aforza__Type__c = 'Outlet Visit', aforza__Status__c = 'Not Started'));
        Test.stopTest();

        List<ContentDocumentLink> result = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :newVisit.Id];

        Assert.areEqual(4, result.size());
    }

    @IsTest
    static void testVisitInsert_ExistingNotStartedVisitsWithNotes() {
        Account newAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        aforza__Visit__c existingVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(RecordTypeId = RecordTypes.VISIT_DIRECT_VISIT_ID, aforza__Account__c = newAccount.Id,
                aforza__Type__c = 'Outlet Visit', aforza__Status__c = 'Not Started'));

        List<ContentVersion> newDocs = (List<ContentVersion>) TdfSObjectFactory.insertSObjects(
            new ContentVersion(PathOnClient = 'Test.sNote'), 5);

        List<ContentVersion> insertedDocs = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id IN :newDocs];

        for (Integer index = 0; index < insertedDocs.size(); index++) {
            TdfSObjectFactory.insertSObject(new ContentDocumentLink(LinkedEntityId = existingVisit.Id,
                ContentDocumentId = insertedDocs[index].ContentDocumentId));
        }

        Test.startTest();
        aforza__Visit__c newVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(RecordTypeId = RecordTypes.VISIT_DIRECT_VISIT_ID, aforza__Account__c = newAccount.Id,
                aforza__Type__c = 'Outlet Visit', aforza__Status__c = 'Not Started'));
        Test.stopTest();

        List<ContentDocumentLink> result = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :newVisit.Id];

        Assert.areEqual(0, result.size());
    }

    @IsTest
    static void testVisitInsert_ExistingCompletedVisitsWithRelatedDocDifferentFromNotes() {
        Account newAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        aforza__Visit__c existingVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(RecordTypeId = RecordTypes.VISIT_DIRECT_VISIT_ID, aforza__Account__c = newAccount.Id,
                aforza__Type__c = 'Outlet Visit', aforza__Status__c = 'Completed'));

        List<ContentVersion> newDocs = (List<ContentVersion>) TdfSObjectFactory.insertSObjects(
            new ContentVersion(PathOnClient = 'Test.pdf'), 5
        );

        List<ContentVersion> insertedDocs = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id IN :newDocs];

        for (Integer index = 0; index < insertedDocs.size(); index++) {
            TdfSObjectFactory.insertSObject(new ContentDocumentLink(LinkedEntityId = existingVisit.Id,
                ContentDocumentId = insertedDocs[index].ContentDocumentId));
        }

        Test.startTest();
        aforza__Visit__c newVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(RecordTypeId = RecordTypes.VISIT_DIRECT_VISIT_ID, aforza__Account__c = newAccount.Id,
                aforza__Type__c = 'Outlet Visit', aforza__Status__c = 'Not Started'));
        Test.stopTest();

        List<ContentDocumentLink> result = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :newVisit.Id];

        Assert.areEqual(0, result.size());
    }

    @IsTest
    static void testVisitInsert_NoExistingVisits() {
        Account newAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        Test.startTest();
        aforza__Visit__c newVisit = (aforza__Visit__c) TdfSObjectFactory.insertSObject(
            new aforza__Visit__c(RecordTypeId = RecordTypes.VISIT_DIRECT_VISIT_ID, aforza__Account__c = newAccount.Id,
                aforza__Type__c = 'Outlet Visit', aforza__Status__c = 'Not Started'));
        Test.stopTest();

        List<ContentDocumentLink> result = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :newVisit.Id];

        Assert.areEqual(0, result.size());
    }
}