src/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the invoice.</description>
    <inlineHelpText>The current status of the invoice.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Attempt Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Approved for Payment</fullName>
                <default>true</default>
                <label>Approved for Payment</label>
            </value>
            <value>
                <fullName>Cash in Transit</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>true</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/CreditCardPaymentTaken__c.field-meta.xml
<CustomField>
    <fullName>CreditCardPaymentTaken__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If check, a Credit Card payment has been captured in the event a Direct Debit or Bacs payment has failed.</inlineHelpText>
    <label>Credit Card Payment Taken?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PreAuthCaptured__c.field-meta.xml
<CustomField>
    <fullName>PreAuthCaptured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Auth Captured?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/aforza__Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>A monetary transaction against a specific account.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PTR-{00000000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the payment transaction has been enacted against.</description>
    <inlineHelpText>The account the payment transaction has been enacted against.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Method__c.field-meta.xml
<CustomField>
    <fullName>aforza__Method__c</fullName>
    <description>The method of payment.</description>
    <inlineHelpText>The method of payment.</inlineHelpText>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adjustment Credit</fullName>
            </value>
            <value>
                <fullName>Adjustment Debit</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Bacs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the transaction.</description>
    <inlineHelpText>The current status of the transaction.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Authorization</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/BtTransaction__c.field-meta.xml
<CustomField>
    <fullName>BtTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BT Transaction</label>
    <referenceTo>bt_stripe__Transaction__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/bt_stripe__Transaction__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/bt_stripe__Transaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A linked Invoice.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/PreAuthCaptured__c.field-meta.xml
<CustomField>
    <fullName>PreAuthCaptured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Auth Captured?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/BtTransactionTriggerHandler.cls
/**
 * Created by svatopluk.sejkora on 15.11.2022.
 */

public with sharing class BtTransactionTriggerHandler {

    /**
     * @description creates aforza transaction whenever specific BT transaction is created
     *
     * @param transactions new BT transactions
     *
     *
     * @author Svatopluk Sejkora, BearingPoint
     * @date 2022-11-14
     */
    public static void createAforzaTransaction(List<bt_stripe__Transaction__c> transactions) {
        Set<Id> accountIds = new Set<Id>();
        Map<String, List<bt_stripe__Transaction__c>> transactionsToProcess = new Map<String, List<bt_stripe__Transaction__c>>{
            'PRE_AUTH' => new List<bt_stripe__Transaction__c>(),
            'INVOICE' => new List<bt_stripe__Transaction__c>(),
            'REFUND' => new List<bt_stripe__Transaction__c>(),
            'JDE' => new List<bt_stripe__Transaction__c>()
        };
        for (bt_stripe__Transaction__c blackthornTransaction : transactions) {
            // to create aforza payment for pre authorised transaction
            if (blackthornTransaction.Order__c != null && blackthornTransaction.bt_stripe__Payment_Status__c == 'Authorized' && blackthornTransaction.Invoice__c == null) {
                accountIds.add(blackthornTransaction.bt_stripe__Related_Account__c);
                transactionsToProcess.get('PRE_AUTH').add(blackthornTransaction);
                continue;
            }
            // to create aforza payment for Straight to JDE orders
            if (blackthornTransaction.Order__c != null && blackthornTransaction.bt_stripe__Payment_Status__c == 'Captured' && blackthornTransaction.Invoice__c == null) {
                accountIds.add(blackthornTransaction.bt_stripe__Related_Account__c);
                transactionsToProcess.get('JDE').add(blackthornTransaction);
                continue;
            }
            // to create aforza payment for invoice based payment creation
            if (blackthornTransaction.Invoice__c != null && blackthornTransaction.Order__c != null) {
                accountIds.add(blackthornTransaction.bt_stripe__Related_Account__c);
                transactionsToProcess.get('INVOICE').add(blackthornTransaction);
                continue;
            }
            // to create aforza payment for refund
            if (blackthornTransaction.bt_stripe__Transaction_Type__c == 'Refund') {
                accountIds.add(blackthornTransaction.bt_stripe__Related_Account__c);
                transactionsToProcess.get('REFUND').add(blackthornTransaction);
            }
        }

        if (transactionsToProcess.size() > 0) {
            List<aforza__Payment_Transaction__c> aforzaTransactionsToInsert = new List<aforza__Payment_Transaction__c>();
            List<Order> ordersToUpdate = new List<Order>();
            Map<Id, Id> accountIdToPaymentMethodId = fetchPaymentMethodsForAccounts(accountIds);
            for (bt_stripe__Transaction__c blackthornTransaction : transactionsToProcess.get('PRE_AUTH')) {
                aforzaTransactionsToInsert.add(mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'PRE_AUTH'));
                ordersToUpdate.add(new Order(Id = blackthornTransaction.Order__c, PreAuthCaptured__c = true));
            }
            for (bt_stripe__Transaction__c blackthornTransaction : transactionsToProcess.get('JDE')) {
                aforzaTransactionsToInsert.add(mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'JDE'));
            }
            for (bt_stripe__Transaction__c blackthornTransaction : transactionsToProcess.get('INVOICE')) {
                aforzaTransactionsToInsert.add(mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'INVOICE'));
            }
            for (bt_stripe__Transaction__c blackthornTransaction : transactionsToProcess.get('REFUND')) {
                aforzaTransactionsToInsert.add(mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'REFUND'));
            }

            insert aforzaTransactionsToInsert;
            update ordersToUpdate;
        }
    }

    /**
     * @description when BT transaction is completed and Paid update aforza payment and invoice
     *
     * @param transactions BT transactions
     * @param oldMap map with old transactions
     *
     * @author Svatopluk Sejkora, BearingPoint
     * @date 2022-11-14
     */
    public static void updateInvoiceAndAforzaTransactionWhenCompleted(List<bt_stripe__Transaction__c> transactions, Map<Id, bt_stripe__Transaction__c> oldMap) {
        List<SObject> invoicesAndPaymentsToUpdate = new List<SObject>();
        Set<Id> transactionIds = new Set<Id>();
        for (bt_stripe__Transaction__c btTransaction : transactions) {
            bt_stripe__Transaction__c oldTransaction = oldMap.get(btTransaction.Id);
            if (btTransaction.bt_stripe__Payment_Status__c == 'Captured' && btTransaction.bt_stripe__Transaction_Status__c == 'Completed'
                && oldTransaction.bt_stripe__Payment_Status__c <> btTransaction.bt_stripe__Payment_Status__c) {
                // update invoices only when there is an invoice, try to get aforza transactions every time
                if (btTransaction.Invoice__c != null) {
                    invoicesAndPaymentsToUpdate.add(new aforza__Invoice__c(Id = btTransaction.Invoice__c, aforza__Status__c = 'Paid in Full', CreditCardPaymentTaken__c = true));
                }
                transactionIds.add(btTransaction.Id);
            }
        }

        if (transactionIds.size() > 0) {
            invoicesAndPaymentsToUpdate.addAll(preparePaymentsForUpdate(transactionIds));
        }

        update invoicesAndPaymentsToUpdate;
    }

    /**
     * @description maps BT payment to Aforza Payment Transaction
     *
     * @param blackthornTransaction BT transaction
     * @param accountIdToPaymentMethodId map of account Id to ITs payment method
     * @param context context for which the aforza payment is created
     *
     * @return aforzaTransaction with mapped values
     *
     * @author Svatopluk Sejkora, BearingPoint
     * @date 2022-11-14
     */
    @TestVisible
    private static aforza__Payment_Transaction__c mapBlackthornTransactionToAforzaTransaction(bt_stripe__Transaction__c blackthornTransaction, Map<Id, Id> accountIdToPaymentMethodId, String context) {
        aforza__Payment_Transaction__c aforzaTransaction = new aforza__Payment_Transaction__c();
        aforzaTransaction.aforza__Payment_Method__c = accountIdToPaymentMethodId?. get (blackthornTransaction.bt_stripe__Related_Account__c);
        aforzaTransaction.aforza__Amount__c = blackthornTransaction.bt_stripe__Amount__c;
        aforzaTransaction.OrderNumber__c = blackthornTransaction.Order__c;
        aforzaTransaction.aforza__Account__c = blackthornTransaction.bt_stripe__Related_Account__c;
        aforzaTransaction.aforza__Method__c = 'Credit Card';
        aforzaTransaction.aforza__Type__c = 'Customer Payment';
        aforzaTransaction.aforza__Date__c = blackthornTransaction.bt_stripe__Processed_Date__c.date();
        aforzaTransaction.BtTransaction__c = blackthornTransaction.Id;

        if (context == 'PRE_AUTH') {
            aforzaTransaction.aforza__Status__c = 'Pre-Authorization';
        } else if (context == 'INVOICE') {
            aforzaTransaction.aforza__Status__c = 'Pending';
            aforzaTransaction.aforza__Invoice__c = blackthornTransaction.Invoice__c;
        } else if (context == 'REFUND') {
            aforzaTransaction.aforza__Status__c = 'Applied';
            aforzaTransaction.aforza__Invoice__c = blackthornTransaction.Invoice__c;
        } else if (context == 'JDE') {
            aforzaTransaction.aforza__Status__c = 'Applied';
        }

        return aforzaTransaction;
    }

    /**
     * @description fetches specific payment method linked to accounts
     *
     * @param accountIds account Ids to get payments methods for
     *
     * @return accountIdToPaymentMethodId map of account Id to its payment method
     *
     * @author Svatopluk Sejkora, BearingPoint
     * @date 2022-11-14
     */
    @TestVisible
    private static Map<Id, Id> fetchPaymentMethodsForAccounts(Set <Id> accountIds) {
        Map<Id, Id> accountIdToPaymentMethodId = new Map<Id, Id>();
        for (aforza__Payment_Method__c paymentMethod : [
            SELECT Id, aforza__Account__c
            FROM aforza__Payment_Method__c
            WHERE aforza__Account__c IN :accountIds
            AND aforza__Account__r.RecordTypeId = :RecordTypes.ACCOUNT_OUTLET_ID
            AND RecordTypeId = :RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID
            AND aforza__Active__c = TRUE
        ]) {
            accountIdToPaymentMethodId.put(paymentMethod.aforza__Account__c, paymentMethod.Id);
        }
        return accountIdToPaymentMethodId;
    }

    /**
     * @description obtains aforza payments for each BT transaction and sets it status to Applied
     *
     * @param transactionIds transactions to get aforza payments for
     *
     * @return paymentTransactions - list of aforza transactions to update
     *
     * @author Svatopluk Sejkora, BearingPoint
     * @date 2022-11-14
     */
    @TestVisible
    private static List<aforza__Payment_Transaction__c> preparePaymentsForUpdate(Set <Id> transactionIds) {
        List<aforza__Payment_Transaction__c> paymentTransactions = [SELECT Id, aforza__Status__c FROM aforza__Payment_Transaction__c WHERE BtTransaction__c IN :transactionIds];
        for (aforza__Payment_Transaction__c paymentTransaction : paymentTransactions) {
            paymentTransaction.aforza__Status__c = 'Applied';
            paymentTransaction.aforza__Method__c = 'Credit Card';
        }
        return paymentTransactions;
    }

}