src/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the invoice.</description>
    <inlineHelpText>The current status of the invoice.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Attempt Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Approved for Payment</fullName>
                <default>true</default>
                <label>Approved for Payment</label>
            </value>
            <value>
                <fullName>Cash in Transit</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>true</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/CreditCardPaymentTaken__c.field-meta.xml
<CustomField>
    <fullName>CreditCardPaymentTaken__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If check, a Credit Card payment has been captured in the event a Direct Debit or Bacs payment has failed.</inlineHelpText>
    <label>Credit Card Payment Taken?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PreAuthCaptured__c.field-meta.xml
<CustomField>
    <fullName>PreAuthCaptured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Auth Captured?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/aforza__Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>A monetary transaction against a specific account.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PTR-{00000000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the payment transaction has been enacted against.</description>
    <inlineHelpText>The account the payment transaction has been enacted against.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Method__c.field-meta.xml
<CustomField>
    <fullName>aforza__Method__c</fullName>
    <description>The method of payment.</description>
    <inlineHelpText>The method of payment.</inlineHelpText>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adjustment Credit</fullName>
            </value>
            <value>
                <fullName>Adjustment Debit</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Bacs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the transaction.</description>
    <inlineHelpText>The current status of the transaction.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Authorization</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/BtTransaction__c.field-meta.xml
<CustomField>
    <fullName>BtTransaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BT Transaction</label>
    <referenceTo>bt_stripe__Transaction__c</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/bt_stripe__Transaction__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/bt_stripe__Transaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A linked Invoice.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/PreAuthCaptured__c.field-meta.xml
<CustomField>
    <fullName>PreAuthCaptured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Auth Captured?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/BtTransactionTriggerHandlerTest.cls
/**
 * Created by svatopluk.sejkora on 15.11.2022.
 */

@IsTest
private class BtTransactionTriggerHandlerTest {

    @IsTest
    private static void testFetchPaymentMethodsForAccounts() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        aforza__Payment_Method__c paymentMethod = (aforza__Payment_Method__c)
            TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
                aforza__Account__c = acc.Id));

        Test.startTest();
        Map<Id, Id> accountIdToPaymentMethodId = BtTransactionTriggerHandler.fetchPaymentMethodsForAccounts(new Set<Id>{
            acc.Id
        });
        Test.stopTest();

        Assert.areEqual(1, accountIdToPaymentMethodId.size());
        Assert.isTrue(accountIdToPaymentMethodId.containsKey(acc.Id));
        Assert.areEqual(paymentMethod.Id, accountIdToPaymentMethodId.get(acc.Id));
    }

    @IsTest
    private static void testMapBlackthornTransactionToAforzaTransaction() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));
        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id, RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID));

        Map<Id, Id> accountIdToPaymentMethodId = BtTransactionTriggerHandler.fetchPaymentMethodsForAccounts(new Set<Id>{
            acc.Id
        });

        Test.startTest();
        aforza__Payment_Transaction__c paymentTransaction = BtTransactionTriggerHandler.mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'PRE_AUTH');
        Test.stopTest();

        Assert.areEqual(accountIdToPaymentMethodId.get(acc.Id), paymentTransaction.aforza__Payment_Method__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Amount__c, paymentTransaction.aforza__Amount__c);
        Assert.areEqual('Pre-Authorization', paymentTransaction.aforza__Status__c);
        Assert.areEqual(blackthornTransaction.Order__c, paymentTransaction.OrderNumber__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Related_Account__c, paymentTransaction.aforza__Account__c);
        Assert.areEqual('Credit Card', paymentTransaction.aforza__Method__c);
        Assert.areEqual('Customer Payment', paymentTransaction.aforza__Type__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Processed_Date__c.date(), paymentTransaction.aforza__Date__c);
        Assert.areEqual(blackthornTransaction.Id, paymentTransaction.BtTransaction__c);
    }

    @IsTest
    private static void testMapBlackthornTransactionToAforzaTransaction_NoPaymentMethod() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id, RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID));

        Map<Id, Id> accountIdToPaymentMethodId = BtTransactionTriggerHandler.fetchPaymentMethodsForAccounts(new Set<Id>{
            acc.Id
        });

        Test.startTest();
        aforza__Payment_Transaction__c paymentTransaction = BtTransactionTriggerHandler.mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'PRE_AUTH');
        Test.stopTest();

        Assert.areEqual(null, paymentTransaction.aforza__Payment_Method__c);
    }

    @IsTest
    private static void testCreateAforzaTransaction() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));

        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id, RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID));

        Test.startTest();
        insert blackthornTransaction;
        Test.stopTest();

        // get aforza transaction
        List<aforza__Payment_Transaction__c> createdPaymentTransaction = [SELECT Id FROM aforza__Payment_Transaction__c];
        Assert.isTrue(createdPaymentTransaction.size() == 1);

        // get updated orders
        List<Order> updatedOrders = [SELECT Id, PreAuthCaptured__c FROM Order];
        Assert.isTrue(updatedOrders.size() == 1);
        Assert.isTrue(updatedOrders[0].PreAuthCaptured__c);
    }

    @IsTest
    private static void testPreparePaymentsForUpdate() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));

        aforza__Invoice__c invoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(new aforza__Invoice__c(aforza__Account__c = acc.Id));

        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id, RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID));
        insert blackthornTransaction;


        Test.startTest();
        blackthornTransaction.bt_stripe__Payment_Status__c = 'Captured';
        blackthornTransaction.bt_stripe__Transaction_Status__c = 'Completed';
        blackthornTransaction.Invoice__c = invoice.Id;
        update blackthornTransaction;
        Test.stopTest();

        List<aforza__Invoice__c> updatedInvoices = [SELECT Id, aforza__Status__c, CreditCardPaymentTaken__c FROM aforza__Invoice__c];
        Assert.isTrue(updatedInvoices.size() == 1);
        Assert.areEqual('Paid in Full', updatedInvoices[0].aforza__Status__c);
        Assert.isTrue(updatedInvoices[0].CreditCardPaymentTaken__c);

        List<aforza__Payment_Transaction__c> updatedPaymentTransactions = [SELECT Id, aforza__Status__c, aforza__Method__c FROM aforza__Payment_Transaction__c];
        Assert.isTrue(updatedPaymentTransactions.size() == 1);
        Assert.areEqual('Applied', updatedPaymentTransactions[0].aforza__Status__c);
        Assert.areEqual('Credit Card', updatedPaymentTransactions[0].aforza__Method__c);
    }

    @IsTest
    private static void testCreateAforzaTransaction_Invoice() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));

        aforza__Invoice__c invoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(new aforza__Invoice__c(aforza__Account__c = acc.Id));

        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id, RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID, Invoice__c = invoice.Id));

        Test.startTest();
        insert blackthornTransaction;
        Test.stopTest();

        // get aforza transaction
        List<aforza__Payment_Transaction__c> createdPaymentTransaction = [SELECT Id FROM aforza__Payment_Transaction__c];
        Assert.isTrue(createdPaymentTransaction.size() == 1);
    }

    @IsTest
    private static void testMapBlackthornTransactionToAforzaTransaction_Invoice() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));

        aforza__Invoice__c invoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(new aforza__Invoice__c(aforza__Account__c = acc.Id));

        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id,
                RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID, Invoice__c = invoice.Id));

        Map<Id, Id> accountIdToPaymentMethodId = BtTransactionTriggerHandler.fetchPaymentMethodsForAccounts(new Set<Id>{
            acc.Id
        });

        Test.startTest();
        aforza__Payment_Transaction__c paymentTransaction = BtTransactionTriggerHandler.mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'INVOICE');
        Test.stopTest();

        Assert.areEqual(accountIdToPaymentMethodId.get(acc.Id), paymentTransaction.aforza__Payment_Method__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Amount__c, paymentTransaction.aforza__Amount__c);
        Assert.areEqual('Pending', paymentTransaction.aforza__Status__c);
        Assert.areEqual(blackthornTransaction.Invoice__c, paymentTransaction.aforza__Invoice__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Related_Account__c, paymentTransaction.aforza__Account__c);
        Assert.areEqual('Credit Card', paymentTransaction.aforza__Method__c);
        Assert.areEqual('Customer Payment', paymentTransaction.aforza__Type__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Processed_Date__c.date(), paymentTransaction.aforza__Date__c);
        Assert.areEqual(blackthornTransaction.Id, paymentTransaction.BtTransaction__c);
    }

    @IsTest
    private static void testMapBlackthornTransactionToAforzaTransaction_Refund() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));

        aforza__Invoice__c invoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(new aforza__Invoice__c(aforza__Account__c = acc.Id));

        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id,
                RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID, Invoice__c = invoice.Id, bt_stripe__Transaction_Type__c = 'Refund'));

        Map<Id, Id> accountIdToPaymentMethodId = BtTransactionTriggerHandler.fetchPaymentMethodsForAccounts(new Set<Id>{
            acc.Id
        });

        Test.startTest();
        aforza__Payment_Transaction__c paymentTransaction = BtTransactionTriggerHandler.mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'REFUND');
        Test.stopTest();

        Assert.areEqual(accountIdToPaymentMethodId.get(acc.Id), paymentTransaction.aforza__Payment_Method__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Amount__c, paymentTransaction.aforza__Amount__c);
        Assert.areEqual('Applied', paymentTransaction.aforza__Status__c);
        Assert.areEqual(blackthornTransaction.Invoice__c, paymentTransaction.aforza__Invoice__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Related_Account__c, paymentTransaction.aforza__Account__c);
        Assert.areEqual('Credit Card', paymentTransaction.aforza__Method__c);
        Assert.areEqual('Customer Payment', paymentTransaction.aforza__Type__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Processed_Date__c.date(), paymentTransaction.aforza__Date__c);
        Assert.areEqual(blackthornTransaction.Id, paymentTransaction.BtTransaction__c);
    }

    @IsTest
    private static void testMapBlackthornTransactionToAforzaTransaction_Jde() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));
        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id,
                RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID));

        Map<Id, Id> accountIdToPaymentMethodId = BtTransactionTriggerHandler.fetchPaymentMethodsForAccounts(new Set<Id>{
            acc.Id
        });

        Test.startTest();
        aforza__Payment_Transaction__c paymentTransaction = BtTransactionTriggerHandler.mapBlackthornTransactionToAforzaTransaction(blackthornTransaction, accountIdToPaymentMethodId, 'JDE');
        Test.stopTest();

        Assert.areEqual(accountIdToPaymentMethodId.get(acc.Id), paymentTransaction.aforza__Payment_Method__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Amount__c, paymentTransaction.aforza__Amount__c);
        Assert.areEqual('Applied', paymentTransaction.aforza__Status__c);
        Assert.areEqual(blackthornTransaction.Order__c, paymentTransaction.OrderNumber__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Related_Account__c, paymentTransaction.aforza__Account__c);
        Assert.areEqual('Credit Card', paymentTransaction.aforza__Method__c);
        Assert.areEqual('Customer Payment', paymentTransaction.aforza__Type__c);
        Assert.areEqual(blackthornTransaction.bt_stripe__Processed_Date__c.date(), paymentTransaction.aforza__Date__c);
        Assert.areEqual(blackthornTransaction.Id, paymentTransaction.BtTransaction__c);
    }

    @IsTest
    private static void testCreateAforzaTransaction_Jde() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        TdfSObjectFactory.insertSObject(new aforza__Payment_Method__c(RecordTypeId = RecordTypes.PAYMENT_METHOD_CREDIT_CARD_ID,
            aforza__Account__c = acc.Id));

        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(AccountId = acc.Id, RecordTypeId = RecordTypes.ORDER_STRAIGHT_TO_JDE_ID));

        bt_stripe__Transaction__c blackthornTransaction = (bt_stripe__Transaction__c)
            TdfSObjectFactory.createSObject(new bt_stripe__Transaction__c(bt_stripe__Related_Account__c = acc.Id,
                RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID, Order__c = order.Id, bt_stripe__Payment_Status__c = 'Captured'));

        Test.startTest();
        insert blackthornTransaction;
        Test.stopTest();

        // get aforza transaction
        List<aforza__Payment_Transaction__c> createdPaymentTransaction = [SELECT Id, aforza__Status__c FROM aforza__Payment_Transaction__c];
        Assert.isTrue(createdPaymentTransaction.size() == 1);
        Assert.areEqual('Applied', createdPaymentTransaction[0].aforza__Status__c);
    }
}