src/main/default/objects/Load__c/Load__c.object-meta.xml
<CustomObject>
    <label>Load</label>
    <nameField>
        <label>Load ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Load__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DepotValues</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Load__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Load__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Loads</relationshipLabel>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>VEH-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Vehicle__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Driver associated with this vehicle.</inlineHelpText>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This user is not a Driver (need to add Driver as this user&apos;s role).</errorMessage>
        <filterItems>
            <field>User.UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>Driver</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/globalValueSets/DepotValues.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>D</fullName>
        <label>Dagenham</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>Wednesbury</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>Moston</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Scotland</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cranks</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>Bentleys</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Murdens</label>
    </customValue>
    <customValue>
        <fullName>Z</fullName>
        <label>Menzies</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Blacks</label>
    </customValue>
    <customValue>
        <fullName>Cumbernauld</fullName>
        <isActive>false</isActive>
        <label>Cumbernauld</label>
    </customValue>
    <masterLabel>Depot Values</masterLabel>
</GlobalValueSet>

src/main/default/classes/TdfLoadTemplate.cls
/**
 * Class provides functionality for creating default load in test methods.
 *
 * Do not use this class directly.
 * Class is initialized in TDF_SObjectTemplateFactory and all its functionality is used through TDF_SObjectFactory.
 *
 * @see TdfSObjectFactory
 * @see TdfSObjectTemplate
 * @see TdfSObjectTemplateFactory
 *
 * @author  Magdalena Stanciu
 * @date    2022-10-15
 *
 */
@IsTest
public with sharing class TdfLoadTemplate extends TdfSObjectTemplate {
    private Id vehicleId;

    /**
     * Instance is created dynamically. This method compensates a constructor.
     *
     * @author  Magdalena Stanciu
     * @date    2022-10-15
     *
     */
    public override void init() {
        Load__c userDefinedLoad = (Load__c) userDefinedSObject;
        if (userDefinedLoad.Vehicle__c == null) {
            vehicleId = ((Vehicle__c) TdfSObjectFactory.insertSObject(new Vehicle__c())).Id;
        }
    }

    /**
     * Creates a template SObject. Every call returns a new instance.
     *
     * Because this method can be called multiple times, all operations as DML or SOQL has to be done in init().
     *
     * @return template with load record
     *
     * @author  Magdalena Stanciu
     * @date    2022-10-15
     */
    protected override SObject createTemplateSObject() {
        Load__c template = new Load__c(
            DeliveryDate__c = System.today(),
            Driver__c = UserInfo.getUserId(),
            Vehicle__c = vehicleId,
            Depot__c = 'M'
        );

        return template;
    }
}