src/main/default/objects/Load__c/Load__c.object-meta.xml
<CustomObject>
    <label>Load</label>
    <nameField>
        <label>Load ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Load__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Load__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Loads</relationshipLabel>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Order/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Load</label>
    <referenceTo>Load__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>VEH-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Vehicle__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Driver associated with this vehicle.</inlineHelpText>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This user is not a Driver (need to add Driver as this user&apos;s role).</errorMessage>
        <filterItems>
            <field>User.UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>Driver</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/LoadPlanningScreenController.cls
/**
 * Created by svatopluk.sejkora on 12.10.2022.
 */

public with sharing class LoadPlanningScreenController {

    @AuraEnabled
    public static List<Order> fetchOrdersForLoad(String fieldsToGet, String loadId) {
        try {
            String sQuery = 'SELECT ';
            sQuery += fieldsToGet;
            sQuery += ' FROM Order WHERE Load__c = \'' + loadId + '\'';

            List<Order> orders = Database.query(sQuery);

            return orders.isEmpty() ? null : orders;
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Load__c fetchLoadData(String loadId) {
        try {
            List<Load__c> load = [SELECT Id, Driver__c, Vehicle__c, DeliveryDate__c FROM Load__c WHERE Id = :loadId];

            return load.isEmpty() ? null : load[0];
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }
}