src/main/default/objects/Load__c/Load__c.object-meta.xml
<CustomObject>
    <label>Load</label>
    <nameField>
        <label>Load ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Load__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Loads</relationshipLabel>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Order/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Load</label>
    <referenceTo>Load__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/Replanned__c.field-meta.xml
<CustomField>
    <fullName>Replanned__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field populated to true when order changed status from Delivery Failed to Unplanned. Populated only by action from Logistic Update Screen.</inlineHelpText>
    <label>Replanned</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/RemoveOrdersFromLoadStatusMapping__mdt/RemoveOrdersFromLoadStatusMapping__mdt.object-meta.xml
<CustomObject>
    <description>A set of mappings that control what statuses are going to be set when order with certain status is removed from load.</description>
    <label>Remove Orders From Load Status Mapping</label>
    <pluralLabel>Remove Orders From Load Status Mappings</pluralLabel>
</CustomObject>

src/main/default/objects/RemoveOrdersFromLoadStatusMapping__mdt/fields/SetReplanToTrue__c.field-meta.xml
<CustomField>
    <fullName>SetReplanToTrue__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please check this if a Replan field should be set to true while changing status.</inlineHelpText>
    <label>Set Replan to True</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/RemoveOrdersFromLoadStatusMapping__mdt/fields/TargetOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>TargetOrderStatus__c</fullName>
    <inlineHelpText>Please use API name of existing Status that removed Order should have.</inlineHelpText>
    <label>Target Order Status</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>VEH-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Vehicle__c/fields/LoadCapacityWeight__c.field-meta.xml
<CustomField>
    <fullName>LoadCapacityWeight__c</fullName>
    <inlineHelpText>The Weight Load Capacity of this vehicle.</inlineHelpText>
    <label>Load Capacity (Weight)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/LoadPlanningAssignmentController.cls
/**
 * Created by svatopluk.sejkora on 13.10.2022.
 */

public with sharing class LoadPlanningAssignmentController {
    @AuraEnabled
    public static Decimal fetchVehicleLoadWeight(String vehicleId) {
        try {
            List<Vehicle__c> vehicles = [SELECT Id, LoadCapacityWeight__c FROM Vehicle__c WHERE Id = :vehicleId];
            return vehicles.isEmpty() ? 0 : vehicles[0].LoadCapacityWeight__c;
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new PopulateAuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Load__c upsertLoad(Load__c load) {
        try {
            upsert load Id;
            Load__c loadName = [SELECT Id, Name, DeliveryDate__c FROM Load__c WHERE Id = :load.Id];

            return loadName;
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new PopulateAuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateOrdersWithLoadIdAndNewStatus(List<String> orderIds, String newStatus, String loadId) {
        try {
            List<Order> ordersToUpdate = new List<Order>();
            for (String orderId : orderIds) {
                Order order = new Order();
                order.Id = orderId;
                order.Load__c = loadId;
                order.Status = newStatus;
                ordersToUpdate.add(order);
            }

            update ordersToUpdate;
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new PopulateAuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void processDeselectedOrders(List<Order> deselectedOrderIds) {
        try {
            Map<String, RemoveOrdersFromLoadStatusMapping__mdt> mappings = RemoveOrdersFromLoadStatusMapping__mdt.getAll();

            for (Order order : deselectedOrderIds) {
                String processedStatus = order.Status.deleteWhitespace().toLowerCase();
                if (mappings.containsKey(processedStatus)) {
                    order.Status = mappings.get(processedStatus).TargetOrderStatus__c;
                    order.Load__c = null;
                    if (mappings.get(processedStatus).SetReplanToTrue__c) {
                        order.Replanned__c = true;
                    }
                }
            }

            update deselectedOrderIds;
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, e.getMessage());
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            throw new PopulateAuraHandledException(e.getMessage());
        }
    }
}