src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/LastOrderDate__c.field-meta.xml
<CustomField>
    <fullName>LastOrderDate__c</fullName>
    <label>Last Order Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/AccountStatusUpdateSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata which stores configurable values used in the automation of the account status updates.</description>
    <label>Account Status Update Setting</label>
    <pluralLabel>Account Status Update Settings</pluralLabel>
</CustomObject>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/NoOfWeeksNoOrdersLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>NoOfWeeksNoOrdersLowerLimit__c</fullName>
    <label>No of Weeks No Orders - Lower Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/NoOfWeeksNoOrdersUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>NoOfWeeksNoOrdersUpperLimit__c</fullName>
    <label>No of Weeks No Orders - Upper Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusLowerLimit__c</fullName>
    <label>Updated Account Status - Lower Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusMidLimit__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusMidLimit__c</fullName>
    <label>Updated Account Status - Mid Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusRecentOrders__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusRecentOrders__c</fullName>
    <label>Updated Account Status - Recent Orders</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusUpperLimit__c</fullName>
    <label>Updated Account Status - Upper Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/AccountStatusUpdateBatchTest.cls
/**
 * Created by magdalena.stanciu on 14.09.2022.
 */

@IsTest
private with sharing class AccountStatusUpdateBatchTest {
    private static final AccountStatusUpdateSetting__mdt weeklyFreqSetting = AccountService.ACC_STATUS_UPDATE_SETTINGS.get('W');
    private static final AccountStatusUpdateSetting__mdt fortnightlyFreqSetting = AccountService.ACC_STATUS_UPDATE_SETTINGS.get('F');
    private static final AccountStatusUpdateSetting__mdt monthlyFreqSetting = AccountService.ACC_STATUS_UPDATE_SETTINGS.get('M');

    @IsTest
    private static void testWeeklyFrequencyNoOrders() {
        // create dp account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEW',
                LastOrderDate__c = null,
                AccountStatus__c = weeklyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                weeklyFreqSetting.UpdatedAccountStatusRecentOrders__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testWeeklyFrequencyRecentOrders() {
        // create dp account
        Date lastOrderDate = System.today();
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEW',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = weeklyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                weeklyFreqSetting.UpdatedAccountStatusRecentOrders__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testWeeklyFrequencyNoOrdersInLowerLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(weeklyFreqSetting.NoOfWeeksNoOrdersLowerLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEW',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = weeklyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                weeklyFreqSetting.UpdatedAccountStatusLowerLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testWeeklyFrequencyNoOrdersInMidLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(weeklyFreqSetting.NoOfWeeksNoOrdersMidLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEW',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = weeklyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                weeklyFreqSetting.UpdatedAccountStatusMidLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testWeeklyFrequencyNoOrdersInUpperLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(weeklyFreqSetting.NoOfWeeksNoOrdersUpperLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEW',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = weeklyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                weeklyFreqSetting.UpdatedAccountStatusUpperLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testFortnightlyFrequencyNoOrders() {
        // create dp account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WE1',
                LastOrderDate__c = null,
                AccountStatus__c = fortnightlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                fortnightlyFreqSetting.UpdatedAccountStatusRecentOrders__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testFortnightlyFrequencyRecentOrders() {
        // create dp account
        Date lastOrderDate = System.today();
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WE1',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = fortnightlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                fortnightlyFreqSetting.UpdatedAccountStatusRecentOrders__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testFortnightlyFrequencyNoOrdersInLowerLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(fortnightlyFreqSetting.NoOfWeeksNoOrdersLowerLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WE1',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = fortnightlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                fortnightlyFreqSetting.UpdatedAccountStatusLowerLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testFortnightlyFrequencyNoOrdersInMidLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(fortnightlyFreqSetting.NoOfWeeksNoOrdersMidLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WE1',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = fortnightlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                fortnightlyFreqSetting.UpdatedAccountStatusMidLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testFortnightlyFrequencyNoOrdersInUpperLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(fortnightlyFreqSetting.NoOfWeeksNoOrdersUpperLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WE1',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = fortnightlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                fortnightlyFreqSetting.UpdatedAccountStatusUpperLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testMonthlyFrequencyNoOrders() {
        // create dp account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEM',
                LastOrderDate__c = null,
                AccountStatus__c = monthlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                monthlyFreqSetting.UpdatedAccountStatusRecentOrders__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testMonthlyFrequencyRecentOrders() {
        // create dp account
        Date lastOrderDate = System.today();
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEM',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = monthlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                monthlyFreqSetting.UpdatedAccountStatusRecentOrders__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testMonthlyFrequencyNoOrdersInLowerLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(monthlyFreqSetting.NoOfWeeksNoOrdersLowerLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEM',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = monthlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                monthlyFreqSetting.UpdatedAccountStatusLowerLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testMonthlyFrequencyNoOrdersInMidLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(monthlyFreqSetting.NoOfWeeksNoOrdersMidLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEM',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = monthlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                monthlyFreqSetting.UpdatedAccountStatusMidLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }

    @IsTest
    private static void testMonthlyFrequencyNoOrdersInUpperLimitNoOfWeeks() {
        // create dp account
        Date lastOrderDate = System.today().addDays(- (7 * Integer.ValueOf(monthlyFreqSetting.NoOfWeeksNoOrdersUpperLimit__c) + 2));
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                PrimaryGridNumber__c = '3C7201WEM',
                LastOrderDate__c = lastOrderDate,
                AccountStatus__c = monthlyFreqSetting.UpdatedAccountStatusRecentOrders__c
        ));

        // run batch to update account status
        Test.startTest();
        Database.executeBatch(new AccountStatusUpdateBatch());
        Test.stopTest();

        // retrieve updated account
        Account updatedDPAccount = [
                SELECT Id, AccountStatus__c
                FROM Account
                WHERE Id = :dpAccount.Id
        ];

        // check results
        System.assertEquals(
                monthlyFreqSetting.UpdatedAccountStatusUpperLimit__c,
                updatedDPAccount.AccountStatus__c,
                'Expecting a different account status.'
        );
    }
}