src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1 fortnightly cycle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/LastOrderDate__c.field-meta.xml
<CustomField>
    <fullName>LastOrderDate__c</fullName>
    <label>Last Order Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/AccountStatusUpdateSetting__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata which stores configurable values used in the automation of the account status updates.</description>
    <label>Account Status Update Setting</label>
    <pluralLabel>Account Status Update Settings</pluralLabel>
</CustomObject>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/AccountFrequency__c.field-meta.xml
<CustomField>
    <fullName>AccountFrequency__c</fullName>
    <label>Account Frequency</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/NoOfWeeksNoOrdersLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>NoOfWeeksNoOrdersLowerLimit__c</fullName>
    <label>No of Weeks No Orders - Lower Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/NoOfWeeksNoOrdersUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>NoOfWeeksNoOrdersUpperLimit__c</fullName>
    <label>No of Weeks No Orders - Upper Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusLowerLimit__c</fullName>
    <label>Updated Account Status - Lower Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusMidLimit__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusMidLimit__c</fullName>
    <label>Updated Account Status - Mid Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusRecentOrders__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusRecentOrders__c</fullName>
    <label>Updated Account Status - Recent Orders</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/AccountStatusUpdateSetting__mdt/fields/UpdatedAccountStatusUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>UpdatedAccountStatusUpperLimit__c</fullName>
    <label>Updated Account Status - Upper Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/AccountStatusUpdateBatch.cls
/**
 * Created by magdalena.stanciu on 13.09.2022.
 */

public with sharing class AccountStatusUpdateBatch implements Database.Batchable<sObject>, Schedulable {
    private Map<Integer, String> orderFrequencyToBeProcessed = new Map<Integer, String>{
            1 => 'W',
            2 => 'F',
            3 => 'M'
    };

    private Integer order {
        get {
            if (order == null) {
                order = 1;
            }
            return order;
        }
        set;
    }

    private AccountStatusUpdateSetting__mdt setting {
        get {
            if (setting == null) {
                setting = AccountService.ACC_STATUS_UPDATE_SETTINGS.get(orderFrequencyToBeProcessed.get(order));
            }
            return setting;
        }
        set;
    }

    public AccountStatusUpdateBatch() {
    }

    private AccountStatusUpdateBatch(Integer order) {
        this.order = order;
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        String query = getQuery();
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<Account> accountsToProcess) {
        List<Account> accountsToUpdate = AccountService.updateAccountStatusBasedOnLastOrderDate(accountsToProcess);
        update accountsToUpdate;
    }

    public void finish(Database.BatchableContext context) {
        Integer nextBatchOrder = order + 1;
        if (nextBatchOrder <= 3) {
            AccountStatusUpdateBatch nextChainedBatch = new AccountStatusUpdateBatch(nextBatchOrder);
            Database.executeBatch(nextChainedBatch);
        }
    }

    public void execute(SchedulableContext context) {
        Database.executeBatch(new AccountStatusUpdateBatch());
    }

    private String getQuery() {
        String accountStatuses = '(\'' + String.join(AccountService.STATUSES_TO_UPDATE_WHEN_NO_RECENT_ORDERS, '\',\'') + '\')';
        String query =
                'SELECT Id, LastOrderDate__c, Frequency__c, AccountStatus__c ' +
                'FROM Account ' +
                'WHERE AccountStatus__c IN ' + accountStatuses + ' ' +
                'AND Frequency__c = \'' + setting.AccountFrequency__c + '\' AND LastOrderDate__c != null AND (' +
                    '(LastOrderDate__c < LAST_N_DAYS:' + (Integer.ValueOf(setting.NoOfWeeksNoOrdersUpperLimit__c) * 7) + ' AND AccountStatus__c != \'' + setting.UpdatedAccountStatusUpperLimit__c + '\') OR ' +
                    '(LastOrderDate__c < LAST_N_DAYS:' + (Integer.ValueOf(setting.NoOfWeeksNoOrdersMidLimit__c) * 7) + ' AND AccountStatus__c != \'' + setting.UpdatedAccountStatusMidLimit__c + '\') OR ' +
                    '(LastOrderDate__c < LAST_N_DAYS:' + (Integer.ValueOf(setting.NoOfWeeksNoOrdersLowerLimit__c) * 7) + ' AND AccountStatus__c != \'' + setting.UpdatedAccountStatusLowerLimit__c + '\') OR ' +
            		'(LastOrderDate__c >= LAST_N_DAYS:' + (Integer.ValueOf(setting.NoOfWeeksNoOrdersLowerLimit__c) * 7) + ' AND AccountStatus__c != \'' + setting.UpdatedAccountStatusRecentOrders__c + '\') ' +
            	')';
        return query;
    }
}