src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/CreateCalls__c.field-meta.xml
<CustomField>
    <fullName>CreateCalls__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create Calls</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>PrimaryStartDate__c</fullName>
    <label>Primary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/aforza__Recurring_Record__c.object-meta.xml
<CustomObject>
    <description>An object that controls when a record recurs.</description>
    <label>Recurring Record</label>
    <nameField>
        <label>Recurring Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Recurring_Record__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Account with Record Type of &quot;Outlet&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Outlet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Records</relationshipLabel>
    <relationshipName>Recurring_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Frequency__c.field-meta.xml
<CustomField>
    <fullName>aforza__Frequency__c</fullName>
    <description>The frequency at which this recurring record should happen.</description>
    <inlineHelpText>The frequency at which this recurring record should happen.</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Week-ly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 fortnightly cycle</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Month-ly</label>
            </value>
            <value>
                <fullName>Annually</fullName>
                <isActive>false</isActive>
                <label>Annually</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
                <isActive>false</isActive>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Last_Recurrence_Date__c.field-meta.xml
<CustomField>
    <fullName>aforza__Last_Recurrence_Date__c</fullName>
    <description>The date for the last recurring record to be scheduled on.</description>
    <inlineHelpText>The date for the last recurring record to be scheduled on.</inlineHelpText>
    <label>Last Recurrence Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Number_Of_Recurrences__c.field-meta.xml
<CustomField>
    <fullName>aforza__Number_Of_Recurrences__c</fullName>
    <description>The number of recurrences the record should recur.</description>
    <inlineHelpText>The number of recurrences the record should recur.</inlineHelpText>
    <label>Number Of Recurrences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of recurring record.</description>
    <inlineHelpText>The type of recurring record.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/CallDayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>CallDayOfWeek__c</fullName>
    <label>Call Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/DaysBetweenRecurrence__c.field-meta.xml
<CustomField>
    <fullName>DaysBetweenRecurrence__c</fullName>
    <formula>CASE(
				aforza__Frequency__c,
				&apos;W&apos;, 7, 
				&apos;F&apos;, 14,
				&apos;M&apos;, 28,
				0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Number of days calculated from frequency: W - 7, F - 14, M - 28</inlineHelpText>
    <label>Days Between Recurrence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/PlanAnotherVisit__c.field-meta.xml
<CustomField>
    <fullName>PlanAnotherVisit__c</fullName>
    <formula>IF(ISBLANK(aforza__Last_Recurrence_Date__c), TRUE, aforza__Last_Recurrence_Date__c &lt; (NOW() + (DaysBetweenRecurrence__c * aforza__Number_Of_Recurrences__c)))</formula>
    <inlineHelpText>Will be true when Last Recurrence Date plus Days Between Recurrence is smaller than actual date.</inlineHelpText>
    <label>Plan Another Visit</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Date of the first visit planned for this recurrence.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Call_Priority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <description>A call priority selection.</description>
    <masterLabel>Call Priority</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/WeekDays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Monday</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Tuesday</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Wednesday</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Thursday</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Friday</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Error</label>
    </customValue>
    <masterLabel>Week Days</masterLabel>
</GlobalValueSet>

src/main/default/classes/AccountTeamMemberTriggerHandlerTest.cls
/**
 * Created by svatopluk.sejkora on 01.10.2022.
 */

@IsTest
private class AccountTeamMemberTriggerHandlerTest {
    @IsTest
    private static void testManageReoccurrenceRecord() {
        Test.startTest();
        TdfSObjectFactory.insertSObject(new AccountTeamMember());
        Test.stopTest();

        aforza__Recurring_Record__c record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ][0];

        System.assertNotEquals(null, record);
    }

    @IsTest
    private static void testManageReoccurrenceRecord_InsertNoCreateCallChecked() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, CreateCalls__c = false));

        Test.startTest();
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testManageReoccurrenceRecord_InsertWrongStatus() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Legal'));
        Test.startTest();
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testManageReoccurrenceRecord_InsertWrongRecordType() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_CUSTOMER_ID));

        Test.startTest();
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testManageReoccurrenceRecord_InsertNoPrimaryGrid() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, PrimaryGridNumber__c = null));

        Test.startTest();
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testManageReoccurrenceRecord_InsertNoStartDate() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, PrimaryStartDate__c = null));

        Test.startTest();
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testManageReoccurrenceRecord_OutStatus() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));

        List<aforza__Recurring_Record__c> checkIfExistsRecord = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];
        System.assertEquals(1, checkIfExistsRecord.size());

        Test.startTest();
        acc.AccountStatus__c = 'Legal';
        update acc;
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testManageReoccurrenceRecord_DeleteTamRecord() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );
        AccountTeamMember accountTeamMember = (AccountTeamMember) TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));

        List<aforza__Recurring_Record__c> checkIfExistsRecord = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];
        System.assertEquals(1, checkIfExistsRecord.size());

        Test.startTest();
        delete accountTeamMember;
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testManageReoccurrenceRecord_ChangeToNotTam() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );
        AccountTeamMember accountTeamMember = (AccountTeamMember) TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));

        List<aforza__Recurring_Record__c> checkIfExistsRecord = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];
        System.assertEquals(1, checkIfExistsRecord.size());

        Test.startTest();
        accountTeamMember.TeamMemberRole = 'Driver';
        update accountTeamMember;
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id,
                        aforza__Type__c,
                        Account__c,
                        OwnerId,
                        Status__c,
                        aforza__Frequency__c,
                        Name,
                        StartDate__c,
                        PlanAnotherVisit__c,
                        DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c,
                        CallDayOfWeek__c,
                        Priority__c,
                        aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, record.size());
    }

    @IsTest
    private static void testAllowOnlyOneTamUserPerAccount() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));

        Test.startTest();
        try {
            TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));
            System.assert(false, 'We expect an error to be thrown');
        } catch (Exception e) {
            System.assertEquals('Exceptions.TdfSObjectFactoryException', e.getTypeName());
            System.assert(e.getMessage().contains('There can be only one TAM user assigned to each'));
        }
        Test.stopTest();
    }

    @IsTest
    private static void testAllowOnlyOneTamUserPerAccount_DifferentMember() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );
        TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id));

        User user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs(user) {
            User newUser = (User) TdfSObjectFactory.insertSObject(new User());

            Test.startTest();
            TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id, TeamMemberRole = 'Driver', UserId = newUser.Id));
            Test.stopTest();
        }

        List<AccountTeamMember> members = [SELECT Id FROM AccountTeamMember WHERE AccountId = :acc.Id];

        System.assertEquals(2, members.size());
    }

    @IsTest
    private static void testAllowOnlyOneTamUserPerAccount_TryMoreTamsInSingleTransaction() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );

        User user = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        System.runAs(user) {
            User newUser = (User) TdfSObjectFactory.insertSObject(new User());
            List<AccountTeamMember> accountTeamMembers = new List<AccountTeamMember>();
            accountTeamMembers.add((AccountTeamMember) TdfSObjectFactory.createSObject(new AccountTeamMember(AccountId = acc.Id)));
            accountTeamMembers.add((AccountTeamMember) TdfSObjectFactory.createSObject(new AccountTeamMember(AccountId = acc.Id, UserId = newUser.Id)));

            Test.startTest();
            try {
                insert accountTeamMembers;
                System.assert(false, 'We expect an error to be thrown');
            } catch (Exception e) {
                System.assertEquals('System.DmlException', e.getTypeName());
                System.assert(e.getMessage().contains('There can be only one TAM user assigned to each'));
            }
            Test.stopTest();
        }
    }

    @IsTest
    private static void testManageReoccurrenceRecord_ChangeToTam() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)
        );
        AccountTeamMember accountTeamMember = (AccountTeamMember) TdfSObjectFactory.insertSObject(new AccountTeamMember(AccountId = acc.Id, TeamMemberRole = 'Driver'));

        List<aforza__Recurring_Record__c> recordFirst = [
                SELECT
                        Id
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(0, recordFirst.size());

        Test.startTest();
        accountTeamMember.TeamMemberRole = 'TAM';
        update accountTeamMember;
        Test.stopTest();

        List<aforza__Recurring_Record__c> record = [
                SELECT
                        Id
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ];

        System.assertEquals(1, record.size());
    }
}