src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1 fortnightly cycle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/NextDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>NextDeliveryDate__c</fullName>
    <formula>IF(
    NextDeliveryDateHidden__c &gt;= TODAY(),
    NextDeliveryDateHidden__c,
    IF(
        OR(ISPICKVAL(Depot__c, &quot;C&quot;), ISPICKVAL(Depot__c,&quot;Z&quot;), ISPICKVAL(Depot__c, &quot;B&quot;)),
        DATEVALUE(  NextCallDate__c ) +
            CASE(
              WEEKDAY(DATEVALUE( NextCallDate__c )),
               1, 1,
               2, 1,
               3, 1,
               4, 1,
               5, 1,
               6, 3,
               7, 2,
             0),
        DATEVALUE( NextCallDate__c ) +
            CASE(
              WEEKDAY(DATEVALUE( NextCallDate__c )),
               1, 2,
               2, 2,
               3, 2,
               4, 2,
               5, 4,
               6, 4,
               7, 3,
             0)
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Delivery Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryDeliveryDay__c.field-meta.xml
<CustomField>
    <fullName>PrimaryDeliveryDay__c</fullName>
    <label>Primary Delivery Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>PrimaryStartDate__c</fullName>
    <label>Primary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Account/fields/SecondaryDeliveryDay__c.field-meta.xml
<CustomField>
    <fullName>SecondaryDeliveryDay__c</fullName>
    <label>Secondary Delivery Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/SecondaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>SecondaryGridNumber__c</fullName>
    <label>Secondary Grid Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/SecondaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>SecondaryStartDate__c</fullName>
    <label>Secondary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/globalValueSets/WeekDays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Monday</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Tuesday</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Wednesday</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Thursday</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Friday</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Error</label>
    </customValue>
    <masterLabel>Week Days</masterLabel>
</GlobalValueSet>

src/main/default/classes/AccountNextDeliveryDateUpdateBatch.cls
/**
 * Created by magdalena.stanciu on 03.01.2023.
 */

public with sharing class AccountNextDeliveryDateUpdateBatch implements Database.Batchable<SObject>, Schedulable {
    public Database.QueryLocator start(Database.BatchableContext context) {
        String query = getQuery();
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<Account> accountsToProcess) {
        List<Account> accountsToUpdate = new List<Account>();
        for (Account newAccount : accountsToProcess) {
            Date newDeliveryDate = AccountService.computeNextDeliveryDate(newAccount);
            if (newAccount.NextDeliveryDate__c != newDeliveryDate) {
                newAccount.NextDeliveryDate__c = newDeliveryDate;
                accountsToUpdate.add(newAccount);
            }
        }
        update accountsToUpdate;
    }

    public void finish(Database.BatchableContext context) {

    }

    public void execute(SchedulableContext context) {
        Database.executeBatch(new AccountNextDeliveryDateUpdateBatch());
    }

    private String getQuery() {
        String accountStatuses = '(\'' + String.join(AccountService.STATUSES_TO_UPDATE_NEXT_DELIVERY_DATE, '\',\'') + '\')';
        String query =
            'SELECT Id, NextDeliveryDate__c, PrimaryGridNumber__c, SecondaryGridNumber__c, Frequency__c, PrimaryDeliveryDay__c, SecondaryDeliveryDay__c, PrimaryStartDate__c, SecondaryStartDate__c ' +
            'FROM Account ' +
            'WHERE AccountStatus__c IN ' + accountStatuses;
        return query;
    }
}