src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/aforza__Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>A specific charge or listing on a customer&apos;s invoice.</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/aforza__Invoice__c.field-meta.xml
<CustomField>
    <fullName>aforza__Invoice__c</fullName>
    <description>The invoice the line item is for.</description>
    <inlineHelpText>The invoice the line item is for.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Billing_Statement_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/InvoicePDFControllerTest.cls
/**
 * @description       :
 * @author            : Ciuca Bianca BearingPoint GmbH
 * @group             :
 * @last modified on  : 10-07-2022
 * @last modified by  : Ciuca Bianca, BearingPoint GmbH
 **/

@IsTest
public with sharing class InvoicePDFControllerTest {
	@IsTest
	static void testInvoicePDFController() {
		Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
			new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
		);
		Order newOrder = (Order) TdfSObjectFactory.insertSObject(
			new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID, AccountId = dpAccount.Id, Status = 'Draft')
		);
		aforza__Invoice__c newInvoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(
			new aforza__Invoice__c(aforza__Account__c = dpAccount.Id, aforza__Order__c = newOrder.Id, aforza__Reference__c = '10')
		);
		aforza__Invoice_Line_Item__c newInvoiceLineItem = (aforza__Invoice_Line_Item__c) TdfSObjectFactory.insertSObject(
			new aforza__Invoice_Line_Item__c(aforza__Invoice__c = newInvoice.Id)
		);

		insertContentVersion();
		insertContentDocumentLink(newOrder.Id);

		Test.startTest();
		PageReference testPage = Page.AGBarrInvoice;
		Test.setCurrentPage(testPage);
		testPage.getParameters().put('id', newInvoice.Id);
		InvoicePDFController.attachPDF(newInvoice.Id);
		InvoicePDFController testPdfController = new InvoicePDFController();
		Test.stopTest();
	}

	public static void insertContentVersion() {
		ContentVersion contentVersion = new Contentversion();
		contentVersion.Title = 'Signature Test';
		contentVersion.PathOnClient = 'Test';
		Blob b = Blob.valueOf('Unit Test Attachment Body');
		contentVersion.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
		insert contentVersion;
	}

	public static void insertContentDocumentLink(Id linkedRecordId) {
		Id insertedContentVersion = [SELECT ContentDocumentId FROM ContentVersion].ContentDocumentId;
		ContentDocumentLink contentDocLink = new ContentDocumentLink(
			LinkedEntityId = linkedRecordId,
			ContentDocumentId = insertedContentVersion,
			ShareType = 'V'
		);
		insert contentDocLink;
	}
}