src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/DdActive__c.field-meta.xml
<CustomField>
    <fullName>DdActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Active?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/Account/fields/DirectDebitMandateRef__c.field-meta.xml
<CustomField>
    <fullName>DirectDebitMandateRef__c</fullName>
    <label>Direct Debit Mandate Ref.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/AccountServiceTest.cls
@IsTest
public class AccountServiceTest {	
@IsTest
    private static void testDdMandateCreationHandlerStageOver6(){
         // create dp account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
        );
    
        Account accRef1 = [SELECT Id, DeliveryPointReference__c, DdActive__c, DirectDebitMandateRef__c FROM Account WHERE Id =:dpAccount.id];
        
        System.assertEquals(FALSE, accRef1.DdActive__c);
		
        String deliveryRef = accRef1.DeliveryPointReference__c;
        DdMandateCreationController.ddMandateCreationHandler(deliveryRef, '9');
        Account accRef2 = [SELECT Id, DeliveryPointReference__c, DdActive__c, DirectDebitMandateRef__c FROM Account WHERE Id =:dpAccount.id];

        System.assertEquals(TRUE, accRef2.DdActive__c);
        System.assertEquals(deliveryRef, accRef2.DirectDebitMandateRef__c);
    }
	
    @IsTest
    private static void testDdMandateCreationHandlerStage6OrBelow(){
         // create dp account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
        );
    
        Account accRef1 = [SELECT Id, DeliveryPointReference__c, DdActive__c, DirectDebitMandateRef__c FROM Account WHERE Id =:dpAccount.id];
        
        System.assertEquals(FALSE, accRef1.DdActive__c);
		
        String deliveryRef = accRef1.DeliveryPointReference__c;
        DdMandateCreationController.ddMandateCreationHandler(deliveryRef, '4');
        Account accRef2 = [SELECT Id, DeliveryPointReference__c, DdActive__c, DirectDebitMandateRef__c FROM Account WHERE Id =:dpAccount.id];

        System.assertEquals(FALSE, accRef2.DdActive__c, 'DD Active should be false');
        System.assertNotEquals(deliveryRef, accRef2.DirectDebitMandateRef__c);
    }
}