src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/InvoiceType__c.field-meta.xml
<CustomField>
    <fullName>InvoiceType__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>EDI</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>In-Store</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/InvoiceType__c.field-meta.xml
<CustomField>
    <fullName>InvoiceType__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceType</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/aforza__Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>A specific charge or listing on a customer&apos;s invoice.</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/aforza__Invoice__c.field-meta.xml
<CustomField>
    <fullName>aforza__Invoice__c</fullName>
    <description>The invoice the line item is for.</description>
    <inlineHelpText>The invoice the line item is for.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Billing_Statement_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/aforza__Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>A monetary transaction against a specific account.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PTR-{00000000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the payment transaction has been enacted against.</description>
    <inlineHelpText>The account the payment transaction has been enacted against.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/globalValueSets/InvoiceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <masterLabel>Invoice Type</masterLabel>
</GlobalValueSet>

src/main/default/classes/InvoiceServiceTest.cls
/**
 * @description       :
 * @author            : Ciuca Bianca BearingPoint GmbH
 * @group             :
 * @last modified on  : 10-07-2022
 * @last modified by  : Ciuca Bianca, BearingPoint GmbH
 **/
@IsTest
private with sharing class InvoiceServiceTest {
	@IsTest
	private static void testCreateInvoicesFromOrders_NoDocumentGenerated() {
		// create product
		Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(
				new Product2(Name = 'Test Product', ProductCode = 'SKU1')
		);

		// add new product to standard PB
		TdfSObjectFactory.insertSObject(
				new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId)
		);

		// create pricebook and add products to pricebook
		Pricebook2 newPricebook = (Pricebook2) TdfSObjectFactory.insertSObject(new Pricebook2());
		PricebookEntry newPricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
				new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = newPricebook.Id)
		);

		// create account
		Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
				new Account(
						RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
						AccountStatus__c = 'Traders',
						aforza__Default_Price_Book__c = newPricebook.Id
				)
		);

		// create order and add items to the order
		Order newOrder = (Order) TdfSObjectFactory.insertSObject(
				new Order(
						RecordTypeId = RecordTypes.ORDER_TELESALES_ID,
						AccountId = dpAccount.Id,
						Status = 'Draft',
						Pricebook2Id = newPricebook.Id
				)
		);
		OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
				new OrderItem(
						OrderId = newOrder.Id,
						Product2Id = newProduct.Id,
						PricebookEntryId = newPricebookEntry.Id
				)
		);

		Test.startTest();
		InvoiceService.createInvoicesFromOrders(new Set<Id>{ newOrder.Id });
		Test.stopTest();

		// retrieve invoice and invoice line items, validate results
		List<aforza__Invoice__c> invoices = [SELECT Id FROM aforza__Invoice__c WHERE aforza__Order__c = :newOrder.Id];
		System.assertEquals(1, invoices.size());

		List<aforza__Invoice_Line_Item__c> invoiceLineItems = [
			SELECT Id
			FROM aforza__Invoice_Line_Item__c
			WHERE aforza__Invoice__c IN :invoices
		];
		System.assertEquals(1, invoiceLineItems.size());

		List<ContentDocumentLink> relatedFiles = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :invoices[0].Id];
		System.assertEquals(0, relatedFiles.size());

		List<Task> relatedActivities = [SELECT Id FROM Task WHERE WhatId = :invoices[0].Id];
		System.assertEquals(0, relatedActivities.size());
	}

	@IsTest
	private static void testCreateInvoicesFromOrders_DocumentGenerated() {
		// create product
		Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(
				new Product2(Name = 'Test Product', ProductCode = 'SKU1')
		);

		// add new product to standard PB
		TdfSObjectFactory.insertSObject(
				new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId)
		);

		// create pricebook and add products to pricebook
		Pricebook2 newPricebook = (Pricebook2) TdfSObjectFactory.insertSObject(new Pricebook2());
		PricebookEntry newPricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
				new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = newPricebook.Id)
		);

		// create account
		Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
				new Account(
						RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
						AccountStatus__c = 'Traders',
						InvoiceType__c = 'Email',
						aforza__Invoice_Email_Address__c = 'test@test.com',
						aforza__Default_Price_Book__c = newPricebook.Id
				)
		);

		Contact newContact = (Contact) TdfSObjectFactory.insertSObject(
				new Contact(AccountId = dpAccount.Id, Email = 'test@test.com')
		);
		dpAccount.aforza__Primary_Contact__c = newContact.Id;
		update dpAccount;

		// create order and add items to the order
		Order newOrder = (Order) TdfSObjectFactory.insertSObject(
				new Order(
						RecordTypeId = RecordTypes.ORDER_TELESALES_ID,
						AccountId = dpAccount.Id,
						Status = 'Draft',
						Pricebook2Id = newPricebook.Id
				)
		);
		OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
				new OrderItem(
						OrderId = newOrder.Id,
						Product2Id = newProduct.Id,
						PricebookEntryId = newPricebookEntry.Id
				)
		);

		Test.startTest();
		InvoiceService.createInvoicesFromOrders(new Set<Id>{ newOrder.Id });
		Test.stopTest();

		// retrieve invoice and invoice line items, validate results
		List<aforza__Invoice__c> invoices = [SELECT Id FROM aforza__Invoice__c WHERE aforza__Order__c = :newOrder.Id];
		System.assertEquals(1, invoices.size());

		List<aforza__Invoice_Line_Item__c> invoiceLineItems = [
				SELECT Id
				FROM aforza__Invoice_Line_Item__c
				WHERE aforza__Invoice__c IN :invoices
		];
		System.assertEquals(1, invoiceLineItems.size());

		List<ContentDocumentLink> relatedFiles = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :invoices[0].Id];
		System.assertEquals(1, relatedFiles.size());

		List<Task> relatedActivities = [SELECT Id FROM Task WHERE WhatId = :invoices[0].Id];
		System.assertEquals(1, relatedActivities.size());
	}

	@IsTest
	private static void testGetPaymentTransactions() {
		Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
			new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
		);

		Order newOrder = (Order) TdfSObjectFactory.insertSObject(
			new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID, AccountId = dpAccount.Id, Status = 'Draft')
		);

		aforza__Payment_Transaction__c newPayment = (aforza__Payment_Transaction__c) TdfSObjectFactory.insertSObject(
			new aforza__Payment_Transaction__c(aforza__Account__c = dpAccount.Id, OrderNumber__c = newOrder.Id)
		);

		// retrieve payment and validate result
		List<aforza__Payment_Transaction__c> transactions = InvoiceService.getPaymentTransactions(new Set<Id>{ newOrder.Id });
		System.assertEquals(1, transactions.size());
	}

	@IsTest
	private static void testGenerateInvoiceFromOrder() {
		// create product
		Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(
				new Product2(Name = 'Test Product', ProductCode = 'SKU1')
		);

		// add new product to standard PB
		TdfSObjectFactory.insertSObject(
				new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId)
		);

		// create pricebook and add products to pricebook
		Pricebook2 newPricebook = (Pricebook2) TdfSObjectFactory.insertSObject(new Pricebook2());
		PricebookEntry newPricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
				new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = newPricebook.Id)
		);

		// create account
		Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
				new Account(
						RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
						AccountStatus__c = 'Traders',
						aforza__Default_Price_Book__c = newPricebook.Id
				)
		);

		// create order and add items to the order
		Order newOrder = (Order) TdfSObjectFactory.insertSObject(
				new Order(
						RecordTypeId = RecordTypes.ORDER_TELESALES_ID,
						AccountId = dpAccount.Id,
						Status = 'Draft',
						Pricebook2Id = newPricebook.Id
				)
		);
		OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
				new OrderItem(
						OrderId = newOrder.Id,
						Product2Id = newProduct.Id,
						PricebookEntryId = newPricebookEntry.Id
				)
		);

		aforza__Invoice__c newInvoice = new aforza__Invoice__c();

		Test.startTest();
		InvoiceService.generateInvoiceFromOrder(newInvoice, newOrder);
		Test.stopTest();

		System.assertEquals(newOrder.Id, newInvoice.aforza__Order__c);
	}

	@IsTest
	private static void testGetOrders() {
		Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
			new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
		);

		Order newOrder = (Order) TdfSObjectFactory.insertSObject(
			new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID, AccountId = dpAccount.Id, Status = 'Draft')
		);

		Test.startTest();
		List<Order> orders = InvoiceService.getOrders(new Set<Id>{ newOrder.Id });
		Test.stopTest();

		System.assertEquals(1, orders.size());
	}

	@IsTest
	private static void getInvoices() {
		// create dp account
		Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
			new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
		);

		// create related order
		Order newOrder = (Order) TdfSObjectFactory.insertSObject(
			new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID, AccountId = dpAccount.Id, Status = 'Draft')
		);

		// create Invoice
		aforza__Invoice__c newInvoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(
			new aforza__Invoice__c(aforza__Account__c = dpAccount.Id, aforza__Order__c = newOrder.Id)
		);

		Test.startTest();
		List<aforza__Invoice__c> invoices = InvoiceService.getInvoices(new Set<Id>{ newOrder.Id });
		Test.stopTest();

		System.assertEquals(1, invoices.size());
	}
}