src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/BillToName__c.field-meta.xml
<CustomField>
    <fullName>BillToName__c</fullName>
    <formula>IF(DefaultInvoiceBillingAddress__c,  Parent.Name , Name )</formula>
    <label>Bill To Name</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/BillToReference__c.field-meta.xml
<CustomField>
    <fullName>BillToReference__c</fullName>
    <label>Bill To Reference</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Account/fields/CustomerShopNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerShopNumber__c</fullName>
    <label>Customer Shop Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/BillToAddress__c.field-meta.xml
<CustomField>
    <fullName>BillToAddress__c</fullName>
    <label>Bill To Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/BillToArea__c.field-meta.xml
<CustomField>
    <fullName>BillToArea__c</fullName>
    <label>Bill To Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/BillToCountry__c.field-meta.xml
<CustomField>
    <fullName>BillToCountry__c</fullName>
    <label>Bill To Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/BillToName__c.field-meta.xml
<CustomField>
    <fullName>BillToName__c</fullName>
    <label>Bill To Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/BillToPostcode__c.field-meta.xml
<CustomField>
    <fullName>BillToPostcode__c</fullName>
    <label>Bill To Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/BillToReference__c.field-meta.xml
<CustomField>
    <fullName>BillToReference__c</fullName>
    <label>Bill To Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/BillToTown__c.field-meta.xml
<CustomField>
    <fullName>BillToTown__c</fullName>
    <label>Bill To Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/CustomerShopNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerShopNumber__c</fullName>
    <label>Customer Shop Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DiscountTotal__c.field-meta.xml
<CustomField>
    <fullName>DiscountTotal__c</fullName>
    <label>Discount Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DpAddress__c.field-meta.xml
<CustomField>
    <fullName>DpAddress__c</fullName>
    <label>DP Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DpArea__c.field-meta.xml
<CustomField>
    <fullName>DpArea__c</fullName>
    <label>DP Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DpCountry__c.field-meta.xml
<CustomField>
    <fullName>DpCountry__c</fullName>
    <label>DP Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DpName__c.field-meta.xml
<CustomField>
    <fullName>DpName__c</fullName>
    <label>DP Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DpPostcode__c.field-meta.xml
<CustomField>
    <fullName>DpPostcode__c</fullName>
    <label>DP Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DpReference__c.field-meta.xml
<CustomField>
    <fullName>DpReference__c</fullName>
    <label>DP Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DpTown__c.field-meta.xml
<CustomField>
    <fullName>DpTown__c</fullName>
    <label>DP Town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/NetTotal__c.field-meta.xml
<CustomField>
    <fullName>NetTotal__c</fullName>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PaymentInstruction__c.field-meta.xml
<CustomField>
    <fullName>PaymentInstruction__c</fullName>
    <label>Payment Instruction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethod</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PoNumber__c.field-meta.xml
<CustomField>
    <fullName>PoNumber__c</fullName>
    <label>Po Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PrintName__c.field-meta.xml
<CustomField>
    <fullName>PrintName__c</fullName>
    <label>Print Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/Vat__c.field-meta.xml
<CustomField>
    <fullName>Vat__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/aforza__Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>A specific charge or listing on a customer&apos;s invoice.</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/aforza__Invoice__c.field-meta.xml
<CustomField>
    <fullName>aforza__Invoice__c</fullName>
    <description>The invoice the line item is for.</description>
    <inlineHelpText>The invoice the line item is for.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Billing_Statement_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/SkuCode__c.field-meta.xml
<CustomField>
    <fullName>SkuCode__c</fullName>
    <label>SKU Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/SkuName__c.field-meta.xml
<CustomField>
    <fullName>SkuName__c</fullName>
    <label>SKU Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/VatRate__c.field-meta.xml
<CustomField>
    <fullName>VatRate__c</fullName>
    <label>VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Order/fields/DiscountTotal__c.field-meta.xml
<CustomField>
    <fullName>DiscountTotal__c</fullName>
    <label>Discount Total</label>
    <summarizedField>OrderItem.UnitPrice</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.aforza__Type__c</field>
        <operation>equals</operation>
        <value>Discount</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/Order/fields/DPName__c.field-meta.xml
<CustomField>
    <fullName>DPName__c</fullName>
    <label>DP Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/DPReference__c.field-meta.xml
<CustomField>
    <fullName>DPReference__c</fullName>
    <label>DP Reference</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <label>Grid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A linked Invoice.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/NetTotal__c.field-meta.xml
<CustomField>
    <fullName>NetTotal__c</fullName>
    <formula>TotalAmount - DiscountTotal__c -  TaxTotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Order/fields/PrintName__c.field-meta.xml
<CustomField>
    <fullName>PrintName__c</fullName>
    <label>Print Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/main/default/globalValueSets/PaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>Bacs</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Card Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
        <isActive>false</isActive>
        <label>Credit</label>
    </customValue>
    <customValue>
        <fullName>Buying Group Central Billing</fullName>
        <isActive>false</isActive>
        <label>Buying Group Central Billing</label>
    </customValue>
    <description>Global value set defining the possible payment methods - used on the account level</description>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/PaymentTerms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>STD</fullName>
    </customValue>
    <customValue>
        <fullName>TMA</fullName>
    </customValue>
    <customValue>
        <fullName>TWA</fullName>
    </customValue>
    <customValue>
        <fullName>50D</fullName>
    </customValue>
    <customValue>
        <fullName>21D</fullName>
    </customValue>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

src/main/default/classes/InvoiceGenerationServiceTest.cls
/**
 * Created by magdalena.stanciu on 10.11.2022.
 */

@IsTest
private class InvoiceGenerationServiceTest {
    @IsTest
    static void testConstructor() {
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
        );
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(
            new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID, AccountId = dpAccount.Id, Status = 'Draft')
        );
        aforza__Invoice__c newInvoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(
            new aforza__Invoice__c(aforza__Account__c = dpAccount.Id, aforza__Order__c = newOrder.Id, aforza__Reference__c = '10')
        );
        TdfSObjectFactory.insertSObject(
            new aforza__Invoice_Line_Item__c(aforza__Invoice__c = newInvoice.Id)
        );
        ContentVersion signature = (ContentVersion) TdfSObjectFactory.insertSObject(
            new ContentVersion(Title = 'Signature Test', PathOnClient = 'Test', VersionData = EncodingUtil.base64Decode('Body'))
        );
        String signatureDocId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :signature.Id].ContentDocumentId;
        TdfSObjectFactory.insertSObject(
            new ContentDocumentLink(ContentDocumentId = signatureDocId, LinkedEntityId = newOrder.Id, ShareType = 'V')
        );

        Test.startTest();
        InvoiceGenerationService service = new InvoiceGenerationService(new List<String>{newInvoice.Id});
        Test.stopTest();

        Assert.areEqual(1, InvoiceGenerationService.retrievedInvoices.size());
        Assert.areEqual(1, InvoiceGenerationService.orderIdSignatureDocumentId.size());
    }

    @IsTest
    static void testGenerateData() {
        // create product
        Product2 newProduct1 = (Product2) TdfSObjectFactory.insertSObject(new Product2());
        Product2 newProduct2 = (Product2) TdfSObjectFactory.insertSObject(new Product2());

        // add new product to standard PB
        TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct1.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId)
        );
        TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct2.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId)
        );

        // create custom pricebook and add product to pricebook
        Pricebook2 newPricebook = (Pricebook2) TdfSObjectFactory.insertSObject(new Pricebook2());
        PricebookEntry product1PricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct1.Id, Pricebook2Id = newPricebook.Id, aforza__Tax_Percent__c = 10)
        );
        PricebookEntry product2PricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct2.Id, Pricebook2Id = newPricebook.Id, aforza__Tax_Percent__c = 15)
        );

        // create account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
            aforza__Default_Price_Book__c = newPricebook.Id,
            RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
            PrimaryGridNumber__c = '3C7201MOW',
            PaymentTerms__c = 'STD',
            aforza__Credit_Amount__c = 200
        ));

        // create orders and add products to it
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(
            RecordTypeId = RecordTypes.ORDER_FIELD_DIRECT_ID,
            AccountId = dpAccount.Id,
            Grid__c = '3C7201MOW',
            Pricebook2Id = newPricebook.Id
        ));
        TdfSObjectFactory.insertSObject(new OrderItem(
            OrderId = newOrder.Id,
            Product2Id = newProduct1.Id,
            Quantity = 10,
            PricebookEntryId = product1PricebookEntry.Id
        ));
        TdfSObjectFactory.insertSObject(new OrderItem(
            OrderId = newOrder.Id,
            Product2Id = newProduct2.Id,
            Quantity = 10,
            PricebookEntryId = product2PricebookEntry.Id
        ));

        // mark order as receipted
        newOrder.Status = 'Receipted';
        update newOrder;

        Order updatedOrder = [SELECT Id, Invoice__c FROM Order WHERE Id = :newOrder.Id];

        Test.startTest();
        InvoiceGenerationService service = new InvoiceGenerationService(new List<String>{updatedOrder.Invoice__c});
        List<InvoiceGenerationService.Invoice> generatedInvoices = service.generateData();
        Test.stopTest();

        aforza__Invoice__c existingInvoice = [
            SELECT
                Id, Name, CreatedDate, PaymentTerms__c, aforza__Due_Date__c, PoNumber__c, PaymentInstruction__c, PrintName__c,
                aforza__Order__c, aforza__Order__r.OrderNumber, CustomerShopNumber__c, NetTotal__c, Vat__c, Gross__c, DiscountTotal__c,
                DpReference__c, DpName__c, DpAddress__c, DpArea__c, DpTown__c, DpCountry__c, DpPostCode__c,
                BillToReference__c, BillToName__c, BillToAddress__c, BillToArea__c, BillToTown__c, BillToCountry__c, BillToPostCode__c,
                (
                    SELECT Id, SkuCode__c, SkuName__c, Quantity__c, UnitPrice__c, VatRate__c, Vat__c, NetPrice__c
                    FROM aforza__Billing_Statement_Line_Items__r
                    WHERE SkuName__c != 'Tax' AND SkuName__c != 'Discount'
                )
            FROM aforza__Invoice__c
            WHERE Id = :updatedOrder.Invoice__c
        ];

        // results
        Assert.areEqual(1, generatedInvoices.size());

        Assert.areEqual(existingInvoice.BillToName__c, generatedInvoices[0].billToName);
        Assert.areEqual(existingInvoice.BillToReference__c, generatedInvoices[0].billToReference);
        Assert.areEqual(existingInvoice.BillToCountry__c, generatedInvoices[0].billToCountry);
        Assert.areEqual(existingInvoice.BillToAddress__c, generatedInvoices[0].billToStreet);
        Assert.areEqual(existingInvoice.BillToArea__c, generatedInvoices[0].billToState);
        Assert.areEqual(existingInvoice.BillToTown__c, generatedInvoices[0].billToCity);
        Assert.areEqual(existingInvoice.BillToPostcode__c, generatedInvoices[0].billToPostalCode);

        Assert.areEqual(existingInvoice.DpName__c, generatedInvoices[0].shipToName);
        Assert.areEqual(existingInvoice.DpReference__c, generatedInvoices[0].shipToReference);
        Assert.areEqual(existingInvoice.DpCountry__c, generatedInvoices[0].shipToCountry);
        Assert.areEqual(existingInvoice.DpAddress__c, generatedInvoices[0].shipToStreet);
        Assert.areEqual(existingInvoice.DpArea__c, generatedInvoices[0].shipToState);
        Assert.areEqual(existingInvoice.DpTown__c, generatedInvoices[0].shipToCity);
        Assert.areEqual(existingInvoice.DpPostcode__c, generatedInvoices[0].shipToPostalCode);

        Assert.areEqual(existingInvoice.aforza__Order__r.OrderNumber, generatedInvoices[0].invoiceNumber);
        Assert.areEqual(existingInvoice.CreatedDate, generatedInvoices[0].createdDate);
        Assert.areEqual(existingInvoice.aforza__Due_Date__c, generatedInvoices[0].dueDate);
        Assert.areEqual(existingInvoice.PoNumber__c, generatedInvoices[0].poNumber);
        Assert.areEqual(existingInvoice.CustomerShopNumber__c, generatedInvoices[0].customerShopNumber);
        Assert.areEqual(existingInvoice.PaymentInstruction__c, generatedInvoices[0].paymentMethod);
        Assert.areEqual(existingInvoice.PaymentTerms__c, generatedInvoices[0].paymentTerms);
        Assert.areEqual(existingInvoice.PrintName__c, generatedInvoices[0].printName);

        Assert.areEqual(existingInvoice.NetTotal__c, generatedInvoices[0].netValue);
        Assert.areEqual(existingInvoice.Vat__c, generatedInvoices[0].vatValue);
        Assert.areEqual(existingInvoice.DiscountTotal__c, generatedInvoices[0].discountTotal);
        Assert.areEqual(existingInvoice.Gross__c, generatedInvoices[0].total);
    }
}