src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/NextDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>NextDeliveryDate__c</fullName>
    <formula>IF(
    NextDeliveryDateHidden__c &gt;= TODAY(),
    NextDeliveryDateHidden__c,
    IF(
        OR(ISPICKVAL(Depot__c, &quot;C&quot;), ISPICKVAL(Depot__c,&quot;Z&quot;), ISPICKVAL(Depot__c, &quot;B&quot;)),
        DATEVALUE(  NextCallDate__c ) +
            CASE(
              WEEKDAY(DATEVALUE( NextCallDate__c )),
               1, 1,
               2, 1,
               3, 1,
               4, 1,
               5, 1,
               6, 3,
               7, 2,
             0),
        DATEVALUE( NextCallDate__c ) +
            CASE(
              WEEKDAY(DATEVALUE( NextCallDate__c )),
               1, 2,
               2, 2,
               3, 2,
               4, 2,
               5, 4,
               6, 4,
               7, 3,
             0)
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Delivery Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>PrimaryStartDate__c</fullName>
    <label>Primary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/classes/AccountNextDeliveryDateUpdateBatchTest.cls
/**
 * Created by magdalena.stanciu on 04.01.2023.
 */
@IsTest
private with sharing class AccountNextDeliveryDateUpdateBatchTest {
    @IsTest
    private static void testBatchExecution_ExistingTradersAccounts() {
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders',
                PrimaryGridNumber__c = '3C7201MO1', PrimaryStartDate__c = Date.newInstance(2022, 1, 1),
                NextDeliveryDate__c = null)
        );

        Test.startTest();
        Database.executeBatch(new AccountNextDeliveryDateUpdateBatch());
        Test.stopTest();

        Account updatedAccount = [
            SELECT Id, NextDeliveryDate__c
            FROM Account
            WHERE Id = :dpAccount.Id
        ];

        Assert.isNotNull(updatedAccount.NextDeliveryDate__c);
    }

    @IsTest
    private static void testBatchExecution_NoExistingTradersAccounts() {
        TdfSObjectFactory.insertSObject(new aforza__Attribute__c(aforza__Code__c = 'New DP'));

        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Prospect',
                PrimaryGridNumber__c = '3C7201MO1', PrimaryStartDate__c = Date.newInstance(2022, 1, 1),
                NextDeliveryDate__c = null)
        );

        Test.startTest();
        Database.executeBatch(new AccountNextDeliveryDateUpdateBatch());
        Test.stopTest();

        Account updatedAccount = [
            SELECT Id, NextDeliveryDate__c
            FROM Account
            WHERE Id = :dpAccount.Id
        ];

        Assert.isNull(updatedAccount.NextDeliveryDate__c);
    }
}