src/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Prospect</fullName>
            </value>
            <value>
                <fullName>Traders</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Request to close</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/classes/EmailServiceTest.cls
/**
 * Created by magdalena.stanciu on 11.10.2022.
 */

@IsTest
private with sharing class EmailServiceTest {

    @IsTest
    private static void testBuildEmailMessage() {
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(
                new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, AccountStatus__c = 'Traders')
        );
        Contact newContact = (Contact) TdfSObjectFactory.insertSObject(new Contact(AccountId = dpAccount.Id, LastName = 'Test'));
        aforza__Invoice__c newInvoice = (aforza__Invoice__c) TdfSObjectFactory.insertSObject(
                new aforza__Invoice__c(aforza__Account__c = dpAccount.Id)
        );

        Id emailTemplateId = [SELECT Id FROM EmailTemplate LIMIT 1].Id;

        Test.startTest();
        Messaging.SingleEmailMessage message = EmailService.buildEmailMessage(
                emailTemplateId,
                false,
                false,
                newInvoice.Id,
                newContact.Id,
                new List<String>{'test@test.com'},
                new List<String>()
        );
        Test.stopTest();

        System.assertEquals(emailTemplateId, message.getTemplateId());
        System.assertEquals(false, message.treatTargetObjectAsRecipient);
        System.assertEquals(false, message.saveAsActivity);
        System.assertEquals(newInvoice.Id, message.getWhatId());
        System.assertEquals(newContact.Id, message.getTargetObjectId());
        System.assertEquals(1, message.getToAddresses().size());
        System.assertEquals(0, message.getEntityAttachments().size());
        System.assertEquals(EmailService.ORG_WIDE_EMAIL_ADDRESS_ID, message.getOrgWideEmailAddressId());
    }
}