src/main/default/objects/Account/fields/BillToReference__c.field-meta.xml
<CustomField>
    <fullName>BillToReference__c</fullName>
    <label>Bill To Reference</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Account/fields/CustomerShopNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerShopNumber__c</fullName>
    <label>Customer Shop Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPaymentMethod__c</fullName>
    <label>Primary Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Payment</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Buying Group Central Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/BillToReference__c.field-meta.xml
<CustomField>
    <fullName>BillToReference__c</fullName>
    <label>Bill To Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/CustomerShopNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerShopNumber__c</fullName>
    <label>Customer Shop Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/DiscountTotal__c.field-meta.xml
<CustomField>
    <fullName>DiscountTotal__c</fullName>
    <label>Discount Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/NetTotal__c.field-meta.xml
<CustomField>
    <fullName>NetTotal__c</fullName>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PrintName__c.field-meta.xml
<CustomField>
    <fullName>PrintName__c</fullName>
    <label>Print Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/TotalQuantity__c.field-meta.xml
<CustomField>
    <fullName>TotalQuantity__c</fullName>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/Vat__c.field-meta.xml
<CustomField>
    <fullName>Vat__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/aforza__Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>A specific charge or listing on a customer&apos;s invoice.</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/aforza__Invoice__c.field-meta.xml
<CustomField>
    <fullName>aforza__Invoice__c</fullName>
    <description>The invoice the line item is for.</description>
    <inlineHelpText>The invoice the line item is for.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Billing_Statement_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/NetPrice__c.field-meta.xml
<CustomField>
    <fullName>NetPrice__c</fullName>
    <label>Net Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/SkuCode__c.field-meta.xml
<CustomField>
    <fullName>SkuCode__c</fullName>
    <label>SKU Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/SkuName__c.field-meta.xml
<CustomField>
    <fullName>SkuName__c</fullName>
    <label>SKU Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Invoice_Line_Item__c/fields/VatRate__c.field-meta.xml
<CustomField>
    <fullName>VatRate__c</fullName>
    <label>VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/main/default/objects/Order/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <formula>Account.DeliveryPointReference__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Point Reference</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/DiscountTotal__c.field-meta.xml
<CustomField>
    <fullName>DiscountTotal__c</fullName>
    <label>Discount Total</label>
    <summarizedField>OrderItem.UnitPrice</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.aforza__Type__c</field>
        <operation>equals</operation>
        <value>Discount</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/Order/fields/NetTotal__c.field-meta.xml
<CustomField>
    <fullName>NetTotal__c</fullName>
    <formula>TotalAmount - DiscountTotal__c -  TaxTotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/Order/fields/PrimaryPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPaymentMethod__c</fullName>
    <formula>TEXT(Account.PrimaryPaymentMethod__c)</formula>
    <label>Primary Payment Method</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/PrintName__c.field-meta.xml
<CustomField>
    <fullName>PrintName__c</fullName>
    <label>Print Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/TotalQuantity__c.field-meta.xml
<CustomField>
    <fullName>TotalQuantity__c</fullName>
    <formula>aforza__Total_Products_In_Order__c -  TotalQuantityOfDRSProducts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/InvoicePDFController.cls
/**
 * @description       :
 * @author            : Ciuca Bianca BearingPoint GmbH
 * @group             :
 * @last modified on  : 10-06-2022
 * @last modified by  : Ciuca Bianca, BearingPoint GmbH
 **/
public with sharing class InvoicePDFController {
	public aforza__Invoice__c currentInvoice { get; set; }
	public Order associatedOrder { get; set; }
	public Account associatedAccount { get; set; }
	public List<aforza__Invoice_Line_Item__c> invoiceLineItems { get; set; }
	public Decimal vatRate { get; set; }
	public ContentDocumentLink signature { get; set; }

	public InvoicePDFController() {
		Id invoiceId = ApexPages.currentPage().getParameters().get('id');
		this.currentInvoice = [
			SELECT
				Name,
				CreatedDate,
				aforza__Order__c,
				aforza__Due_Date__c,
				NetTotal__c,
				TotalQuantity__c,
				Vat__c,
				Gross__c,
				(
					SELECT Name, SkuCode__c, SkuName__c, Quantity__C, UnitPrice__c, VatRate__c, Vat__c, NetPrice__c
					FROM aforza__Billing_Statement_Line_Items__r
				)
			FROM aforza__Invoice__c
			WHERE Id = :invoiceId
		];
		this.invoiceLineItems = this.currentInvoice.aforza__Billing_Statement_Line_Items__r;
		this.vatRate = this.invoiceLineItems[0].VatRate__c;
		this.associatedOrder = [
			SELECT
				Id,
				BillingStreet,
				BillingCity,
				BillingState,
				BillingPostalCode,
				BillingCountry,
				ShippingStreet,
				ShippingCity,
				ShippingState,
				ShippingPostalCode,
				ShippingCountry,
				AccountId,
				PoNumber,
				DiscountTotal__c,
				PrintName__c
			FROM Order
			WHERE Id = :this.currentInvoice.aforza__Order__c
		];
		this.associatedAccount = [
			SELECT Name, DeliveryPointReference__c, PrimaryPaymentMethod__c, BillToReference__c, CustomerShopNumber__c
			FROM Account
			WHERE Id = :this.associatedOrder.AccountId
		];

		// get signature
		List<ContentDocumentLink> signatureDocuments = new List<ContentDocumentLink>([
				SELECT Id, ContentDocumentId, ContentDocument.LatestPublishedVersionId, ContentDocument.Title
				FROM ContentDocumentLink
				WHERE LinkedEntityId = :associatedOrder.Id AND ContentDocument.Title LIKE 'Signature%'
		]);
		this.signature = signatureDocuments.isEmpty() ? null : signatureDocuments[0];
	}

	@AuraEnabled
	public static void attachPDF(Id invoiceId) {
		try {
			InvoiceService.generateInvoiceDocuments(new Set<Id>{invoiceId});
		} catch (Exception e) {
			System.debug(LoggingLevel.Error, e.getStackTraceString());
			throw new AuraHandledException(e.getMessage());
		}
	}
}