src/main/default/objects/Account/fields/BottomlineRefNumber__c.field-meta.xml
<CustomField>
    <fullName>BottomlineRefNumber__c</fullName>
    <externalId>true</externalId>
    <label>Bottomline Ref. Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/UrlMapping__mdt/UrlMapping__mdt.object-meta.xml
<CustomObject>
    <description>Link for Direct Debit Mandate Url</description>
    <label>UrlMapping</label>
    <pluralLabel>UrlMappings</pluralLabel>
</CustomObject>

src/main/default/classes/DdMandateLinkController.cls
public with sharing class DdMandateLinkController {
    /*@AuraEnabled
    public static String populateDDUrlBasedOnMappings(String accountId) { 
        Account thisAccount = [SELECT Id, BillingPostalCode, BillingStreet, BillingCity, DeliveryPointReference__c,
                              aforza__Primary_Contact__c, aforza__Primary_Contact__r.FirstName,aforza__Primary_Contact__r.Email,
                              aforza__Primary_Contact__r.LastName, BottomlineRefNumber__c FROM Account WHERE Id =:accountId limit 1];
            
        UrlMapping__mdt agentUrlMapping = AccountService.AGENT_MANDATE_URL_MAPPING;
        UrlMapping__mdt customerUrlMapping = AccountService.CUSTOMER_MANDATE_URL_MAPPING;
        
        Set <String> agentUrlFields = CommonUtility.urlGetFieldsToQuery(agentUrlMapping);
        Set <String> customerUrlFields = CommonUtility.urlGetFieldsToQuery(customerUrlMapping);
        agentUrlFields.addAll(customerUrlFields);
        
        List <String> allUrlFields = new List <String> (agentUrlFields);
        Map <Id, Account> agentAccountsWithFieldData = AccountService.getAccountDetailsFromFields(allUrlFields, accountId);

        String agentMandateUrl = CommonUtility.createUrlMethod(thisAccount, agentUrlMapping);
        String customerMandateUrl = CommonUtility.createUrlMethod(thisAccount, customerUrlMapping);
                
        String returnedUrl;

        if (FeatureManagement.checkPermission('FieldSalesUser')){
           returnedUrl = customerMandateUrl;
        }
         else{
            returnedUrl = agentMandateUrl;
        }
        return returnedUrl;         
    }*/
}