src/main/default/objects/Account/fields/CallPriority__c.field-meta.xml
<CustomField>
    <fullName>CallPriority__c</fullName>
    <label>Call Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <label>Closed Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Account/fields/CreditStatus__c.field-meta.xml
<CustomField>
    <fullName>CreditStatus__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
                <default>true</default>
                <label>Good</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>On Stop</fullName>
                <isActive>false</isActive>
                <label>On Stop</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/Account/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <inlineHelpText>Which Depot Will Service This Customer?</inlineHelpText>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TBC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Account/fields/SecondaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>SecondaryGridNumber__c</fullName>
    <label>Secondary Grid Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>Store Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/TradingFrequencyBucketed__c.field-meta.xml
<CustomField>
    <fullName>TradingFrequencyBucketed__c</fullName>
    <description>Used for filtering based on buckets. Created field so that we can use dynamic filtering component.</description>
    <formula>CASE(
    TradingFrequency__c,
				0, &apos;0-4&apos;,
				1, &apos;0-4&apos;,
				2, &apos;0-4&apos;,
				3, &apos;0-4&apos;,
				4, &apos;0-4&apos;,
				5, &apos;5-9&apos;,
				6, &apos;5-9&apos;,
				7, &apos;5-9&apos;,
				8, &apos;5-9&apos;,
				9, &apos;5-9&apos;,
				10, &apos;10-13&apos;,
				11, &apos;10-13&apos;,
				12, &apos;10-13&apos;,
				13, &apos;10-13&apos;,
				14, &apos;14-20&apos;,
				15, &apos;14-20&apos;,
				16, &apos;14-20&apos;,
				17, &apos;14-20&apos;,
				18, &apos;14-20&apos;,
				19, &apos;14-20&apos;,
				20, &apos;14-20&apos;,
				&apos;20+&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trading Frequency Bucketed</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/aforza__Recurring_Record__c.object-meta.xml
<CustomObject>
    <description>An object that controls when a record recurs.</description>
    <label>Recurring Record</label>
    <nameField>
        <label>Recurring Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Recurring_Record__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Account with Record Type of &quot;Outlet&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Outlet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Records</relationshipLabel>
    <relationshipName>Recurring_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Visit__c/aforza__Visit__c.object-meta.xml
<CustomObject>
    <description>A purposeful on-site meeting at an account.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>VIS-{00000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Visit__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the visit is taking place at.</description>
    <inlineHelpText>The account the visit is taking place at.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the visit.</description>
    <inlineHelpText>The current status of the visit.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Ring Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Call_Priority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <description>A call priority selection.</description>
    <masterLabel>Call Priority</masterLabel>
</GlobalValueSet>

src/main/default/classes/DynamicFilterControllerTest.cls
/**
 * Created by svatopluk.sejkora on 26.09.2022.
 */

@IsTest
private class DynamicFilterControllerTest {
    @IsTest
    private static void testPopulateOperand_Equals() {
        String operand = 'equals';

        Test.startTest();
        String returnedOperand = DynamicFilterController.populateOperand(operand);
        Test.stopTest();

        System.assertEquals(' = ', returnedOperand, 'We expect = for equals to be returned');
    }

    @IsTest
    private static void testPopulateOperand_EqualGreater() {
        String operand = 'equalGreater';

        Test.startTest();
        String returnedOperand = DynamicFilterController.populateOperand(operand);
        Test.stopTest();

        System.assertEquals(' >= ', returnedOperand, 'We expect >= for equalGreater to be returned');
    }

    @IsTest
    private static void testPopulateOperand_EqualSmaller() {
        String operand = 'equalSmaller';

        Test.startTest();
        String returnedOperand = DynamicFilterController.populateOperand(operand);
        Test.stopTest();

        System.assertEquals(' <= ', returnedOperand, 'We expect <= for equalSmaller to be returned');
    }

    @IsTest
    private static void testPopulateOperand_UnknownOperand() {
        String operand = 'aaa';

        Test.startTest();
        try {
            DynamicFilterController.populateOperand(operand);
            System.assert(false, 'An exception should have been thrown here.');
        } catch (Exception e) {
            System.assertEquals('System.IllegalArgumentException', e.getTypeName());
            System.assertEquals('An unknown operand has been submitted: aaa', e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    private static void testPopulateFilterCondition_Date() {
        DynamicFilterController.FilterValue filterValue = new DynamicFilterController.FilterValue();
        filterValue.value = JSON.serialize(System.today());
        filterValue.type = 'Date';
        filterValue.soqlName = 'aforza__Planned_Time__c';

        Test.startTest();
        String populatedValue = DynamicFilterController.populateFilterCondition(filterValue, 'aforza__Visit__c');
        Test.stopTest();

        System.assertEquals(filterValue.value + 'T00:00:00Z', populatedValue, 'We expect to get the same value as we sent in');
    }

    @IsTest
    private static void testPopulateFilterCondition_Integer() {
        DynamicFilterController.FilterValue filterValue = new DynamicFilterController.FilterValue();
        filterValue.value = String.valueOf(90);
        filterValue.type = 'Integer';

        Test.startTest();
        String populatedValue = DynamicFilterController.populateFilterCondition(filterValue, 'aforza__Visit__c');
        Test.stopTest();

        System.assertEquals(filterValue.value, populatedValue, 'We expect to get the same value as we sent in');
    }

    @IsTest
    private static void testPopulateFilterCondition_Picklist() {
        DynamicFilterController.FilterValue filterValue = new DynamicFilterController.FilterValue();
        filterValue.value = 'Picklist Value';
        filterValue.type = 'Picklist';

        Test.startTest();
        String populatedValue = DynamicFilterController.populateFilterCondition(filterValue, 'aforza__Visit__c');
        Test.stopTest();

        System.assertEquals('\'' + filterValue.value + '\'', populatedValue, 'We expect to get the value surrounded with apostrophes');
    }

    @IsTest
    private static void testPopulateOperand_UnknownDataType() {
        DynamicFilterController.FilterValue filterValue = new DynamicFilterController.FilterValue();
        filterValue.type = 'aaa';
        filterValue.value = 'Picklist Value';

        Test.startTest();
        try {
            DynamicFilterController.populateFilterCondition(filterValue, 'aforza__Visit__c');
            System.assert(false, 'An exception should have been thrown here.');
        } catch (Exception e) {
            System.assertEquals('System.IllegalArgumentException', e.getTypeName());
            System.assertEquals('An unknown data type submitted: aaa', e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    private static void testBuildQuery() {
        // prepare filter definition object
        DynamicFilterController.FilterValue filter = new DynamicFilterController.FilterValue();
        filter.value = 'P2';
        filter.type = 'Picklist';
        filter.operand = 'equals';
        filter.soqlName = 'aforza__Account__r.CallPriority__c';

        List<DynamicFilterController.FilterValue> filterFieldsList = new List<DynamicFilterController.FilterValue>();
        filterFieldsList.add(filter);

        String filterFields = JSON.serialize(filterFieldsList);

        String queryFields = 'Id, aforza__Status__c,aforza__Planned_Time__c,aforza__Account__r.Owner.LastName,aforza__Owner__r.LastName,' +
                'aforza__Account__r.StoreName__c,aforza__Account__r.BillingPostalCode,aforza__Account__r.DeliveryPointReference__c,' +
                'aforza__Account__r.PrimaryGridNumber__c,aforza__Account__r.SecondaryGridNumber__c,' +
                'toLabel(aforza__Account__r.Depot__c),aforza__Account__r.CreditStatus__c,aforza__Account__r.CallPriority__c,aforza__Account__r.TradingFrequencyBucketed__c';
        List<String> queryList = queryFields.split(',');

        Test.startTest();
        String query = DynamicFilterController.buildQuery('aforza__Visit__c', queryList, filterFields, 900);
        Test.stopTest();

        String expectedQuery = 'SELECT Id, aforza__Status__c,aforza__Planned_Time__c,aforza__Account__r.Owner.LastName,' +
                'aforza__Owner__r.LastName,aforza__Account__r.StoreName__c,aforza__Account__r.BillingPostalCode,aforza__Account__r.DeliveryPointReference__c,' +
                'aforza__Account__r.PrimaryGridNumber__c,aforza__Account__r.SecondaryGridNumber__c,toLabel(aforza__Account__r.Depot__c),' +
                'aforza__Account__r.CreditStatus__c,aforza__Account__r.CallPriority__c,aforza__Account__r.TradingFrequencyBucketed__c ' +
                'FROM aforza__Visit__c WHERE  (aforza__Account__r.CallPriority__c = \'P2\' ) LIMIT 900';
        System.assertEquals(expectedQuery, query);
    }

    @IsTest
    private static void testBuildQuery_MultipleFilters() {
        // prepare filter definition object
        List<DynamicFilterController.FilterValue> filterFieldsList = new List<DynamicFilterController.FilterValue>();
        DynamicFilterController.FilterValue filter = new DynamicFilterController.FilterValue();
        filter.value = 'P2';
        filter.type = 'Picklist';
        filter.operand = 'equals';
        filter.soqlName = 'aforza__Account__r.CallPriority__c';
        filterFieldsList.add(filter);

        DynamicFilterController.FilterValue filter2 = new DynamicFilterController.FilterValue();
        filter2.value = '14-20';
        filter2.type = 'Picklist';
        filter2.operand = 'equals';
        filter2.soqlName = 'aforza__Account__r.TradingFrequencyBucketed__c';
        filterFieldsList.add(filter2);

        String filterFields = JSON.serialize(filterFieldsList);

        String queryFields = 'Id, aforza__Status__c,aforza__Planned_Time__c,aforza__Account__r.Owner.LastName,aforza__Owner__r.LastName,' +
                'aforza__Account__r.StoreName__c,aforza__Account__r.BillingPostalCode,aforza__Account__r.DeliveryPointReference__c,' +
                'aforza__Account__r.PrimaryGridNumber__c,aforza__Account__r.SecondaryGridNumber__c,' +
                'toLabel(aforza__Account__r.Depot__c),aforza__Account__r.CreditStatus__c,aforza__Account__r.CallPriority__c,aforza__Account__r.TradingFrequencyBucketed__c';
        List<String> queryList = queryFields.split(',');

        Test.startTest();
        String query = DynamicFilterController.buildQuery('aforza__Visit__c', queryList, filterFields, 900);
        Test.stopTest();

        System.debug(query);
        String expectedQuery = 'SELECT Id, aforza__Status__c,aforza__Planned_Time__c,aforza__Account__r.Owner.LastName,' +
                'aforza__Owner__r.LastName,aforza__Account__r.StoreName__c,aforza__Account__r.BillingPostalCode,' +
                'aforza__Account__r.DeliveryPointReference__c,aforza__Account__r.PrimaryGridNumber__c,' +
                'aforza__Account__r.SecondaryGridNumber__c,toLabel(aforza__Account__r.Depot__c),' +
                'aforza__Account__r.CreditStatus__c,aforza__Account__r.CallPriority__c,aforza__Account__r.TradingFrequencyBucketed__c ' +
                'FROM aforza__Visit__c WHERE  (aforza__Account__r.CallPriority__c = \'P2\'  AND aforza__Account__r.TradingFrequencyBucketed__c = \'14-20\' ) LIMIT 900';
        System.assertEquals(expectedQuery, query);

    }

    @IsTest
    private static void testGetResult() {
        // get some visits
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        List<aforza__Recurring_Record__c> recurringRecords = [SELECT Id FROM aforza__Recurring_Record__c WHERE Account__c = :acc.Id LIMIT 1];
        System.assert(recurringRecords.size() == 1);

        TdfSObjectFactory.insertSObjects(new aforza__Visit__c(aforza__Account__c = acc.Id, aforza__Recurring_Record__c = recurringRecords[0].Id,
                RecordTypeId = RecordTypes.VISIT_REMOTE_VISIT_ID), 20);

        // prepare filter definition object
        List<DynamicFilterController.FilterValue> filterFieldsList = new List<DynamicFilterController.FilterValue>();
        DynamicFilterController.FilterValue filter = new DynamicFilterController.FilterValue();
        filter.value = 'P2';
        filter.type = 'Picklist';
        filter.operand = 'equals';
        filter.soqlName = 'aforza__Account__r.CallPriority__c';
        filterFieldsList.add(filter);

        DynamicFilterController.FilterValue filter2 = new DynamicFilterController.FilterValue();
        filter2.value = '0-4';
        filter2.type = 'Picklist';
        filter2.operand = 'equals';
        filter2.soqlName = 'aforza__Account__r.TradingFrequencyBucketed__c';
        filterFieldsList.add(filter2);

        String filterFields = JSON.serialize(filterFieldsList);

        String queryFields = 'Id, aforza__Status__c,aforza__Planned_Time__c,aforza__Account__r.Owner.LastName,aforza__Owner__r.LastName,' +
                'aforza__Account__r.StoreName__c,aforza__Account__r.BillingPostalCode,aforza__Account__r.DeliveryPointReference__c,' +
                'aforza__Account__r.PrimaryGridNumber__c,aforza__Account__r.SecondaryGridNumber__c,' +
                'toLabel(aforza__Account__r.Depot__c),aforza__Account__r.CreditStatus__c,aforza__Account__r.CallPriority__c,aforza__Account__r.TradingFrequencyBucketed__c';
        List<String> queryList = queryFields.split(',');

        Test.startTest();
        List<SObject> records = DynamicFilterController.getResults('aforza__Visit__c', queryList, filterFields, 40);
        Test.stopTest();

        System.assertEquals(20, records.size());
    }

    @IsTest
    private static void testGetResult_NoData() {
        // get some visits
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        List<aforza__Recurring_Record__c> recurringRecords = [SELECT Id FROM aforza__Recurring_Record__c WHERE Account__c = :acc.Id LIMIT 1];
        System.assert(recurringRecords.size() == 1);

        TdfSObjectFactory.insertSObjects(new aforza__Visit__c(aforza__Account__c = acc.Id, aforza__Recurring_Record__c = recurringRecords[0].Id,
                RecordTypeId = RecordTypes.VISIT_REMOTE_VISIT_ID), 20);

        // prepare filter definition object
        List<DynamicFilterController.FilterValue> filterFieldsList = new List<DynamicFilterController.FilterValue>();
        DynamicFilterController.FilterValue filter = new DynamicFilterController.FilterValue();
        filter.value = 'P3';
        filter.type = 'Picklist';
        filter.operand = 'equals';
        filter.soqlName = 'aforza__Account__r.CallPriority__c';
        filterFieldsList.add(filter);

        DynamicFilterController.FilterValue filter2 = new DynamicFilterController.FilterValue();
        filter2.value = '0-4';
        filter2.type = 'Picklist';
        filter2.operand = 'equals';
        filter2.soqlName = 'aforza__Account__r.TradingFrequencyBucketed__c';
        filterFieldsList.add(filter2);

        String filterFields = JSON.serialize(filterFieldsList);

        String queryFields = 'Id, aforza__Status__c,aforza__Planned_Time__c,aforza__Account__r.Owner.LastName,aforza__Owner__r.LastName,' +
                'aforza__Account__r.StoreName__c,aforza__Account__r.BillingPostalCode,aforza__Account__r.DeliveryPointReference__c,' +
                'aforza__Account__r.PrimaryGridNumber__c,aforza__Account__r.SecondaryGridNumber__c,' +
                'toLabel(aforza__Account__r.Depot__c),aforza__Account__r.CreditStatus__c,aforza__Account__r.CallPriority__c,aforza__Account__r.TradingFrequencyBucketed__c';
        List<String> queryList = queryFields.split(',');

        Test.startTest();
        List<SObject> records = DynamicFilterController.getResults('aforza__Visit__c', queryList, filterFields, 40);
        Test.stopTest();

        System.assertEquals(0, records.size());
    }

    @IsTest
    private static void testGetResult_Exception() {
        Test.startTest();
        try {
            DynamicFilterController.getResults(null, null, null, 40);
            System.assert(false);
        } catch (Exception e) {
            System.assertEquals('System.AuraHandledException', e.getTypeName());
            System.assertEquals('null input to JSON parser', e.getMessage());
        }
        Test.stopTest();
    }

    @IsTest
    private static void testGetFilterFieldSfDataType() {
        DynamicFilterController.FilterValue filter = new DynamicFilterController.FilterValue();
        filter.soqlName = 'aforza__Account__r.CreatedDate';

        Test.startTest();
        String fieldType = DynamicFilterController.getFilterFieldSfDataType(filter, 'aforza__Visit__c');
        Test.stopTest();

        System.assertEquals('DATETIME', fieldType);
    }

    @IsTest
    private static void testGetFilterFieldSfDataType_Date() {
        DynamicFilterController.FilterValue filter = new DynamicFilterController.FilterValue();
        filter.soqlName = 'aforza__Account__r.ClosedDate__c';

        Test.startTest();
        String fieldType = DynamicFilterController.getFilterFieldSfDataType(filter, 'aforza__Visit__c');
        Test.stopTest();

        System.assertEquals('DATE', fieldType);
    }
}