src/main/default/objects/Account/fields/CallPriority__c.field-meta.xml
<CustomField>
    <fullName>CallPriority__c</fullName>
    <label>Call Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/Account/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1 fortnightly cycle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/PreferredCallTimeTelesales__c.field-meta.xml
<CustomField>
    <fullName>PreferredCallTimeTelesales__c</fullName>
    <label>Preferred Call Time Telesales</label>
    <type>Time</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryCallDay__c.field-meta.xml
<CustomField>
    <fullName>PrimaryCallDay__c</fullName>
    <formula>CASE( LEFT(RIGHT( PrimaryGridNumber__c ,3),2), 
    &quot;MO&quot;, &quot;Monday&quot;, 
    &quot;TU&quot;, &quot;Tuesday&quot;, 
    &quot;WE&quot;, &quot;Wednesday&quot;, 
    &quot;TH&quot;, &quot;Thursday&quot;, 
    &quot;FR&quot;, &quot;Friday&quot;, 
    &quot;Error&quot;)</formula>
    <label>Primary Call Day</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>PrimaryStartDate__c</fullName>
    <label>Primary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Account/fields/SecondaryCallDay__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCallDay__c</fullName>
    <label>Secondary Call Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/SecondaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>SecondaryGridNumber__c</fullName>
    <label>Secondary Grid Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/SecondaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>SecondaryStartDate__c</fullName>
    <label>Secondary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/aforza__Recurring_Record__c.object-meta.xml
<CustomObject>
    <description>An object that controls when a record recurs.</description>
    <label>Recurring Record</label>
    <nameField>
        <label>Recurring Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Recurring_Record__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Account with Record Type of &quot;Outlet&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Outlet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Records</relationshipLabel>
    <relationshipName>Recurring_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Frequency__c.field-meta.xml
<CustomField>
    <fullName>aforza__Frequency__c</fullName>
    <description>The frequency at which this recurring record should happen.</description>
    <inlineHelpText>The frequency at which this recurring record should happen.</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Week-ly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 fortnightly cycle</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Month-ly</label>
            </value>
            <value>
                <fullName>Annually</fullName>
                <isActive>false</isActive>
                <label>Annually</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
                <isActive>false</isActive>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Last_Recurrence_Date__c.field-meta.xml
<CustomField>
    <fullName>aforza__Last_Recurrence_Date__c</fullName>
    <description>The date for the last recurring record to be scheduled on.</description>
    <inlineHelpText>The date for the last recurring record to be scheduled on.</inlineHelpText>
    <label>Last Recurrence Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Number_Of_Recurrences__c.field-meta.xml
<CustomField>
    <fullName>aforza__Number_Of_Recurrences__c</fullName>
    <description>The number of recurrences the record should recur.</description>
    <inlineHelpText>The number of recurrences the record should recur.</inlineHelpText>
    <label>Number Of Recurrences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of recurring record.</description>
    <inlineHelpText>The type of recurring record.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/CallDayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>CallDayOfWeek__c</fullName>
    <label>Call Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Date of the first visit planned for this recurrence.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/CallRecurrenceSetting__mdt/CallRecurrenceSetting__mdt.object-meta.xml
<CustomObject>
    <description>Keeps settings used for creation of visits.</description>
    <label>Call Recurrence Setting</label>
    <pluralLabel>Call Recurrence Settings</pluralLabel>
</CustomObject>

src/main/default/objects/CallRecurrenceSetting__mdt/fields/CallStatus__c.field-meta.xml
<CustomField>
    <fullName>CallStatus__c</fullName>
    <inlineHelpText>Please enter name of the status of the visit.</inlineHelpText>
    <label>Call Status</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/CallRecurrenceSetting__mdt/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <inlineHelpText>Please enter a call type that should be used for generated recurring calls.</inlineHelpText>
    <label>Call Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/globalValueSets/Call_Priority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <description>A call priority selection.</description>
    <masterLabel>Call Priority</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/WeekDays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Monday</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Tuesday</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Wednesday</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Thursday</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Friday</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Error</label>
    </customValue>
    <masterLabel>Week Days</masterLabel>
</GlobalValueSet>

src/main/default/classes/RecurringRecordService.cls
/**
 * Created by svatopluk.sejkora on 11.09.2022.
 */

public with sharing class RecurringRecordService {

    @TestVisible
    private static final CallRecurrenceSetting__mdt CALL_SETTINGS {
        get {
            if (CALL_SETTINGS == null) {
                CALL_SETTINGS = CallRecurrenceSetting__mdt.getInstance('OrgDefaultCallSettings');
            }
            return CALL_SETTINGS;
        }
        set;
    }

    public static void upsertRecurringRecords(List<AccountToTamDto> accountsToTam) {
        List<aforza__Recurring_Record__c> recurringToUpsert = new List<aforza__Recurring_Record__c>();
        for (AccountToTamDto accToTam : accountsToTam) {
            // we expect that primary is always populated
            recurringToUpsert.add(createRecurringRecord(accToTam, 'Primary'));
            if (String.isNotEmpty(accToTam.account.SecondaryGridNumber__c) && accToTam.account.SecondaryStartDate__c != null) {
                recurringToUpsert.add(createRecurringRecord(accToTam, 'Secondary'));
            }
        }
        upsert recurringToUpsert Name;
    }

    public static void deleteRecurringAndVisitRecords(Set<Id> accountIds) {
        List<aforza__Recurring_Record__c> recurringRecords = getRecurringRecordIds(accountIds);

        if (recurringRecords.size() > 0) {
            VisitCallService.deleteFutureCalls(recurringRecords, System.today());
        }

        delete recurringRecords;
    }

    public static void updateRecurringRecordsLastScheduledDate(Map<Id, Datetime> recurringRecordToLastScheduledDateMap) {
        List<aforza__Recurring_Record__c> recordsToUpdate = new List<aforza__Recurring_Record__c>();
        for (Id recurringRecordId : recurringRecordToLastScheduledDateMap.keySet()) {
            recordsToUpdate.add(new aforza__Recurring_Record__c(Id = recurringRecordId, aforza__Last_Recurrence_Date__c = recurringRecordToLastScheduledDateMap.get(recurringRecordId)));
        }

        update recordsToUpdate;
    }

    @TestVisible
    private static aforza__Recurring_Record__c createRecurringRecord(AccountToTamDto accToTam, String priority) {
        aforza__Recurring_Record__c recurring = new aforza__Recurring_Record__c();
        recurring.aforza__Type__c = CALL_SETTINGS.CallType__c;
        recurring.Account__c = accToTam.account.Id;
        recurring.OwnerId = accToTam.tamId;
        recurring.Status__c = CALL_SETTINGS.CallStatus__c;
        recurring.aforza__Frequency__c = accToTam.account.Frequency__c;
        recurring.Name = /*accToTam.account.DeliveryPointReference__c + */'_' + accToTam.account.Id + '_' + priority;
        recurring.StartDate__c = priority == 'Primary' ? accToTam.account.PrimaryStartDate__c : accToTam.account.SecondaryStartDate__c;
        recurring.CallDayOfWeek__c = priority == 'Primary' ? accToTam.account.PrimaryCallDay__c : accToTam.account.SecondaryCallDay__c;
        recurring.aforza__Last_Recurrence_Date__c = null; // setting to null to trigger recreation of visits for any update
        recurring.aforza__Number_Of_Recurrences__c = accToTam.account.Frequency__c == 'W' ? 12 : accToTam.account.Frequency__c == 'M' ? 3 : accToTam.account.Frequency__c == 'F' ? 6 : 12;
        if (accToTam.account.PreferredCallTimeTelesales__c != null) {
            recurring.Priority__c = 'Custom';
            recurring.StartTime__c = accToTam.account.PreferredCallTimeTelesales__c;
        } else {
            recurring.Priority__c = accToTam.account.CallPriority__c;
        }
        return recurring;
    }

    private static List<aforza__Recurring_Record__c> getRecurringRecordIds(Set<Id> accountIds) {
        return [SELECT Id FROM aforza__Recurring_Record__c WHERE Account__c IN :accountIds];
    }

    public class AccountToTamDto {
        public Account account;
        public Id tamId;

        public AccountToTamDto(Account account, Id tamId) {
            this.account = account;
            this.tamId = tamId;
        }
    }
}