src/main/default/objects/Account/fields/CallPriority__c.field-meta.xml
<CustomField>
    <fullName>CallPriority__c</fullName>
    <label>Call Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/Account/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1 fortnightly cycle</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/PrimaryCallDay__c.field-meta.xml
<CustomField>
    <fullName>PrimaryCallDay__c</fullName>
    <formula>CASE( LEFT(RIGHT( PrimaryGridNumber__c ,3),2), 
    &quot;MO&quot;, &quot;Monday&quot;, 
    &quot;TU&quot;, &quot;Tuesday&quot;, 
    &quot;WE&quot;, &quot;Wednesday&quot;, 
    &quot;TH&quot;, &quot;Thursday&quot;, 
    &quot;FR&quot;, &quot;Friday&quot;, 
    &quot;Error&quot;)</formula>
    <label>Primary Call Day</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Account/fields/PrimaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>PrimaryStartDate__c</fullName>
    <label>Primary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Account/fields/SecondaryCallDay__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCallDay__c</fullName>
    <label>Secondary Call Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Account/fields/SecondaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>SecondaryGridNumber__c</fullName>
    <label>Secondary Grid Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/SecondaryStartDate__c.field-meta.xml
<CustomField>
    <fullName>SecondaryStartDate__c</fullName>
    <label>Secondary Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/aforza__Recurring_Record__c.object-meta.xml
<CustomObject>
    <description>An object that controls when a record recurs.</description>
    <label>Recurring Record</label>
    <nameField>
        <label>Recurring Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Recurring_Record__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Account with Record Type of &quot;Outlet&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Outlet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Records</relationshipLabel>
    <relationshipName>Recurring_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Frequency__c.field-meta.xml
<CustomField>
    <fullName>aforza__Frequency__c</fullName>
    <description>The frequency at which this recurring record should happen.</description>
    <inlineHelpText>The frequency at which this recurring record should happen.</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Week-ly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 fortnightly cycle</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Month-ly</label>
            </value>
            <value>
                <fullName>Annually</fullName>
                <isActive>false</isActive>
                <label>Annually</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
                <isActive>false</isActive>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Last_Recurrence_Date__c.field-meta.xml
<CustomField>
    <fullName>aforza__Last_Recurrence_Date__c</fullName>
    <description>The date for the last recurring record to be scheduled on.</description>
    <inlineHelpText>The date for the last recurring record to be scheduled on.</inlineHelpText>
    <label>Last Recurrence Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Number_Of_Recurrences__c.field-meta.xml
<CustomField>
    <fullName>aforza__Number_Of_Recurrences__c</fullName>
    <description>The number of recurrences the record should recur.</description>
    <inlineHelpText>The number of recurrences the record should recur.</inlineHelpText>
    <label>Number Of Recurrences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of recurring record.</description>
    <inlineHelpText>The type of recurring record.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/CallDayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>CallDayOfWeek__c</fullName>
    <label>Call Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/DaysBetweenRecurrence__c.field-meta.xml
<CustomField>
    <fullName>DaysBetweenRecurrence__c</fullName>
    <formula>CASE(
				aforza__Frequency__c,
				&apos;W&apos;, 7, 
				&apos;F&apos;, 14,
				&apos;M&apos;, 28,
				0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Number of days calculated from frequency: W - 7, F - 14, M - 28</inlineHelpText>
    <label>Days Between Recurrence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/PlanAnotherVisit__c.field-meta.xml
<CustomField>
    <fullName>PlanAnotherVisit__c</fullName>
    <formula>IF(ISBLANK(aforza__Last_Recurrence_Date__c), TRUE, aforza__Last_Recurrence_Date__c &lt; (NOW() + (DaysBetweenRecurrence__c * aforza__Number_Of_Recurrences__c)))</formula>
    <inlineHelpText>Will be true when Last Recurrence Date plus Days Between Recurrence is smaller than actual date.</inlineHelpText>
    <label>Plan Another Visit</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Date of the first visit planned for this recurrence.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Visit__c/aforza__Visit__c.object-meta.xml
<CustomObject>
    <description>A purposeful on-site meeting at an account.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>VIS-{00000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Visit__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the visit is taking place at.</description>
    <inlineHelpText>The account the visit is taking place at.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of visit.</description>
    <inlineHelpText>The type of visit.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outlet Visit</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
            <value>
                <fullName>Video Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Call_Priority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <description>A call priority selection.</description>
    <masterLabel>Call Priority</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/WeekDays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Monday</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Tuesday</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Wednesday</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Thursday</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Friday</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Error</label>
    </customValue>
    <masterLabel>Week Days</masterLabel>
</GlobalValueSet>

src/main/default/classes/RecurringRecordServiceTest.cls
/**
 * Created by svatopluk.sejkora on 12.09.2022.
 */

@IsTest
private class RecurringRecordServiceTest {

    @IsTest
    private static void testCreateRecurringRecord() {
        TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        Account acc = [
                SELECT Id, OwnerId, Frequency__c, DeliveryPointReference__c, PrimaryStartDate__c,
                        SecondaryStartDate__c, PrimaryGridNumber__c, CallPriority__c, PrimaryCallDay__c,
                        SecondaryCallDay__c
                FROM Account
        ];

        Test.startTest();
        aforza__Recurring_Record__c recurringRecord = RecurringRecordService.createRecurringRecord(acc, 'Primary');
        insert recurringRecord;
        Test.stopTest();

        aforza__Recurring_Record__c record = [
                SELECT Id, aforza__Type__c, Account__c, OwnerId, Status__c,
                        aforza__Frequency__c, Name, StartDate__c, PlanAnotherVisit__c, DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c, CallDayOfWeek__c, Priority__c, aforza__Number_Of_Recurrences__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ][0];

        System.assertEquals(acc.OwnerId, record.OwnerId);
        System.assertEquals(RecurringRecordService.CALL_SETTINGS.CallType__c, record.aforza__Type__c);
        System.assertEquals(acc.Id, record.Account__c);
        System.assertEquals(RecurringRecordService.CALL_SETTINGS.CallStatus__c, record.Status__c);
        System.assertEquals(acc.Frequency__c, record.aforza__Frequency__c);
        System.assertEquals(true, record.Name.contains('Primary'));
        System.assertEquals(acc.PrimaryStartDate__c, record.StartDate__c);
        System.assertEquals(acc.CallPriority__c, record.Priority__c);
        System.assertEquals(acc.PrimaryCallDay__c, record.CallDayOfWeek__c);
        System.assertEquals(null, record.aforza__Last_Recurrence_Date__c);
        System.assertEquals(12, record.aforza__Number_Of_Recurrences__c, 'We expect 12 for W Frequency (part of Primary Grid)');
    }

    @IsTest
    private static void testUpsertRecurringRecords_SecondaryGrid() {
        TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, SecondaryGridNumber__c = '3C7201WEW',
                SecondaryStartDate__c = Date.parse('07/09/2022')));

        Account acc = [
                SELECT Id, OwnerId, Frequency__c, DeliveryPointReference__c, PrimaryStartDate__c,
                        SecondaryStartDate__c, PrimaryGridNumber__c, SecondaryGridNumber__c, CallPriority__c, PrimaryCallDay__c,
                        SecondaryCallDay__c
                FROM Account
        ];

        Test.startTest();
        RecurringRecordService.upsertRecurringRecords(new List<Account>{
                acc
        });
        Test.stopTest();

        List<aforza__Recurring_Record__c> records = [
                SELECT Id, aforza__Type__c, Account__c, OwnerId, Status__c,
                        aforza__Frequency__c, Name, StartDate__c, PlanAnotherVisit__c, DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c
                FROM aforza__Recurring_Record__c
        ];

        System.assertEquals(2, records.size());
    }

    @IsTest
    private static void testUpsertRecurringRecords_PrimaryGrid() {
        TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));

        Account acc = [
                SELECT Id, OwnerId, Frequency__c, DeliveryPointReference__c, PrimaryStartDate__c,
                        SecondaryStartDate__c, PrimaryGridNumber__c, SecondaryGridNumber__c, CallPriority__c, PrimaryCallDay__c,
                        SecondaryCallDay__c
                FROM Account
        ];

        Test.startTest();
        RecurringRecordService.upsertRecurringRecords(new List<Account>{
                acc
        });
        Test.stopTest();

        List<aforza__Recurring_Record__c> records = [
                SELECT Id, aforza__Type__c, Account__c, OwnerId, Status__c,
                        aforza__Frequency__c, Name, StartDate__c, PlanAnotherVisit__c, DaysBetweenRecurrence__c,
                        aforza__Last_Recurrence_Date__c
                FROM aforza__Recurring_Record__c
        ];

        System.assertEquals(1, records.size());
    }

    @IsTest
    private static void testCreateRecurringRecord_Upsert() {
        TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        Account acc = [
                SELECT Id, OwnerId, Frequency__c, DeliveryPointReference__c, PrimaryStartDate__c,
                        SecondaryStartDate__c, PrimaryGridNumber__c, CallPriority__c, PrimaryCallDay__c,
                        SecondaryCallDay__c
                FROM Account
        ];

        TdfSObjectFactory.insertSObject(new aforza__Recurring_Record__c(Account__c = acc.Id, aforza__Last_Recurrence_Date__c = System.today(), Name = '100001_' + acc.Id + '_Primary'));

        Test.startTest();
        acc.PrimaryGridNumber__c = '3C7201WEM';
        update acc;
        Test.stopTest();

        aforza__Recurring_Record__c record = [
                SELECT Id, aforza__Last_Recurrence_Date__c
                FROM aforza__Recurring_Record__c
                LIMIT 1
        ][0];

        System.assertEquals(null, record.aforza__Last_Recurrence_Date__c);
    }

    @IsTest
    private static void testUpdateRecurringRecordsLastScheduledDate() {
        aforza__Recurring_Record__c recurringRecord = (aforza__Recurring_Record__c) TdfSObjectFactory.insertSObject(new aforza__Recurring_Record__c());

        Datetime newDate = System.now();

        Test.startTest();
        RecurringRecordService.updateRecurringRecordsLastScheduledDate(new Map<Id, Datetime>{
                recurringRecord.Id => newDate
        });
        Test.stopTest();

        aforza__Recurring_Record__c record = [
                SELECT Id, aforza__Last_Recurrence_Date__c
                FROM aforza__Recurring_Record__c
                WHERE Id = :recurringRecord.Id
                LIMIT 1
        ][0];

        System.assertEquals(newDate, record.aforza__Last_Recurrence_Date__c);
    }

    @IsTest
    private static void testDeleteRecurringAndVisitRecords() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        aforza__Recurring_Record__c recurringRecord = (aforza__Recurring_Record__c) TdfSObjectFactory.insertSObject(new aforza__Recurring_Record__c(Account__c = acc.Id));

        TdfSObjectFactory.insertSObjects(
                new aforza__Visit__c(aforza__Account__c = acc.Id, aforza__Recurring_Record__c = recurringRecord.Id,
                        RecordTypeId = RecordTypes.VISIT_REMOTE_VISIT_ID), 10);

        Test.startTest();
        RecurringRecordService.deleteRecurringAndVisitRecords(new Set<Id>{
                acc.Id
        });
        Test.stopTest();

        List<aforza__Visit__c> deletedVisits = [SELECT Id FROM aforza__Visit__c];
        System.assertEquals(0, deletedVisits.size());
    }
}