src/main/default/objects/Account/fields/CreditStatus__c.field-meta.xml
<CustomField>
    <fullName>CreditStatus__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
                <default>true</default>
                <label>Good</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>On Stop</fullName>
                <isActive>false</isActive>
                <label>On Stop</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/aforza__Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>A monetary transaction against a specific account.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PTR-{00000000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the payment transaction has been enacted against.</description>
    <inlineHelpText>The account the payment transaction has been enacted against.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the transaction.</description>
    <inlineHelpText>The current status of the transaction.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Authorization</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/PaymentTransactionTriggerHandler.cls
/**
 * Created by eddy.ferreira on 13.09.2022.
 */

public with sharing class PaymentTransactionTriggerHandler {
      
    public static void setParentOrderAndAccountStatusesOnPaymentTransactionCreationOrUpdate (List<aforza__Payment_Transaction__c> newPayments, Map<Id,aforza__Payment_Transaction__c> oldPayments){
        Set<Id> relatedOrderIds = new Set<Id>();
		Set<Id> relatedAccountIds = new Set<Id>();
        
        for (aforza__Payment_Transaction__c payment : newPayments) {
            relatedOrderIds.add(payment.OrderNumber__c);
            relatedAccountIds.add(payment.aforza__Account__c);
        }
        
        Map<Id, Order> parentOrders = new Map<Id, Order>([SELECT Id, Status FROM Order WHERE Id IN :relatedOrderIds]);
		Map<Id, Account> parentAccounts = new Map<Id, Account>([SELECT Id, CreditStatus__c FROM Account WHERE Id IN :relatedAccountIds]);
        
        for (aforza__Payment_Transaction__c payment: newPayments){
            aforza__Payment_Transaction__c oldPayment = oldPayments?.get(payment.Id);
            Order parentOrder = parentOrders.get(payment.OrderNumber__c);
            Account parentAccount = parentAccounts.get(payment.aforza__Account__c);
            if(	
                (oldPayment == null && payment.aforza__Status__c == 'Pre-Authorization' && 
                parentOrder.Status != 'Activated' && 
                parentAccount.CreditStatus__c != 'Good') ||
                (oldPayment != null && payment.aforza__Status__c != oldPayment.aforza__Status__c && 
                payment.aforza__Status__c == 'Pre-Authorization' && 
                parentOrder.Status != 'Activated' && 
                parentAccount.CreditStatus__c != 'Good')
                ){
                    parentOrder.Status = 'Activated';
                    parentAccount.CreditStatus__c = 'Good';
            }   
        }
        
		if (!parentAccounts.isEmpty()) {
            update parentAccounts.values();
        }
        if (!parentOrders.isEmpty()) {
            update parentOrders.values();
        }    
    }
}