src/main/default/objects/Account/fields/CreditStatus__c.field-meta.xml
<CustomField>
    <fullName>CreditStatus__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
                <default>true</default>
                <label>Good</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>On Stop</fullName>
                <isActive>false</isActive>
                <label>On Stop</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/aforza__Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>A monetary transaction against a specific account.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PTR-{00000000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the payment transaction has been enacted against.</description>
    <inlineHelpText>The account the payment transaction has been enacted against.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the transaction.</description>
    <inlineHelpText>The current status of the transaction.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Authorization</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/PaymentTransactionTriggerHandlerTest.cls
/**
 * Created by eddy.ferreira on 06.10.2022.
 */
@isTest
private with sharing class PaymentTransactionTriggerHandlerTest {
    @isTest
    private static void testUpdateParentOrderAndAccountCreditStatuses_onCreation(){
        Account parentAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                CreditStatus__c = 'On Hold'
            )
        );
        Order parentOrder = (Order) TdfSObjectFactory.insertSObject(
            new Order(
                AccountId = parentAccount.Id,
                RecordTypeId = RecordTypes.ORDER_TELESALES_ID,
                Status = 'Draft'
            )
        );
        Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(new Product2(Name = 'Test Product'));
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
                new OrderItem(OrderId = parentOrder.Id, Product2Id = newProduct.Id)
        );

        Test.startTest();
			aforza__Payment_Transaction__c newPaymentTransaction = new aforza__Payment_Transaction__c(aforza__account__c = parentAccount.Id, aforza__amount__c = 100, aforza__Status__c = 'Pre-Authorization', OrderNumber__c=parentOrder.Id);
       		insert newPaymentTransaction;
        Test.stopTest();
        Order updatedParentOrder = [
            SELECT Id, Status
            FROM Order
            WHERE Id = :parentOrder.Id
        ];
        
        Account updatedParentAccount = [
            SELECT Id, CreditStatus__c
            FROM Account
            WHERE Id = :parentAccount.Id
        ];
   
        System.assertEquals('Activated', updatedParentOrder.Status, 'Expecting a different order status.');
        System.assertEquals('Good', updatedParentAccount.CreditStatus__c, 'Expecting a different account credit status.');
    }
	@isTest
    private static void testUpdateParentOrderAndAccountCreditStatuses_onUpdate(){
        Account parentAccount = (Account) TdfSObjectFactory.insertSObject(
            new Account(
                RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
                CreditStatus__c = 'On Hold'
            )
        );
        Order parentOrder = (Order) TdfSObjectFactory.insertSObject(
            new Order(
                AccountId = parentAccount.Id,
                RecordTypeId = RecordTypes.ORDER_TELESALES_ID,
                Status = 'Draft'
            )
        );
        Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(new Product2(Name = 'Test Product'));
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
                new OrderItem(OrderId = parentOrder.Id, Product2Id = newProduct.Id)
        );

        aforza__Payment_Transaction__c newPaymentTransaction = new aforza__Payment_Transaction__c(aforza__account__c = parentAccount.Id, aforza__amount__c = 100, aforza__Status__c = 'Applied', OrderNumber__c=parentOrder.Id);
        insert newPaymentTransaction;
        
        Test.startTest();
        newPaymentTransaction.aforza__Status__c = 'Pre-Authorization';
        update newPaymentTransaction;
        Test.stopTest();
        
        Order updatedParentOrder = [
            SELECT Id, Status
            FROM Order
            WHERE Id = :parentOrder.Id
        ];
        
        Account updatedParentAccount = [
            SELECT Id, CreditStatus__c
            FROM Account
            WHERE Id = :parentAccount.Id
        ];

        System.assertEquals('Activated', updatedParentOrder.Status, 'Expecting a different order status.');
        System.assertEquals('Good', updatedParentAccount.CreditStatus__c, 'Expecting a different account credit status.');
    }
}