src/main/default/objects/Account/fields/CustomerShopNumber__c.field-meta.xml
<CustomField>
    <fullName>CustomerShopNumber__c</fullName>
    <label>Customer Shop Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/Account/fields/FixedDeliveryInstructions__c.field-meta.xml
<CustomField>
    <fullName>FixedDeliveryInstructions__c</fullName>
    <label>Fixed Delivery Instructions</label>
    <type>TextArea</type>
</CustomField>

src/main/default/objects/Order/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <description>Used for email templates.</description>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Order/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <formula>Account.DeliveryPointReference__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery Point Reference</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/OrderInstructions__c.field-meta.xml
<CustomField>
    <fullName>OrderInstructions__c</fullName>
    <label>Order Instructions</label>
    <type>TextArea</type>
</CustomField>

src/main/default/objects/Order/fields/PrintName__c.field-meta.xml
<CustomField>
    <fullName>PrintName__c</fullName>
    <label>Print Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of product.</description>
    <inlineHelpText>The type of product.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Still</fullName>
            </value>
            <value>
                <fullName>Sparkling</fullName>
            </value>
            <value>
                <fullName>Baby</fullName>
                <isActive>false</isActive>
                <label>Baby</label>
            </value>
            <value>
                <fullName>Beer, Wine &amp; Spirits</fullName>
                <isActive>false</isActive>
                <label>Beer, Wine &amp; Spirits</label>
            </value>
            <value>
                <fullName>Bins &amp; Fridges</fullName>
                <isActive>false</isActive>
                <label>Bins &amp; Fridges</label>
            </value>
            <value>
                <fullName>Bread &amp; Bakery</fullName>
                <isActive>false</isActive>
                <label>Bread &amp; Bakery</label>
            </value>
            <value>
                <fullName>Breakfast &amp; Cereal</fullName>
                <isActive>false</isActive>
                <label>Breakfast &amp; Cereal</label>
            </value>
            <value>
                <fullName>Brochures &amp; Handouts</fullName>
                <isActive>false</isActive>
                <label>Brochures &amp; Handouts</label>
            </value>
            <value>
                <fullName>Canned Goods &amp; Soups</fullName>
                <isActive>false</isActive>
                <label>Canned Goods &amp; Soups</label>
            </value>
            <value>
                <fullName>Cleaning Supplies</fullName>
                <isActive>false</isActive>
                <label>Cleaning Supplies</label>
            </value>
            <value>
                <fullName>Condiments/Spices &amp; Bake</fullName>
                <isActive>false</isActive>
                <label>Condiments/Spices &amp; Bake</label>
            </value>
            <value>
                <fullName>Cookies, Snacks &amp; Candy</fullName>
                <isActive>false</isActive>
                <label>Cookies, Snacks &amp; Candy</label>
            </value>
            <value>
                <fullName>Dairy, Eggs &amp; Cheese</fullName>
                <isActive>false</isActive>
                <label>Dairy, Eggs &amp; Cheese</label>
            </value>
            <value>
                <fullName>Deli &amp; Signature Cafe</fullName>
                <isActive>false</isActive>
                <label>Deli &amp; Signature Cafe</label>
            </value>
            <value>
                <fullName>Fixtures</fullName>
                <isActive>false</isActive>
                <label>Fixtures</label>
            </value>
            <value>
                <fullName>Flowers</fullName>
                <isActive>false</isActive>
                <label>Flowers</label>
            </value>
            <value>
                <fullName>Frozen Foods</fullName>
                <isActive>false</isActive>
                <label>Frozen Foods</label>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
                <isActive>false</isActive>
                <label>Fruits &amp; Vegetables</label>
            </value>
            <value>
                <fullName>Gondolas</fullName>
                <isActive>false</isActive>
                <label>Gondolas</label>
            </value>
            <value>
                <fullName>Grains, Pasta &amp; Sides</fullName>
                <isActive>false</isActive>
                <label>Grains, Pasta &amp; Sides</label>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
                <isActive>false</isActive>
                <label>Health &amp; Beauty</label>
            </value>
            <value>
                <fullName>International Cuisine</fullName>
                <isActive>false</isActive>
                <label>International Cuisine</label>
            </value>
            <value>
                <fullName>Meat &amp; Seafood</fullName>
                <isActive>false</isActive>
                <label>Meat &amp; Seafood</label>
            </value>
            <value>
                <fullName>Paper Products</fullName>
                <isActive>false</isActive>
                <label>Paper Products</label>
            </value>
            <value>
                <fullName>Personal Care &amp; Pharmacy</fullName>
                <isActive>false</isActive>
                <label>Personal Care &amp; Pharmacy</label>
            </value>
            <value>
                <fullName>Pet Care</fullName>
                <isActive>false</isActive>
                <label>Pet Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/DeliveryNotePDFController.cls
public without sharing class DeliveryNotePDFController {
    public Order associatedOrder { get; set; }
    public Account associatedAccount { get; set; }
    public List<OrderItem> orderLineItems { get; set; }
    public ContentDocumentLink signature { get; set; }

    public String strOrderIdsContainsOrdItem { get; set; }
    public String strOrderIdsContainsSig { get; set; }

    public Map<Id, Order> mapIdOrder { get; set; }
    public Map<Id, Account> mapOrderIdAccount { get; set; }
    public Map<Id, List<OrderItem>> mapOrderIdlstOrderItem { get; set; }
    public Map<Id, ContentDocumentLink> mapOrderIdContentDoc { get; set; }

    public DeliveryNotePDFController() {
        String orderID = ApexPages.currentPage().getParameters().get('p');
        this.mapIdOrder = new Map<Id, Order>();
        this.mapOrderIdAccount = new Map<Id, Account>();
        this.mapOrderIdlstOrderItem = new Map<Id, List<OrderItem>>();
        this.mapOrderIdContentDoc = new Map<Id, ContentDocumentLink>();
        Set<Id> accountIds = new Set<Id>();
        List<String> lstOrders = orderID.split(',');
        for (Order ord : [
            SELECT
                Id,
                OrderNumber,
                OrderReferenceNumber,
                AccountName__c,
                DeliveryPointReference__c,
                OrderInstructions__c,
                ShippingStreet,
                ShippingCity,
                ShippingState,
                ShippingPostalCode,
                ShippingCountry,
                PrintName__c,
                PoNumber,
                AccountId,
                DeliveryDate__c
            FROM Order
            WHERE Id IN :lstOrders
        ]) {
            mapIdOrder.put(ord.Id, ord);
            accountIds.add(ord.AccountId);
        }

        for (Account acc : [
            SELECT Name, CustomerShopNumber__c, FixedDeliveryInstructions__c, Phone
            FROM Account
            WHERE Id IN :accountIds
        ]) {
            mapOrderIdAccount.put(acc.Id, acc);
        }

        for (OrderItem ordItem : [
            SELECT Id, Product2Id, Product2.StockKeepingUnit, Product2.Name, Quantity, OrderId
            FROM OrderItem
            WHERE OrderId IN :mapIdOrder.keySet() AND aforza__Type__c NOT IN ('Tax', 'Discount', 'Promotion')
        ]) {
            strOrderIdsContainsOrdItem = strOrderIdsContainsOrdItem + ';' + ordItem.OrderId;
            if (mapOrderIdlstOrderItem.containsKey(ordItem.OrderId)) {
                List<OrderItem> lstOrderItem = mapOrderIdlstOrderItem.get(ordItem.OrderId);
                lstOrderItem.add(ordItem);
                mapOrderIdlstOrderItem.put(ordItem.OrderId, lstOrderItem);
            } else {
                mapOrderIdlstOrderItem.put(ordItem.OrderId, new List<OrderItem>{
                    ordItem
                });
            }
        }

        for (ContentDocumentLink contentDocLink : [
            SELECT
                Id,
                ContentDocumentId,
                LinkedEntityId,
                ContentDocument.LatestPublishedVersionId,
                ContentDocument.LatestPublishedVersion.Title
            FROM ContentDocumentLink
            WHERE LinkedEntityId IN :mapIdOrder.keySet() AND ContentDocument.Title LIKE 'Signature%'
        ]) {
            mapOrderIdContentDoc.put(contentDocLink.LinkedEntityId, contentDocLink);
            strOrderIdsContainsSig = strOrderIdsContainsSig + ';' + contentDocLink.LinkedEntityId;
        }
    }
}