src/main/default/objects/Account/fields/DdActive__c.field-meta.xml
<CustomField>
    <fullName>DdActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DD Active?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Account/fields/DeliveryPointReference__c.field-meta.xml
<CustomField>
    <fullName>DeliveryPointReference__c</fullName>
    <displayFormat>DP-{00000}</displayFormat>
    <label>Delivery Point Reference</label>
    <type>AutoNumber</type>
</CustomField>

src/main/default/objects/Account/fields/DirectDebitMandateRef__c.field-meta.xml
<CustomField>
    <fullName>DirectDebitMandateRef__c</fullName>
    <label>Direct Debit Mandate Ref.</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/DdMandateCreationController.cls
public without sharing class DdMandateCreationController {

    public static void updateMandateOnAccount(){       
        Map <string, string> callBackParameters = apexpages.currentPage().getParameters();
        ddMandateCreationHandler(callBackParameters.get('DdPlanReference'), callBackParameters.get('Stage'));
    }
    
    @TestVisible
    private static void ddMandateCreationHandler(String ddPlan, String stage) {
        Account currentAccount;
        Account[] currentAccounts = [SELECT Id, DeliveryPointReference__c, DirectDebitMandateRef__c FROM Account WHERE DeliveryPointReference__c =: ddPlan limit 1];
        
        if (currentAccounts.size() > 0) {
            currentAccount = currentAccounts[0];
        }

        if (Integer.valueOf(stage) >5){
            if(String.isBlank(currentAccount.DirectDebitMandateRef__c)){
                currentAccount.DirectDebitMandateRef__c = ddPlan;
                currentAccount.DdActive__c = TRUE;
            }
           
        update currentAccount;
        }
    }
}