src/main/default/objects/Account/fields/InvoiceType__c.field-meta.xml
<CustomField>
    <fullName>InvoiceType__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>EDI</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>In-Store</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/InvoiceType__c.field-meta.xml
<CustomField>
    <fullName>InvoiceType__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InvoiceType</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/InvoiceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <masterLabel>Invoice Type</masterLabel>
</GlobalValueSet>

src/main/default/classes/TdfAforzaInvoiceTemplate.cls
/**
 * Class provides functionality for creating default Invoice in test methods.
 *
 * Do not use this class directly.
 * Class is initialized in TDF_SObjectTemplateFactory and all its functionality is used through TDF_SObjectFactory.
 *
 * @see TdfSObjectFactory
 * @see TdfSObjectTemplate
 * @see TdfSObjectTemplateFactory
 * @author  Magdalena Stanciu
 * @date    2022-10-03
 *
 */
@IsTest
public class TdfAforzaInvoiceTemplate extends TdfSObjectTemplate {
    private Id accountId;
    /**
     * Instance is created dynamically. This method compensates a constructor.
     *
     * @author  Magdalena Stanciu
     * @date    2022-10-03
     *
     */
    public override void init() {
        aforza__Invoice__c userDefinedInvoice = (aforza__Invoice__c) userDefinedSObject;
        if (userDefinedInvoice.aforza__Account__c == null) {
            accountId = TdfSObjectFactory.insertSObject(new Account(
                    RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID
            )).Id;
        }
    }

    /**
     * Creates a template SObject. Every call returns a new instance.
     *
     * Because this method can be called multiple times, all operations as DML or SOQL has to be done in init().
     *
     * @return Invoice template with default values
     *
     * @author  Magdalena Stanciu
     * @date    2022-10-03
     *
     */
    protected override SObject createTemplateSObject() {
        aforza__Invoice__c template = new aforza__Invoice__c();
        template.aforza__Account__c = accountId;
        template.InvoiceType__c = 'Invoice';
        template.aforza__Reference__c = 'Test';
        return template;
    }
}