src/main/default/objects/Account/fields/PerfectStoreScoreEligible__c.field-meta.xml
<CustomField>
    <fullName>PerfectStoreScoreEligible__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please set this to true if you want to start Perfect Store Score for this customer.</inlineHelpText>
    <label>Perfect Store Score Eligible</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Audit__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type or purpose of the audit.</description>
    <inlineHelpText>The type or purpose of the audit.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stock Check</fullName>
            </value>
            <value>
                <fullName>Merchandise Review</fullName>
            </value>
            <value>
                <fullName>Promotion Compliance</fullName>
            </value>
            <value>
                <fullName>Perfect Store Core and Energy</fullName>
            </value>
            <value>
                <fullName>Perfect Store Visibility and Display</fullName>
            </value>
            <value>
                <fullName>Call Productivity</fullName>
            </value>
            <value>
                <fullName>Marketing Audit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectScoreProduct__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perfect Score Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectScoreRate__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreRate__c</fullName>
    <label>Perfect Score Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectScoreWeight__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreWeight__c</fullName>
    <label>Perfect Score Weight</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectStoreMet__c.field-meta.xml
<CustomField>
    <fullName>PerfectStoreMet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the perfect store condition is met</description>
    <inlineHelpText>Indicates if the perfect store condition is met</inlineHelpText>
    <label>Perfect Store Met?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <formula>aforza__Outlet_Asset__r.PsProductEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PsRateEngland__c.field-meta.xml
<CustomField>
    <fullName>PsRateEngland__c</fullName>
    <formula>aforza__Outlet_Asset__r.PsRateEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Rate England</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PsWeightEngland__c.field-meta.xml
<CustomField>
    <fullName>PsWeightEngland__c</fullName>
    <formula>aforza__Outlet_Asset__r.PsWeightEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Weight England</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of outlet asset.</description>
    <inlineHelpText>The type of outlet asset.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Competitor Product</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectScoreProduct__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreProduct__c</fullName>
    <formula>IF(aforza__Account__r.ShippingState = &quot;England&quot;, aforza__Product__r.PsProductEngland__c, IF(aforza__Account__r.ShippingState = &quot;Scotland&quot;, aforza__Product__r.PsProductScotland__c, false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Perfect Score Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectScoreWeight__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreWeight__c</fullName>
    <formula>IF(aforza__Account__r.ShippingState = &quot;England&quot;, aforza__Product__r.PsWeightEngland__c, IF(aforza__Account__r.ShippingState = &quot;Scotland&quot;, aforza__Product__r.PsWeightScotland__c, 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Perfect Score Weight</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectStoreMet__c.field-meta.xml
<CustomField>
    <fullName>PerfectStoreMet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the perfect store condition is met</description>
    <inlineHelpText>Indicates if the perfect store condition is met</inlineHelpText>
    <label>Perfect Store Met?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <formula>aforza__Product__r.PsProductEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsRateEngland__c.field-meta.xml
<CustomField>
    <fullName>PsRateEngland__c</fullName>
    <formula>aforza__Product__r.PsRateEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Rate England</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsWeightEngland__c.field-meta.xml
<CustomField>
    <fullName>PsWeightEngland__c</fullName>
    <formula>aforza__Product__r.PsWeightEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Weight England</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Product2/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of product.</description>
    <inlineHelpText>The type of product.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Still</fullName>
            </value>
            <value>
                <fullName>Sparkling</fullName>
            </value>
            <value>
                <fullName>Baby</fullName>
                <isActive>false</isActive>
                <label>Baby</label>
            </value>
            <value>
                <fullName>Beer, Wine &amp; Spirits</fullName>
                <isActive>false</isActive>
                <label>Beer, Wine &amp; Spirits</label>
            </value>
            <value>
                <fullName>Bins &amp; Fridges</fullName>
                <isActive>false</isActive>
                <label>Bins &amp; Fridges</label>
            </value>
            <value>
                <fullName>Bread &amp; Bakery</fullName>
                <isActive>false</isActive>
                <label>Bread &amp; Bakery</label>
            </value>
            <value>
                <fullName>Breakfast &amp; Cereal</fullName>
                <isActive>false</isActive>
                <label>Breakfast &amp; Cereal</label>
            </value>
            <value>
                <fullName>Brochures &amp; Handouts</fullName>
                <isActive>false</isActive>
                <label>Brochures &amp; Handouts</label>
            </value>
            <value>
                <fullName>Canned Goods &amp; Soups</fullName>
                <isActive>false</isActive>
                <label>Canned Goods &amp; Soups</label>
            </value>
            <value>
                <fullName>Cleaning Supplies</fullName>
                <isActive>false</isActive>
                <label>Cleaning Supplies</label>
            </value>
            <value>
                <fullName>Condiments/Spices &amp; Bake</fullName>
                <isActive>false</isActive>
                <label>Condiments/Spices &amp; Bake</label>
            </value>
            <value>
                <fullName>Cookies, Snacks &amp; Candy</fullName>
                <isActive>false</isActive>
                <label>Cookies, Snacks &amp; Candy</label>
            </value>
            <value>
                <fullName>Dairy, Eggs &amp; Cheese</fullName>
                <isActive>false</isActive>
                <label>Dairy, Eggs &amp; Cheese</label>
            </value>
            <value>
                <fullName>Deli &amp; Signature Cafe</fullName>
                <isActive>false</isActive>
                <label>Deli &amp; Signature Cafe</label>
            </value>
            <value>
                <fullName>Fixtures</fullName>
                <isActive>false</isActive>
                <label>Fixtures</label>
            </value>
            <value>
                <fullName>Flowers</fullName>
                <isActive>false</isActive>
                <label>Flowers</label>
            </value>
            <value>
                <fullName>Frozen Foods</fullName>
                <isActive>false</isActive>
                <label>Frozen Foods</label>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
                <isActive>false</isActive>
                <label>Fruits &amp; Vegetables</label>
            </value>
            <value>
                <fullName>Gondolas</fullName>
                <isActive>false</isActive>
                <label>Gondolas</label>
            </value>
            <value>
                <fullName>Grains, Pasta &amp; Sides</fullName>
                <isActive>false</isActive>
                <label>Grains, Pasta &amp; Sides</label>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
                <isActive>false</isActive>
                <label>Health &amp; Beauty</label>
            </value>
            <value>
                <fullName>International Cuisine</fullName>
                <isActive>false</isActive>
                <label>International Cuisine</label>
            </value>
            <value>
                <fullName>Meat &amp; Seafood</fullName>
                <isActive>false</isActive>
                <label>Meat &amp; Seafood</label>
            </value>
            <value>
                <fullName>Paper Products</fullName>
                <isActive>false</isActive>
                <label>Paper Products</label>
            </value>
            <value>
                <fullName>Personal Care &amp; Pharmacy</fullName>
                <isActive>false</isActive>
                <label>Personal Care &amp; Pharmacy</label>
            </value>
            <value>
                <fullName>Pet Care</fullName>
                <isActive>false</isActive>
                <label>Pet Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify a PS product, and used in the Audit filter on mobile</description>
    <inlineHelpText>Used to identify a PS product, and used in the Audit filter on mobile</inlineHelpText>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/PsRateEngland__c.field-meta.xml
<CustomField>
    <fullName>PsRateEngland__c</fullName>
    <description>PS Rate England used as a multiplier for Calculating Perfect Store</description>
    <inlineHelpText>PS Rate England used as a multiplier for Calculating Perfect Store</inlineHelpText>
    <label>PS Rate England</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Product2/fields/PsWeightEngland__c.field-meta.xml
<CustomField>
    <fullName>PsWeightEngland__c</fullName>
    <description>PS Weightage England used as a multiplier for Calculating Perfect Store</description>
    <inlineHelpText>PS Weightage England used as a multiplier for Calculating Perfect Store</inlineHelpText>
    <label>PS Weight England</label>
    <precision>9</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/AuditAssetTriggerHandlerTest.cls
/**
 * Created by svatopluk.sejkora on 03.11.2022.
 */

@IsTest
private class AuditAssetTriggerHandlerTest {
    @IsTest
    static void testPopulatePerfectScoreAttributes() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, PerfectStoreScoreEligible__c = true));
        Product2 prod = (Product2) TdfSObjectFactory.insertSObject(new Product2(PsProductEngland__c = true, PsRateEngland__c = 4, PsWeightEngland__c = 0.00234));
        aforza__Outlet_Asset__c outletAsset = (aforza__Outlet_Asset__c) TdfSObjectFactory.insertSObject(new aforza__Outlet_Asset__c(aforza__Product__c = prod.Id,
                aforza__Account__c = acc.Id, aforza__Type__c = 'test', PerfectStoreMet__c = true, aforza__Audit_Date__c = System.today()));

        System.debug('Oasset' + [SELECT Id, PerfectScoreWeight__c, PerfectScoreProduct__c, PerfectScoreRate__c, Score__c FROM aforza__Outlet_Asset__c]);

        aforza__Audit__c audit = (aforza__Audit__c) TdfSObjectFactory.insertSObject(new aforza__Audit__c(aforza__Account__c = acc.Id));

        Test.startTest();
        TdfSObjectFactory.insertSObject(new aforza__Audit_Asset__c(aforza__Outlet_Asset__c = outletAsset.Id, aforza__Audit__c = audit.Id, PerfectStoreMet__c = true));
        Test.stopTest();

        aforza__Audit_Asset__c updatedAsset = [SELECT Id, PerfectScoreRate__c, PerfectScoreProduct__c, PerfectScoreWeight__c, Score__c FROM aforza__Audit_Asset__c LIMIT 1][0];

        //as we cant set states via API/Apex, we cant test this logic in tests.
        Assert.areEqual(0, updatedAsset.PerfectScoreRate__c);
        Assert.areEqual(0, updatedAsset.PerfectScoreWeight__c);
        Assert.areEqual(false, updatedAsset.PerfectScoreProduct__c);
        Assert.areEqual(0.00, updatedAsset.Score__c);
    }
}