src/main/default/objects/Account/fields/PerfectStoreScoreEligible__c.field-meta.xml
<CustomField>
    <fullName>PerfectStoreScoreEligible__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please set this to true if you want to start Perfect Store Score for this customer.</inlineHelpText>
    <label>Perfect Store Score Eligible</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/BenchmarkDate__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkDate__c</fullName>
    <formula>null</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Benchmark Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/BenchmarkScore__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkScore__c</fullName>
    <inlineHelpText>Score of the first visit done within any Fiscal year.</inlineHelpText>
    <defaultValue>0</defaultValue>
    <label>Benchmark Score</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectStoreMet__c.field-meta.xml
<CustomField>
    <fullName>PerfectStoreMet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the perfect store condition is met</description>
    <inlineHelpText>Indicates if the perfect store condition is met</inlineHelpText>
    <label>Perfect Store Met?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <formula>aforza__Product__r.PsProductEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsRateEngland__c.field-meta.xml
<CustomField>
    <fullName>PsRateEngland__c</fullName>
    <formula>aforza__Product__r.PsRateEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Rate England</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsWeightEngland__c.field-meta.xml
<CustomField>
    <fullName>PsWeightEngland__c</fullName>
    <formula>aforza__Product__r.PsWeightEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Weight England</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Product2/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify a PS product, and used in the Audit filter on mobile</description>
    <inlineHelpText>Used to identify a PS product, and used in the Audit filter on mobile</inlineHelpText>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/PsRateEngland__c.field-meta.xml
<CustomField>
    <fullName>PsRateEngland__c</fullName>
    <description>PS Rate England used as a multiplier for Calculating Perfect Store</description>
    <inlineHelpText>PS Rate England used as a multiplier for Calculating Perfect Store</inlineHelpText>
    <label>PS Rate England</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Product2/fields/PsWeightEngland__c.field-meta.xml
<CustomField>
    <fullName>PsWeightEngland__c</fullName>
    <description>PS Weightage England used as a multiplier for Calculating Perfect Store</description>
    <inlineHelpText>PS Weightage England used as a multiplier for Calculating Perfect Store</inlineHelpText>
    <label>PS Weight England</label>
    <precision>9</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/BenchmarkServiceTest.cls
@IsTest
public class BenchmarkServiceTest {
    
    @IsTest
    public static void testResetOutletBenchmark() {
        // Create Data
        Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(
            new Product2(PsProductEngland__c = true)
		);
        List<aforza__Outlet_Asset__c> newAssets = new List<aforza__Outlet_Asset__c>();
        newAssets.add((aforza__Outlet_Asset__c) TdfSObjectFactory.insertSObject(
			new aforza__Outlet_Asset__c(
                aforza__Product__c = newProduct.Id,
                BenchmarkDate__c = System.today(),
                BenchmarkScore__c = 10
            )
		));
        
        Test.startTest();
        BenchmarkService.resetOutletBenchmark(newAssets);
        Test.stopTest();
        
        aforza__Outlet_Asset__c oAsset = [SELECT BenchmarkDate__c, BenchmarkScore__c FROM aforza__Outlet_Asset__c WHERE Id = :newAssets[0].Id];
        System.assert(oAsset.BenchmarkDate__c == null, 'Benchmark Date values should be reset');
        System.assert(oAsset.BenchmarkScore__c == 0, 'Benchmark score values should be reset');
    }

    @IsTest
    public static void testResetOutletBenchmark_WithProperOutletAsset() {
        // Create Data
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID, PerfectStoreScoreEligible__c = true));
        // add product in test as the outlet asset will be created in batch
        Test.startTest();
        TdfSObjectFactory.insertSObject(new Product2(PsProductEngland__c = true, PsRateEngland__c = 2.3, PsWeightEngland__c = 0.45));
        Test.stopTest();

        // get outlet asset from acc and update it so it is considered as met
        List<aforza__Outlet_Asset__c> createdAsset = [SELECT Id, PerfectStoreMet__c FROM aforza__Outlet_Asset__c WHERE aforza__Account__c = :acc.Id];
        Assert.isTrue(createdAsset.size() == 1);

        createdAsset[0].PerfectStoreMet__c = true;
        createdAsset[0].aforza__Audit_Date__c = System.today();

        update createdAsset;

        //check that values are populated
        List<aforza__Outlet_Asset__c> createdAssetBenchmarked = [SELECT Id, PerfectStoreMet__c, BenchmarkDate__c, BenchmarkScore__c FROM aforza__Outlet_Asset__c WHERE aforza__Account__c = :acc.Id];
        Assert.isTrue(createdAssetBenchmarked.size() == 1);
        Assert.isTrue(createdAssetBenchmarked[0].BenchmarkDate__c != null, 'There should be date populated');
        //TODO cant check for the score now, as the state cannot be set via data load or metadata, as the fields calculating it are dependent on it and are formula fields
        //Assert.isTrue(createdAssetBenchmarked[0].BenchmarkScore__c != 0, 'The score should be populated to non zero value');

        // run the reset
        BenchmarkService.resetOutletBenchmark(createdAssetBenchmarked);

        // get the new values reset
        aforza__Outlet_Asset__c resetOutletAsset = [SELECT BenchmarkDate__c, BenchmarkScore__c FROM aforza__Outlet_Asset__c WHERE Id = :createdAssetBenchmarked[0].Id];
        Assert.isTrue(resetOutletAsset != null);
        System.assert(resetOutletAsset.BenchmarkDate__c == null, 'Benchmark Date values should be reset = null');
        System.assert(resetOutletAsset.BenchmarkScore__c == 0, 'Benchmark score values should be reset = 0');
    }
}