src/main/default/objects/Account/fields/PrimaryPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPaymentMethod__c</fullName>
    <label>Primary Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card Payment</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Buying Group Central Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/Gross__c.field-meta.xml
<CustomField>
    <fullName>Gross__c</fullName>
    <label>Gross</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/InvoiceReadyForEvaluation__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReadyForEvaluation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used when generating invoice mailing. Marking invoices as ready for evaluation. Ready means that all documents, payments are done and we have all info to evaluate if email should be sent.</description>
    <label>Invoice Ready For Evaluation</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/InvoiceSentToCustomer__c.field-meta.xml
<CustomField>
    <fullName>InvoiceSentToCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field populated by logic in code or flows when email was sent to customer.</description>
    <label>Invoice Sent To Customer</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PaymentLink__c.field-meta.xml
<CustomField>
    <fullName>PaymentLink__c</fullName>
    <inlineHelpText>This field is read only as it will be populated when an appropriate payment is created.</inlineHelpText>
    <label>Payment Link</label>
    <type>Url</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PreAuthCaptured__c.field-meta.xml
<CustomField>
    <fullName>PreAuthCaptured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Auth Captured?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/bt_stripe__Transaction__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/bt_stripe__Transaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/InvoiceSettings__c/InvoiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>An object holding in information about settings for Invoices and logic connected to them.</description>
    <label>Invoice Setrings</label>
</CustomObject>

src/main/default/objects/InvoiceSettings__c/fields/CreatePaymentWhenInvoiceIsCreated__c.field-meta.xml
<CustomField>
    <fullName>CreatePaymentWhenInvoiceIsCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please mark as checked when you want to create a Payment and send its link to customers when invoice is created. It will be created only for invoices without pre-authorisation and linked to customers with Payment Method &quot;Credit Card&quot;.</inlineHelpText>
    <label>Create Payment When Invoice Is Created?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/InvoiceSettings__c/fields/PaymentCommerceOnInvoice__c.field-meta.xml
<CustomField>
    <fullName>PaymentCommerceOnInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please check if you wish to create payments (BT and Aforza) for created invoice linked to E-Commerce Order</inlineHelpText>
    <label>Payment Commerce On Invoice</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Order/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A linked Invoice.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/PreAuthCaptured__c.field-meta.xml
<CustomField>
    <fullName>PreAuthCaptured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre-Auth Captured?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Order/fields/PrimaryPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PrimaryPaymentMethod__c</fullName>
    <formula>TEXT(Account.PrimaryPaymentMethod__c)</formula>
    <label>Primary Payment Method</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/recordTypes/ECommerceOrder.recordType-meta.xml
<RecordType>
    <fullName>ECommerceOrder</fullName>
    <active>true</active>
    <label>E-Commerce Order</label>
</RecordType>

src/main/default/objects/Order/recordTypes/EDIOrder.recordType-meta.xml
<RecordType>
    <fullName>EDIOrder</fullName>
    <active>true</active>
    <label>EDI Order</label>
</RecordType>

src/main/default/objects/Order/recordTypes/FieldDirectOrder.recordType-meta.xml
<RecordType>
    <fullName>FieldDirectOrder</fullName>
    <active>true</active>
    <label>Field Direct Order</label>
</RecordType>

src/main/default/objects/Order/recordTypes/ReturnOrder.recordType-meta.xml
<RecordType>
    <fullName>ReturnOrder</fullName>
    <active>true</active>
    <label>Return Order</label>
</RecordType>

src/main/default/objects/Order/recordTypes/StraightToJDEOrder.recordType-meta.xml
<RecordType>
    <fullName>StraightToJDEOrder</fullName>
    <active>true</active>
    <label>Straight to JDE Order</label>
</RecordType>

src/main/default/objects/Order/recordTypes/TelesalesOrder.recordType-meta.xml
<RecordType>
    <fullName>TelesalesOrder</fullName>
    <active>true</active>
    <label>Telesales Order</label>
</RecordType>

src/main/default/objects/Order/recordTypes/VanSalesOrder.recordType-meta.xml
<RecordType>
    <fullName>VanSalesOrder</fullName>
    <active>true</active>
    <label>Van Sales Order</label>
</RecordType>

src/main/default/classes/InvoiceTriggerHandler.cls
/**
 * Created by svatopluk.sejkora on 16.11.2022.
 */

public with sharing class InvoiceTriggerHandler {

    private static final Boolean CREATE_PAYMENT = InvoiceSettings__c.getOrgDefaults().CreatePaymentWhenInvoiceIsCreated__c;
    private static final Boolean CREATE_PAYMENT_COMMERCE = InvoiceSettings__c.getOrgDefaults().PaymentCommerceOnInvoice__c;
    private static final Set<String> ORDER_RECORD_TYPES_TO_ALLOW_PAYMENT = new Set<String>{
        'EDIOrder', 'FieldDirectOrder', 'TelesalesOrder', 'VanSalesOrder'
    };
    private static final String ORDER_RECORD_TYPE_COMMERCE = 'ECommerceOrder';

    //'ReturnOrder','StraightToJDEOrder' - yet unused order record types

    /**
     * @description creates BT transaction whenever an invoice without pre auth is created. It needs to be also enabled in custom settings
     * and Payment method needs to be Credit Card
     *
     * @param invoicesMap map of newly created invoices
     *
     *
     * @author Svatopluk Sejkora, BearingPoint
     * @date 2022-11-14
     */
    public static void createTransactions(Map<Id, aforza__Invoice__c> invoicesMap) {
        // get needed data
        List<aforza__Invoice__c> invoicesWithRelatedData = getInvoicesWithNeededData(invoicesMap.keySet());

        List<bt_stripe__Transaction__c> transactionsToCreate = new List<bt_stripe__Transaction__c>();
        Set<Id> invoiceIds = new Set<Id>();
        for (aforza__Invoice__c invoice : invoicesWithRelatedData) {
            if (invoice.aforza__Order__r.PrimaryPaymentMethod__c == 'Card Payment' && invoice.aforza__Order__r.PreAuthCaptured__c == false
                && (CREATE_PAYMENT == true && ORDER_RECORD_TYPES_TO_ALLOW_PAYMENT.contains(invoice.aforza__Order__r.RecordType.DeveloperName)
                || CREATE_PAYMENT_COMMERCE == true && invoice.aforza__Order__r.RecordType.DeveloperName == ORDER_RECORD_TYPE_COMMERCE)) {
                    transactionsToCreate.add(createTransactionRecord(invoice));
                    invoiceIds.add(invoice.Id);
            }
        }

        insert transactionsToCreate;
        if (transactionsToCreate.size() > 0) {
            updateInvoiceWithPayLink(invoicesWithRelatedData, invoiceIds);
        }
    }

    public static void evaluateAndSendEmailToCustomer(List<aforza__Invoice__c> invoices) {
        Set<Id> invoiceToSendEmailForIds = new Set<Id>();
        for (aforza__Invoice__c invoice :invoices) {
            if (invoice.InvoiceSentToCustomer__c == false && invoice.InvoiceReadyForEvaluation__c == true) {
                invoiceToSendEmailForIds.add(invoice.Id);
            }
        }
        InvoiceEmailService.sendInvoiceToCustomers(invoiceToSendEmailForIds);
    }

    /**
     * @description maps invoice data and default values to BT payment
     *
     * @param invoice invoice from which to create BT payment
     *
     * @return mapped BT transaction
     *
     *
     * @author Svatopluk Sejkora, BearingPoint
     * @date 2022-11-14
     */
    @TestVisible
    private static bt_stripe__Transaction__c createTransactionRecord(aforza__Invoice__c invoice) {
        bt_stripe__Transaction__c btTransaction = new bt_stripe__Transaction__c();
        btTransaction.RecordTypeId = RecordTypes.BT_TRANSACTION_CHARGE_ID;
        btTransaction.bt_stripe__Amount__c = invoice.Gross__c;
        btTransaction.bt_stripe__Description__c = 'Payment Request for ' + invoice.aforza__Order__r.OrderNumber;
        btTransaction.bt_stripe__Transaction_Type__c = 'Normal';
        btTransaction.bt_stripe__Transaction_Status__c = 'Open';
        btTransaction.bt_stripe__Related_Contact__c = invoice.aforza__Account__r.aforza__Primary_Contact__c;
        btTransaction.bt_stripe__Related_Account__c = invoice.aforza__Account__c;
        btTransaction.bt_stripe__Processed_Date__c = System.now();
        btTransaction.Order__c = invoice.aforza__Order__c;
        btTransaction.Invoice__c = invoice.Id;

        return btTransaction;
    }

    private static void updateInvoiceWithPayLink(List<aforza__Invoice__c> invoiceList, Set<Id> invoiceIds) {
        // get the payments with links
        Map<Id, String> invoiceIdToItsPaymentLink = getPaymentLinks(invoiceIds);

        for (aforza__Invoice__c invoice : invoiceList) {
            invoice.PaymentLink__c = invoiceIdToItsPaymentLink.get(invoice.Id);
        }

        update invoiceList;
    }

    private static Map<Id, String> getPaymentLinks(Set<Id> invoiceIds) {
        Map<Id, String> invoiceIdToItsPaymentLink = new Map<Id, String>();
        for (bt_stripe__Transaction__c btTransaction : [SELECT Id, Invoice__c, bt_paylink__PayLink__c FROM bt_stripe__Transaction__c WHERE Invoice__c IN :invoiceIds]) {
            invoiceIdToItsPaymentLink.put(btTransaction.Invoice__c, btTransaction.bt_paylink__PayLink__c);
        }
        return invoiceIdToItsPaymentLink;
    }

    private static List<aforza__Invoice__c> getInvoicesWithNeededData(Set<Id> invoicesIds) {
        return [
            SELECT Id, aforza__Order__r.PrimaryPaymentMethod__c, aforza__Order__r.PreAuthCaptured__c,
                aforza__Order__r.RecordType.DeveloperName, Gross__c, aforza__Account__r.aforza__Primary_Contact__c,
                aforza__Account__c, aforza__Order__c, aforza__Order__r.OrderNumber, PaymentLink__c
            FROM aforza__Invoice__c
            WHERE Id IN :invoicesIds
        ];
    }
}