src/main/default/objects/Account/fields/PrimaryGridNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryGridNumber__c</fullName>
    <label>Primary Grid Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Inventory__c/aforza__Inventory__c.object-meta.xml
<CustomObject>
    <description>A building or vehicle used to store products.</description>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Inventory_Product__c/fields/PickingLocation__c.field-meta.xml
<CustomField>
    <fullName>PickingLocation__c</fullName>
    <inlineHelpText>Picking location for this inventory product</inlineHelpText>
    <label>Picking Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Load__c/Load__c.object-meta.xml
<CustomObject>
    <label>Load</label>
    <nameField>
        <label>Load ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Load__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Load__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Loads</relationshipLabel>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Load__c/fields/VehicleRegistration__c.field-meta.xml
<CustomField>
    <fullName>VehicleRegistration__c</fullName>
    <formula>Vehicle__r.VehicleRegistration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Registration</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Order/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <label>Grid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Load</label>
    <referenceTo>Load__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/PalletSequence__c.field-meta.xml
<CustomField>
    <fullName>PalletSequence__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pallet Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Order/fields/ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortDescription__c</fullName>
    <inlineHelpText>Populated with Account name when Accounts Separate Load is checked.</inlineHelpText>
    <label>Short Description</label>
    <type>TextArea</type>
</CustomField>

src/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>VEH-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Vehicle__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Driver associated with this vehicle.</inlineHelpText>
    <label>Driver</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This user is not a Driver (need to add Driver as this user&apos;s role).</errorMessage>
        <filterItems>
            <field>User.UserRole.DeveloperName</field>
            <operation>equals</operation>
            <value>Driver</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Vehicle__c/fields/VehicleRegistration__c.field-meta.xml
<CustomField>
    <fullName>VehicleRegistration__c</fullName>
    <inlineHelpText>Vehicle Registration in format = &quot;AA11 AAA&quot;.</inlineHelpText>
    <label>Vehicle Registration</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/classes/PickSheetPDFControllerTest.cls
/**
 * Created by magdalena.stanciu on 15.10.2022.
 */
@IsTest
private with sharing class PickSheetPDFControllerTest {
    private static final String GRID = '3C7201MOW';
    private static final String VEHICLE_REGISTRATION_NUMBER = 'AA11 AAA';
    private static final Date DELIVERY_DATE = Date.parse('12/10/2022');
    private static final Integer PALLET_SEQUENCE = 1;
    private static final String PALLET_DESCRIPTION = 'Description 1';
    private static final String PICK_LOCATION_PROD = 'A1';

    @IsTest
    private static void testInitializePageWithIncorrectParameters() {
        PageReference pageRef = Page.AGBarrPickSheet;
        Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('p', 'test');

        Test.startTest();
        PickSheetPDFController ctrl = new PickSheetPDFController();
        Test.stopTest();

        Assert.areEqual(0, ctrl.loadPlans.size());
    }

    @IsTest
    private static void testInitializePageWithCorrectParameters_SingleOrder() {
        // create product
        Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(new Product2());

        // add new product to standard PB
        TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId)
        );

        // create pricebook and add products to pricebook
        Pricebook2 newPricebook = (Pricebook2) TdfSObjectFactory.insertSObject(new Pricebook2());
        PricebookEntry productPricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = newPricebook.Id)
        );

        // create account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
            aforza__Default_Price_Book__c = newPricebook.Id,
            RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
            PrimaryGridNumber__c = GRID
        ));

        // create inventory and add products to inventory
        aforza__Inventory__c newInventory = (aforza__Inventory__c) TdfSObjectFactory.insertSObject(
                new aforza__Inventory__c(RecordTypeId = RecordTypes.INVENTORY_BUILDING_ID)
        );
        aforza__Inventory_Product__c newInventoryProduct1 = (aforza__Inventory_Product__c) TdfSObjectFactory.insertSObject(
            new aforza__Inventory_Product__c(
                aforza__Inventory__c = newInventory.Id,
                aforza__Product__c = newProduct.Id,
                PickingLocation__c = PICK_LOCATION_PROD
            )
        );

        // create orders and add products to it
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(
            RecordTypeId = RecordTypes.ORDER_FIELD_DIRECT_ID,
            AccountId = dpAccount.Id,
            Grid__c = GRID,
            Pricebook2Id = newPricebook.Id,
            aforza__Inventory__c = newInventory.Id
        ));
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(new OrderItem(
            OrderId = newOrder.Id,
            Product2Id = newProduct.Id,
            Quantity = 10,
            PricebookEntryId = productPricebookEntry.Id
        ));

        // create Vehicle
        Vehicle__c newVehicle = (Vehicle__c) TdfSObjectFactory.insertSObject(
            new Vehicle__c(VehicleRegistration__c = VEHICLE_REGISTRATION_NUMBER)
        );

        // create Load
        Load__c newLoad = (Load__c) TdfSObjectFactory.insertSObject(
            new Load__c(DeliveryDate__c = DELIVERY_DATE, Vehicle__c = newVehicle.Id, Driver__c = UserInfo.getUserId())
        );

        // add orders to the load
        List<Order> ordersToUpdate = new List<Order>();

        newOrder.Load__c = newLoad.Id;
        newOrder.PalletSequence__c = PALLET_SEQUENCE;
        newOrder.ShortDescription__c = PALLET_DESCRIPTION;
        ordersToUpdate.add(newOrder);

        update ordersToUpdate;

        PageReference pageRef = Page.AGBarrPickSheet;
        Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('p', newOrder.Id);

        Test.startTest();
        PickSheetPDFController ctrl = new PickSheetPDFController();
        Test.stopTest();

        Assert.areEqual(1, ctrl.loadPlans.size());
    }

    @IsTest
    private static void testInitializePageWithCorrectParameters_MultipleOrders() {
        // create product
        Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(new Product2());

        // add new product to standard PB
        TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId)
        );

        // create pricebook and add products to pricebook
        Pricebook2 newPricebook = (Pricebook2) TdfSObjectFactory.insertSObject(new Pricebook2());
        PricebookEntry productPricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = newPricebook.Id)
        );

        // create account
        Account dpAccount = (Account) TdfSObjectFactory.insertSObject(new Account(
            aforza__Default_Price_Book__c = newPricebook.Id,
            RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID,
            PrimaryGridNumber__c = GRID
        ));

        // create inventory and add products to inventory
        aforza__Inventory__c newInventory = (aforza__Inventory__c) TdfSObjectFactory.insertSObject(
            new aforza__Inventory__c(RecordTypeId = RecordTypes.INVENTORY_BUILDING_ID)
        );
        TdfSObjectFactory.insertSObject(
            new aforza__Inventory_Product__c(
                aforza__Inventory__c = newInventory.Id,
                aforza__Product__c = newProduct.Id,
                PickingLocation__c = PICK_LOCATION_PROD
            )
        );

        // create orders and add products to it
        Order newOrder1 = (Order) TdfSObjectFactory.insertSObject(new Order(
            RecordTypeId = RecordTypes.ORDER_FIELD_DIRECT_ID,
            AccountId = dpAccount.Id,
            Grid__c = GRID,
            Pricebook2Id = newPricebook.Id,
            aforza__Inventory__c = newInventory.Id
        ));
        TdfSObjectFactory.insertSObject(new OrderItem(
            OrderId = newOrder1.Id,
            Product2Id = newProduct.Id,
            Quantity = 10,
            PricebookEntryId = productPricebookEntry.Id
        ));

        Order newOrder2 = (Order) TdfSObjectFactory.insertSObject(new Order(
            RecordTypeId = RecordTypes.ORDER_FIELD_DIRECT_ID,
            AccountId = dpAccount.Id,
            Grid__c = GRID,
            Pricebook2Id = newPricebook.Id,
            aforza__Inventory__c = newInventory.Id
        ));
        OrderItem newOrderItem2 = (OrderItem) TdfSObjectFactory.insertSObject(new OrderItem(
            OrderId = newOrder1.Id,
            Product2Id = newProduct.Id,
            Quantity = 20,
            PricebookEntryId = productPricebookEntry.Id
        ));

        // create Vehicle
        Vehicle__c newVehicle = (Vehicle__c) TdfSObjectFactory.insertSObject(
            new Vehicle__c(VehicleRegistration__c = VEHICLE_REGISTRATION_NUMBER)
        );

        // create Load
        Load__c newLoad = (Load__c) TdfSObjectFactory.insertSObject(
            new Load__c(DeliveryDate__c = DELIVERY_DATE, Vehicle__c = newVehicle.Id, Driver__c = UserInfo.getUserId())
        );

        // add orders to the load
        List<Order> ordersToUpdate = new List<Order>();

        newOrder1.Load__c = newLoad.Id;
        newOrder1.PalletSequence__c = PALLET_SEQUENCE;
        newOrder1.ShortDescription__c = PALLET_DESCRIPTION;
        ordersToUpdate.add(newOrder1);

        newOrder2.Load__c = newLoad.Id;
        newOrder2.PalletSequence__c = PALLET_SEQUENCE;
        newOrder2.ShortDescription__c = PALLET_DESCRIPTION;
        ordersToUpdate.add(newOrder2);

        update ordersToUpdate;

        PageReference pageRef = Page.AGBarrPickSheet;
        Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('p', newOrder1.Id + ',' + newOrder2.Id);

        Test.startTest();
        PickSheetPDFController ctrl = new PickSheetPDFController();
        Test.stopTest();

        Assert.areEqual(1, ctrl.loadPlans.size());
    }
}