src/main/default/objects/aforza__Relationship_Rule__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/Product2/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of product.</description>
    <inlineHelpText>The type of product.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Still</fullName>
            </value>
            <value>
                <fullName>Sparkling</fullName>
            </value>
            <value>
                <fullName>Baby</fullName>
                <isActive>false</isActive>
                <label>Baby</label>
            </value>
            <value>
                <fullName>Beer, Wine &amp; Spirits</fullName>
                <isActive>false</isActive>
                <label>Beer, Wine &amp; Spirits</label>
            </value>
            <value>
                <fullName>Bins &amp; Fridges</fullName>
                <isActive>false</isActive>
                <label>Bins &amp; Fridges</label>
            </value>
            <value>
                <fullName>Bread &amp; Bakery</fullName>
                <isActive>false</isActive>
                <label>Bread &amp; Bakery</label>
            </value>
            <value>
                <fullName>Breakfast &amp; Cereal</fullName>
                <isActive>false</isActive>
                <label>Breakfast &amp; Cereal</label>
            </value>
            <value>
                <fullName>Brochures &amp; Handouts</fullName>
                <isActive>false</isActive>
                <label>Brochures &amp; Handouts</label>
            </value>
            <value>
                <fullName>Canned Goods &amp; Soups</fullName>
                <isActive>false</isActive>
                <label>Canned Goods &amp; Soups</label>
            </value>
            <value>
                <fullName>Cleaning Supplies</fullName>
                <isActive>false</isActive>
                <label>Cleaning Supplies</label>
            </value>
            <value>
                <fullName>Condiments/Spices &amp; Bake</fullName>
                <isActive>false</isActive>
                <label>Condiments/Spices &amp; Bake</label>
            </value>
            <value>
                <fullName>Cookies, Snacks &amp; Candy</fullName>
                <isActive>false</isActive>
                <label>Cookies, Snacks &amp; Candy</label>
            </value>
            <value>
                <fullName>Dairy, Eggs &amp; Cheese</fullName>
                <isActive>false</isActive>
                <label>Dairy, Eggs &amp; Cheese</label>
            </value>
            <value>
                <fullName>Deli &amp; Signature Cafe</fullName>
                <isActive>false</isActive>
                <label>Deli &amp; Signature Cafe</label>
            </value>
            <value>
                <fullName>Fixtures</fullName>
                <isActive>false</isActive>
                <label>Fixtures</label>
            </value>
            <value>
                <fullName>Flowers</fullName>
                <isActive>false</isActive>
                <label>Flowers</label>
            </value>
            <value>
                <fullName>Frozen Foods</fullName>
                <isActive>false</isActive>
                <label>Frozen Foods</label>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
                <isActive>false</isActive>
                <label>Fruits &amp; Vegetables</label>
            </value>
            <value>
                <fullName>Gondolas</fullName>
                <isActive>false</isActive>
                <label>Gondolas</label>
            </value>
            <value>
                <fullName>Grains, Pasta &amp; Sides</fullName>
                <isActive>false</isActive>
                <label>Grains, Pasta &amp; Sides</label>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
                <isActive>false</isActive>
                <label>Health &amp; Beauty</label>
            </value>
            <value>
                <fullName>International Cuisine</fullName>
                <isActive>false</isActive>
                <label>International Cuisine</label>
            </value>
            <value>
                <fullName>Meat &amp; Seafood</fullName>
                <isActive>false</isActive>
                <label>Meat &amp; Seafood</label>
            </value>
            <value>
                <fullName>Paper Products</fullName>
                <isActive>false</isActive>
                <label>Paper Products</label>
            </value>
            <value>
                <fullName>Personal Care &amp; Pharmacy</fullName>
                <isActive>false</isActive>
                <label>Personal Care &amp; Pharmacy</label>
            </value>
            <value>
                <fullName>Pet Care</fullName>
                <isActive>false</isActive>
                <label>Pet Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/DRSGrossUnits__c.field-meta.xml
<CustomField>
    <fullName>DRSGrossUnits__c</fullName>
    <label>DRS Gross Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Product2/fields/DRSSKUCode__c.field-meta.xml
<CustomField>
    <fullName>DRSSKUCode__c</fullName>
    <label>DRS SKU Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/ProductSetting__mdt/ProductSetting__mdt.object-meta.xml
<CustomObject>
    <description>Settings used for operations related to Products.</description>
    <label>Product Setting</label>
    <pluralLabel>Product Settings</pluralLabel>
</CustomObject>

src/main/default/objects/ProductSetting__mdt/fields/DRSProductRelationshipRulePrefix__c.field-meta.xml
<CustomField>
    <fullName>DRSProductRelationshipRulePrefix__c</fullName>
    <label>DRS Product Relationship Rule Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/InsecureProductService.cls
/**
 * Created by magdalena.stanciu on 20.09.2022.
 */

public without sharing class InsecureProductService {
    public static final ProductSetting__mdt SETTINGS {
        get {
            if (SETTINGS == null) {
                SETTINGS = ProductSetting__mdt.getInstance('OrgDefaultProductSettings');
            }
            return SETTINGS;
        }
        set;
    }

    public static void removeOffSaleProductsFromAssortments(Set<Id> productIds) {
        List<aforza__Assortment_Product__c> assortProds = [
            SELECT Id
            FROM aforza__Assortment_Product__c
            WHERE aforza__Product__c IN :productIds
        ];
        delete assortProds;
    }

    public static void createDRSRelationshipRules(List<Product2> newProducts) {
        List<String> productCodesCodesOfRelatedDRSProducts = new List<String>();
        for (Product2 newProduct : newProducts) {
            productCodesCodesOfRelatedDRSProducts.add(newProduct.DRSSKUCode__c);
        }

        Map<String, Product2> drsProducts = getProductsBasedOnProductCodes(productCodesCodesOfRelatedDRSProducts);

        List<aforza__Relationship_Rule__c> relationshipRulesToBeCreated = new List<aforza__Relationship_Rule__c>();
        for (Product2 newProduct : newProducts) {
            Product2 drsProduct = drsProducts.get(newProduct.DRSSKUCode__c);
            if (drsProduct != null) {
                aforza__Relationship_Rule__c newRelationshipRule = createNewDRSRelationshipRule(
                        newProduct, drsProduct
                );
                relationshipRulesToBeCreated.add(newRelationshipRule);
            }
        }

        insert relationshipRulesToBeCreated;
    }

    public static Map<String, Product2> getProductsBasedOnProductCodes(List<String> productCodes) {
        List<Product2> drsProducts = [
            SELECT Id, Name, ProductCode
            FROM Product2
            WHERE ProductCode IN :productCodes
        ];

        Map<String, Product2> productsBySKU = new Map<String, Product2>();
        for (Product2 newProduct : drsProducts) {
            productsBySKU.put(newProduct.ProductCode, newProduct);
        }

        return productsBySKU;
    }

    public static aforza__Relationship_Rule__c createNewDRSRelationshipRule(Product2 baseProduct, Product2 drsProduct) {
        aforza__Relationship_Rule__c relationship = new aforza__Relationship_Rule__c();
        relationship.ExternalId__c = createExternalIdForRelationshipRule(
            SETTINGS.DRSProductRelationshipRulePrefix__c,
            baseProduct.ProductCode,
            drsProduct.ProductCode
        );
        relationship.Name = baseProduct.Name + ' - ' + drsProduct.Name;
        relationship.aforza__Source_Product__c = baseProduct.Id;
        relationship.aforza__Target_Product__c = drsProduct.Id;
        relationship.aforza__Type__c = 'Addition';
        relationship.aforza__Active__c = true;
        relationship.aforza__Rule_Source__c = 'Manual';
        relationship.aforza__Quantity__c = baseProduct.DRSGrossUnits__c;
        return relationship;
    }

    public static void deleteDRSRelationshipRules(List<Product2> oldProducts) {
        List<String> idsOfRelationshipsToBeDeleted = new List<String>();
        for (Product2 oldProduct : oldProducts) {
            idsOfRelationshipsToBeDeleted.add(
                createExternalIdForRelationshipRule(
                    SETTINGS.DRSProductRelationshipRulePrefix__c,
                    oldProduct.ProductCode,
                    oldProduct.DRSSKUCode__c
                )
            );
        }

        List<aforza__Relationship_Rule__c> relationshipsToBeDeleted = [
            SELECT Id
            FROM aforza__Relationship_Rule__c
            WHERE ExternalId__c IN :idsOfRelationshipsToBeDeleted
        ];

        delete relationshipsToBeDeleted;
    }

    public static void updateDRSRelationshipRules(List<Product2> newProducts) {
        List<aforza__Relationship_Rule__c> relationshipsToBeUpdated = new List<aforza__Relationship_Rule__c>();
        for (Product2 newProduct : newProducts) {
            aforza__Relationship_Rule__c newRelationship = new aforza__Relationship_Rule__c();
            newRelationship.ExternalId__c = createExternalIdForRelationshipRule (
                SETTINGS.DRSProductRelationshipRulePrefix__c,
                newProduct.ProductCode,
                newProduct.DRSSKUCode__c
            );
            newRelationship.aforza__Quantity__c = newProduct.DRSGrossUnits__c;
            relationshipsToBeUpdated.add(newRelationship);
        }
        upsert relationshipsToBeUpdated ExternalId__c;
    }

    public static String createExternalIdForRelationshipRule(String prefix, String baseProductSKU, String drsProductSku) {
        return prefix + baseProductSKU + drsProductSku;
    }
}