src/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>VEH-{0000}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Vehicle__c/fields/AssociatedDepot__c.field-meta.xml
<CustomField>
    <fullName>AssociatedDepot__c</fullName>
    <inlineHelpText>The Depot associated with this vehicle.</inlineHelpText>
    <label>Associated Depot</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DepotValues</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Vehicle__c/fields/LoadCapacityWeight__c.field-meta.xml
<CustomField>
    <fullName>LoadCapacityWeight__c</fullName>
    <inlineHelpText>The Weight Load Capacity of this vehicle.</inlineHelpText>
    <label>Load Capacity (Weight)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Vehicle__c/fields/LoadLimitCases__c.field-meta.xml
<CustomField>
    <fullName>LoadLimitCases__c</fullName>
    <inlineHelpText>The Cases Load Limit of this vehicle.</inlineHelpText>
    <label>Load Limit (Cases)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/Vehicle__c/fields/VehicleRegistration__c.field-meta.xml
<CustomField>
    <fullName>VehicleRegistration__c</fullName>
    <inlineHelpText>Vehicle Registration in format = &quot;AA11 AAA&quot;.</inlineHelpText>
    <label>Vehicle Registration</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/globalValueSets/DepotValues.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>D</fullName>
        <label>Dagenham</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>Wednesbury</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>Moston</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Scotland</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cranks</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>Bentleys</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Murdens</label>
    </customValue>
    <customValue>
        <fullName>Z</fullName>
        <label>Menzies</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Blacks</label>
    </customValue>
    <customValue>
        <fullName>Cumbernauld</fullName>
        <isActive>false</isActive>
        <label>Cumbernauld</label>
    </customValue>
    <masterLabel>Depot Values</masterLabel>
</GlobalValueSet>

src/main/default/classes/TdfVehicleTemplate.cls
/**
 * Class provides functionality for creating default vehicle in test methods.
 *
 * Do not use this class directly.
 * Class is initialized in TDF_SObjectTemplateFactory and all its functionality is used through TDF_SObjectFactory.
 *
 * @see TdfSObjectFactory
 * @see TdfSObjectTemplate
 * @see TdfSObjectTemplateFactory
 *
 * @author  Magdalena Stanciu
 * @date    2022-10-15
 *
 */
@IsTest
public with sharing class TdfVehicleTemplate extends TdfSObjectTemplate {
    /**
     * Instance is created dynamically. This method compensates a constructor.
     *
     * @author  Magdalena Stanciu
     * @date    2022-10-15
     *
     */
    public override void init() {
        Vehicle__c userDefinedVehicle = (Vehicle__c) userDefinedSObject;
    }

    /**
     * Creates a template SObject. Every call returns a new instance.
     *
     * Because this method can be called multiple times, all operations as DML or SOQL has to be done in init().
     *
     * @return template with vehicle record
     *
     * @author  Magdalena Stanciu
     * @date    2022-10-15
     */
    protected override SObject createTemplateSObject() {
        Vehicle__c template = new Vehicle__c(
                VehicleRegistration__c = 'AA11 AAA',
                AssociatedDepot__c = 'D',
                LoadCapacityWeight__c = 3000,
                LoadLimitCases__c = 100
        );

        return template;
    }
}