src/main/default/objects/aforza__Outlet_Asset__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of outlet asset.</description>
    <inlineHelpText>The type of outlet asset.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Competitor Product</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/FocusFiveProduct__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveProduct__c</fullName>
    <formula>aforza__Product__r.FocusFiveProduct__c</formula>
    <label>Focus 5 Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <formula>aforza__Product__r.PsProductEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductScotland__c.field-meta.xml
<CustomField>
    <fullName>PsProductScotland__c</fullName>
    <formula>aforza__Product__r.PsProductScotland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product Scotland</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of product.</description>
    <inlineHelpText>The type of product.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Still</fullName>
            </value>
            <value>
                <fullName>Sparkling</fullName>
            </value>
            <value>
                <fullName>Baby</fullName>
                <isActive>false</isActive>
                <label>Baby</label>
            </value>
            <value>
                <fullName>Beer, Wine &amp; Spirits</fullName>
                <isActive>false</isActive>
                <label>Beer, Wine &amp; Spirits</label>
            </value>
            <value>
                <fullName>Bins &amp; Fridges</fullName>
                <isActive>false</isActive>
                <label>Bins &amp; Fridges</label>
            </value>
            <value>
                <fullName>Bread &amp; Bakery</fullName>
                <isActive>false</isActive>
                <label>Bread &amp; Bakery</label>
            </value>
            <value>
                <fullName>Breakfast &amp; Cereal</fullName>
                <isActive>false</isActive>
                <label>Breakfast &amp; Cereal</label>
            </value>
            <value>
                <fullName>Brochures &amp; Handouts</fullName>
                <isActive>false</isActive>
                <label>Brochures &amp; Handouts</label>
            </value>
            <value>
                <fullName>Canned Goods &amp; Soups</fullName>
                <isActive>false</isActive>
                <label>Canned Goods &amp; Soups</label>
            </value>
            <value>
                <fullName>Cleaning Supplies</fullName>
                <isActive>false</isActive>
                <label>Cleaning Supplies</label>
            </value>
            <value>
                <fullName>Condiments/Spices &amp; Bake</fullName>
                <isActive>false</isActive>
                <label>Condiments/Spices &amp; Bake</label>
            </value>
            <value>
                <fullName>Cookies, Snacks &amp; Candy</fullName>
                <isActive>false</isActive>
                <label>Cookies, Snacks &amp; Candy</label>
            </value>
            <value>
                <fullName>Dairy, Eggs &amp; Cheese</fullName>
                <isActive>false</isActive>
                <label>Dairy, Eggs &amp; Cheese</label>
            </value>
            <value>
                <fullName>Deli &amp; Signature Cafe</fullName>
                <isActive>false</isActive>
                <label>Deli &amp; Signature Cafe</label>
            </value>
            <value>
                <fullName>Fixtures</fullName>
                <isActive>false</isActive>
                <label>Fixtures</label>
            </value>
            <value>
                <fullName>Flowers</fullName>
                <isActive>false</isActive>
                <label>Flowers</label>
            </value>
            <value>
                <fullName>Frozen Foods</fullName>
                <isActive>false</isActive>
                <label>Frozen Foods</label>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
                <isActive>false</isActive>
                <label>Fruits &amp; Vegetables</label>
            </value>
            <value>
                <fullName>Gondolas</fullName>
                <isActive>false</isActive>
                <label>Gondolas</label>
            </value>
            <value>
                <fullName>Grains, Pasta &amp; Sides</fullName>
                <isActive>false</isActive>
                <label>Grains, Pasta &amp; Sides</label>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
                <isActive>false</isActive>
                <label>Health &amp; Beauty</label>
            </value>
            <value>
                <fullName>International Cuisine</fullName>
                <isActive>false</isActive>
                <label>International Cuisine</label>
            </value>
            <value>
                <fullName>Meat &amp; Seafood</fullName>
                <isActive>false</isActive>
                <label>Meat &amp; Seafood</label>
            </value>
            <value>
                <fullName>Paper Products</fullName>
                <isActive>false</isActive>
                <label>Paper Products</label>
            </value>
            <value>
                <fullName>Personal Care &amp; Pharmacy</fullName>
                <isActive>false</isActive>
                <label>Personal Care &amp; Pharmacy</label>
            </value>
            <value>
                <fullName>Pet Care</fullName>
                <isActive>false</isActive>
                <label>Pet Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/FocusFiveProduct__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Pease check this field when the Product should be considered as Focus 5 Product. It will add this product to All DPs Outlet Assets. When the product is unchecked as Focus 5 Product it will be unchecked as Focus 5 Product or deleted if no orders from Outlet Assets.</inlineHelpText>
    <label>Focus 5 Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify a PS product, and used in the Audit filter on mobile</description>
    <inlineHelpText>Used to identify a PS product, and used in the Audit filter on mobile</inlineHelpText>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/PsProductScotland__c.field-meta.xml
<CustomField>
    <fullName>PsProductScotland__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify a PS product, and used in the Audit filter on mobile</description>
    <inlineHelpText>Used to identify a PS product, and used in the Audit filter on mobile</inlineHelpText>
    <label>PS Product Scotland</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/OutletAssetService.cls
/**
 * Created by svatopluk.sejkora on 04.10.2022.
 */

public with sharing class OutletAssetService {
    private static final List<Product2> FOCUSED_PRODUCTS {
        get {
            if (FOCUSED_PRODUCTS == null) {
                FOCUSED_PRODUCTS = new List<Product2>(
                        getFocusProducts()
                );
            }
            return FOCUSED_PRODUCTS;
        }
        set;
    }

    private static final Map<String, List<Product2>> PERFECT_STORE_PRODUCTS {
        get {
            if (PERFECT_STORE_PRODUCTS == null) {
                PERFECT_STORE_PRODUCTS = new Map<String, List<Product2>>(
                        getPerfectStoreProducts()
                );
            }
            return PERFECT_STORE_PRODUCTS;
        }
        set;
    }

    public static List<aforza__Outlet_Asset__c> createOutletAssetsForAccounts(Set<Account> accounts, AccountTriggerHandler.OutletAssetType outletAssetType) {
        List<aforza__Outlet_Asset__c> outletAssetsToImport = new List<aforza__Outlet_Asset__c>();
        List<Product2> productsToLinkOutletAssetsTo = new List<Product2>();
        for (Account acc : accounts) {
            if (outletAssetType == AccountTriggerHandler.OutletAssetType.FOCUS) {
                productsToLinkOutletAssetsTo = FOCUSED_PRODUCTS;
            } else if (outletAssetType == AccountTriggerHandler.OutletAssetType.PERFECT_SCORE) {
                if (Test.isRunningTest()) {
                    // as the states cannot be added via API/Apex, we are not able to set them in scratch org, thus validation would
                    // be failing and scratch org tests as well. This is why we are using different logic to obtain values.
                    // this should be removed once States can be created via API/Apex - if ever.
                    productsToLinkOutletAssetsTo = PERFECT_STORE_PRODUCTS.get('England');
                } else {
                    productsToLinkOutletAssetsTo = PERFECT_STORE_PRODUCTS.get(acc.ShippingState);
                }
            }

            for (Product2 product : productsToLinkOutletAssetsTo) {
                outletAssetsToImport.add(createOutletAsset(acc.Id, product));
            }
        }
        return outletAssetsToImport;
    }

    public static void addNewOutletAssets(Set<Id> accounts, List<Product2> products) {
        // determine if the newly focused products are already attached to account (from previous orders)
        Map<Id, Map<Id, Date>> accountsOutletAssetsByProductId = getAccountsOutletAssets(accounts);
        List<aforza__Outlet_Asset__c> outletAssetsToImport = new List<aforza__Outlet_Asset__c>();
        System.debug(accounts);
        System.debug(products);

        for (Id accountId : accounts) {
            Set<Id> outletAssetProductIds = new Set<Id>();
            if (accountsOutletAssetsByProductId.size() > 0 && accountsOutletAssetsByProductId.containsKey(accountId)) {
                outletAssetProductIds = accountsOutletAssetsByProductId?.get(accountId).keySet();
            }
            for (Product2 focusedProduct : products) {
                // if the id is not present in current list we add new Asset Outlet
                if (outletAssetProductIds.isEmpty() || !outletAssetProductIds.contains(focusedProduct.Id)) {
                    outletAssetsToImport.add(createOutletAsset(accountId, focusedProduct));
                }
            }
        }
        // running with limit 150, so save up to 50 focused products, in case we need more, the batch size needs to be lowered
        insert outletAssetsToImport;
    }

    private static List<Product2> getFocusProducts() {
        return [SELECT Id, Name, StockKeepingUnit, Family FROM Product2 WHERE FocusFiveProduct__c = TRUE];
    }

    private static Map<String, List<Product2>> getPerfectStoreProducts() {
        Map<String, List<Product2>> stateToProducts = new Map<String, List<Product2>>{
                'England' => new List<Product2>(), 'Scotland' => new List<Product2>()
        };
        for (Product2 product : [
                SELECT Id, Name, StockKeepingUnit, Family, PsProductEngland__c, PsProductScotland__c
                FROM Product2
                WHERE PsProductEngland__c = TRUE
                OR PsProductScotland__c = TRUE
        ]) {
            if (product.PsProductEngland__c) {
                stateToProducts.get('England').add(product);
            }

            if (product.PsProductScotland__c) {
                stateToProducts.get('Scotland').add(product);
            }
        }
        return stateToProducts;
    }

    @TestVisible
    private static aforza__Outlet_Asset__c createOutletAsset(Id accId, Product2 product) {
        aforza__Outlet_Asset__c outletAsset = new aforza__Outlet_Asset__c();
        outletAsset.aforza__Account__c = accId;
        outletAsset.aforza__Product__c = product.Id;
        outletAsset.aforza__Name__c = product.Name;
        outletAsset.aforza__Type__c = product.Family;

        return outletAsset;
    }

    @TestVisible
    private static Map<Id, Map<Id, Date>> getAccountsOutletAssets(Set<Id> accountIdsSet) {
        Map<Id, Map<Id, Date>> accountIdToOutletAssetsProductIds = new Map<Id, Map<Id, Date>>();
        for (aforza__Outlet_Asset__c asset : [SELECT Id, aforza__Account__c, aforza__Product__c, aforza__Purchase_Date__c FROM aforza__Outlet_Asset__c WHERE aforza__Account__c IN :accountIdsSet]) {
            if (accountIdToOutletAssetsProductIds.containsKey(asset.aforza__Account__c)) {
                accountIdToOutletAssetsProductIds.get(asset.aforza__Account__c).put(asset.aforza__Product__c, asset.aforza__Purchase_Date__c);
            } else {
                accountIdToOutletAssetsProductIds.put(asset.aforza__Account__c, new Map<Id, Date>{
                        asset.aforza__Product__c => asset.aforza__Purchase_Date__c
                });
            }
        }
        return accountIdToOutletAssetsProductIds;
    }
}