src/main/default/objects/aforza__Outlet_Asset__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of outlet asset.</description>
    <inlineHelpText>The type of outlet asset.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Competitor Product</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/FocusFiveGroup__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveGroup__c</fullName>
    <formula>aforza__Product__r.FocusFiveGroup__c</formula>
    <label>Focus 5 Group</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/FocusFiveProduct__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveProduct__c</fullName>
    <formula>aforza__Product__r.FocusFiveProduct__c</formula>
    <label>Focus 5 Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <formula>aforza__Product__r.PsProductEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of product.</description>
    <inlineHelpText>The type of product.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Still</fullName>
            </value>
            <value>
                <fullName>Sparkling</fullName>
            </value>
            <value>
                <fullName>Baby</fullName>
                <isActive>false</isActive>
                <label>Baby</label>
            </value>
            <value>
                <fullName>Beer, Wine &amp; Spirits</fullName>
                <isActive>false</isActive>
                <label>Beer, Wine &amp; Spirits</label>
            </value>
            <value>
                <fullName>Bins &amp; Fridges</fullName>
                <isActive>false</isActive>
                <label>Bins &amp; Fridges</label>
            </value>
            <value>
                <fullName>Bread &amp; Bakery</fullName>
                <isActive>false</isActive>
                <label>Bread &amp; Bakery</label>
            </value>
            <value>
                <fullName>Breakfast &amp; Cereal</fullName>
                <isActive>false</isActive>
                <label>Breakfast &amp; Cereal</label>
            </value>
            <value>
                <fullName>Brochures &amp; Handouts</fullName>
                <isActive>false</isActive>
                <label>Brochures &amp; Handouts</label>
            </value>
            <value>
                <fullName>Canned Goods &amp; Soups</fullName>
                <isActive>false</isActive>
                <label>Canned Goods &amp; Soups</label>
            </value>
            <value>
                <fullName>Cleaning Supplies</fullName>
                <isActive>false</isActive>
                <label>Cleaning Supplies</label>
            </value>
            <value>
                <fullName>Condiments/Spices &amp; Bake</fullName>
                <isActive>false</isActive>
                <label>Condiments/Spices &amp; Bake</label>
            </value>
            <value>
                <fullName>Cookies, Snacks &amp; Candy</fullName>
                <isActive>false</isActive>
                <label>Cookies, Snacks &amp; Candy</label>
            </value>
            <value>
                <fullName>Dairy, Eggs &amp; Cheese</fullName>
                <isActive>false</isActive>
                <label>Dairy, Eggs &amp; Cheese</label>
            </value>
            <value>
                <fullName>Deli &amp; Signature Cafe</fullName>
                <isActive>false</isActive>
                <label>Deli &amp; Signature Cafe</label>
            </value>
            <value>
                <fullName>Fixtures</fullName>
                <isActive>false</isActive>
                <label>Fixtures</label>
            </value>
            <value>
                <fullName>Flowers</fullName>
                <isActive>false</isActive>
                <label>Flowers</label>
            </value>
            <value>
                <fullName>Frozen Foods</fullName>
                <isActive>false</isActive>
                <label>Frozen Foods</label>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
                <isActive>false</isActive>
                <label>Fruits &amp; Vegetables</label>
            </value>
            <value>
                <fullName>Gondolas</fullName>
                <isActive>false</isActive>
                <label>Gondolas</label>
            </value>
            <value>
                <fullName>Grains, Pasta &amp; Sides</fullName>
                <isActive>false</isActive>
                <label>Grains, Pasta &amp; Sides</label>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
                <isActive>false</isActive>
                <label>Health &amp; Beauty</label>
            </value>
            <value>
                <fullName>International Cuisine</fullName>
                <isActive>false</isActive>
                <label>International Cuisine</label>
            </value>
            <value>
                <fullName>Meat &amp; Seafood</fullName>
                <isActive>false</isActive>
                <label>Meat &amp; Seafood</label>
            </value>
            <value>
                <fullName>Paper Products</fullName>
                <isActive>false</isActive>
                <label>Paper Products</label>
            </value>
            <value>
                <fullName>Personal Care &amp; Pharmacy</fullName>
                <isActive>false</isActive>
                <label>Personal Care &amp; Pharmacy</label>
            </value>
            <value>
                <fullName>Pet Care</fullName>
                <isActive>false</isActive>
                <label>Pet Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Product2/fields/FocusFiveGroup__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveGroup__c</fullName>
    <inlineHelpText>Please Insert Focus 5 Group Name for this product.</inlineHelpText>
    <label>Focus 5 Group</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/Product2/fields/FocusFiveProduct__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Pease check this field when the Product should be considered as Focus 5 Product. It will add this product to All DPs Outlet Assets. When the product is unchecked as Focus 5 Product it will be unchecked as Focus 5 Product or deleted if no orders from Outlet Assets.</inlineHelpText>
    <label>Focus 5 Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify a PS product, and used in the Audit filter on mobile</description>
    <inlineHelpText>Used to identify a PS product, and used in the Audit filter on mobile</inlineHelpText>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/OutletAssetServiceTest.cls
/**
 * Created by svatopluk.sejkora on 05.10.2022.
 */

@IsTest
private class OutletAssetServiceTest {
    @IsTest
    private static void testGetAccountsOutletAssets() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        Product2 prod1 = (Product2) TdfSObjectFactory.insertSObject(new Product2());
        Product2 prod2 = (Product2) TdfSObjectFactory.insertSObject(new Product2(StockKeepingUnit = 'uniqueSKU2'));


        TdfSObjectFactory.insertSObject(new aforza__Outlet_Asset__c(aforza__Account__c = acc.Id, aforza__Product__c = prod1.Id));
        TdfSObjectFactory.insertSObject(new aforza__Outlet_Asset__c(aforza__Account__c = acc.Id, aforza__Product__c = prod2.Id));

        Test.startTest();
        Map<Id, Map<Id, Date>> outlets = OutletAssetService.getAccountsOutletAssets(new Set<Id>{acc.Id});
        Test.stopTest();

        System.assertEquals(1, outlets.size());
        System.assertEquals(2, outlets.get(acc.Id).size());
    }

    @IsTest
    private static void testCreateOutletAsset() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        Product2 prod1 = (Product2) TdfSObjectFactory.insertSObject(new Product2());

        Test.startTest();
        aforza__Outlet_Asset__c outletAsset = OutletAssetService.createOutletAsset(acc.Id, prod1);
        Test.stopTest();

        System.assertEquals(acc.Id, outletAsset.aforza__Account__c);
        System.assertEquals(prod1.Id, outletAsset.aforza__Product__c);
        System.assertEquals(prod1.Name, outletAsset.aforza__Name__c);
        System.assertEquals('Product', outletAsset.aforza__Type__c);
    }

    @IsTest
    private static void testAddNewFocusProducts() {
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        Product2 prod1 = (Product2) TdfSObjectFactory.insertSObject(new Product2());

        Test.startTest();
        OutletAssetService.addNewOutletAssets(new Set<Id>{acc.Id}, new List<Product2>{prod1});
        Test.stopTest();

        List<aforza__Outlet_Asset__c> assets = [SELECT Id FROM aforza__Outlet_Asset__c WHERE aforza__Account__c = :acc.Id AND aforza__Product__c = :prod1.Id];
        System.assertEquals(1, assets.size());
    }

    @IsTest
    private static void testCreateOutletAssetsForAccounts() {
        // create NonStockis attribute category
        TdfSObjectFactory.insertSObject(new aforza__Attribute_Category__c());

        Test.startTest();
        TdfSObjectFactory.insertSObject(new Product2(FocusFiveProduct__c = true, FocusFiveGroup__c = 'GROUP'));
        Test.stopTest();
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        List<aforza__Outlet_Asset__c> assetsBefore = [SELECT Id FROM aforza__Outlet_Asset__c WHERE aforza__Account__c = :acc.Id];
        System.assertEquals(0, assetsBefore.size());

        List<aforza__Outlet_Asset__c> assetsToInsert =  OutletAssetService.createOutletAssetsForAccounts(new Set<Account>{acc}, AccountTriggerHandler.OutletAssetType.FOCUS);
        insert assetsToInsert;

        List<aforza__Outlet_Asset__c> assetsAfter = [SELECT Id FROM aforza__Outlet_Asset__c WHERE aforza__Account__c = :acc.Id];
        System.assertEquals(1, assetsAfter.size());
    }

    @IsTest
    private static void testCreateOutletAssetsForAccounts_PerfectScore() {
        TdfSObjectFactory.insertSObject(new Product2(PsProductEngland__c = true));
        Account acc = (Account) TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID));
        List<aforza__Outlet_Asset__c> assetsBefore = [SELECT Id FROM aforza__Outlet_Asset__c WHERE aforza__Account__c = :acc.Id];
        System.assertEquals(0, assetsBefore.size());

        Test.startTest();
        List<aforza__Outlet_Asset__c> assetsToInsert =  OutletAssetService.createOutletAssetsForAccounts(new Set<Account>{acc}, AccountTriggerHandler.OutletAssetType.PERFECT_SCORE);
        insert assetsToInsert;
        Test.stopTest();

        List<aforza__Outlet_Asset__c> assetsAfter = [SELECT Id FROM aforza__Outlet_Asset__c WHERE aforza__Account__c = :acc.Id];
        //One created in test, One created by default setting on account - perfectScoreEligibity = true
        System.assertEquals(2, assetsAfter.size());
    }
}