src/main/default/objects/aforza__Outlet_Asset__c/fields/BenchmarkDate__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkDate__c</fullName>
    <formula>null</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Benchmark Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/BenchmarkScore__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkScore__c</fullName>
    <inlineHelpText>Score of the first visit done within any Fiscal year.</inlineHelpText>
    <defaultValue>0</defaultValue>
    <label>Benchmark Score</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/BenchmarkService.cls
public with sharing class BenchmarkService {
    
    public static void resetOutletBenchmark(List<aforza__Outlet_Asset__c> outletAssets) {
        List<aforza__Outlet_Asset__c> assetsToUpdate= new List<aforza__Outlet_Asset__c>();
        for(aforza__Outlet_Asset__c oAsset: outletAssets) {
            oAsset.BenchmarkDate__c = null;
            oAsset.BenchmarkScore__c = 0;
            assetsToUpdate.add(oAsset);
        }
        update assetsToUpdate;
    }
}