src/main/default/objects/aforza__Outlet_Asset__c/fields/BenchmarkDate__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkDate__c</fullName>
    <formula>null</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Benchmark Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/BenchmarkScore__c.field-meta.xml
<CustomField>
    <fullName>BenchmarkScore__c</fullName>
    <inlineHelpText>Score of the first visit done within any Fiscal year.</inlineHelpText>
    <defaultValue>0</defaultValue>
    <label>Benchmark Score</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <formula>aforza__Product__r.PsProductEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductScotland__c.field-meta.xml
<CustomField>
    <fullName>PsProductScotland__c</fullName>
    <formula>aforza__Product__r.PsProductScotland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product Scotland</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify a PS product, and used in the Audit filter on mobile</description>
    <inlineHelpText>Used to identify a PS product, and used in the Audit filter on mobile</inlineHelpText>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/PsProductScotland__c.field-meta.xml
<CustomField>
    <fullName>PsProductScotland__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify a PS product, and used in the Audit filter on mobile</description>
    <inlineHelpText>Used to identify a PS product, and used in the Audit filter on mobile</inlineHelpText>
    <label>PS Product Scotland</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/ResetFeatureValuesBatchTest.cls
@IsTest
public class ResetFeatureValuesBatchTest {
    
    @IsTest
    public static void testBenchmarkResetOnOutletAsset() {
        // Create Data
        Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(
         	new Product2(PsProductEngland__c = true)
		);
        aforza__Outlet_Asset__c newAsset = (aforza__Outlet_Asset__c) TdfSObjectFactory.insertSObject(
			new aforza__Outlet_Asset__c(
                aforza__Product__c = newProduct.Id,
                BenchmarkDate__c = System.today(),
                BenchmarkScore__c = 10
            )
		);
        
        Test.startTest();
        ResetBenchmarkScheduler.scheduleBenchmarkReset();
        ResetFeatureValuesBatch rfv = new ResetFeatureValuesBatch(
            'SELECT Id FROM aforza__Outlet_Asset__c WHERE aforza__Product__r.PsProductEngland__c = true OR aforza__Product__r.PsProductScotland__c = true', 
            ResetFeatureValuesBatch.FEATURES.BENCHMARK
        );
        Database.executeBatch(rfv);
        Test.stopTest();
        
        aforza__Outlet_Asset__c oAsset = [SELECT BenchmarkDate__c, BenchmarkScore__c FROM aforza__Outlet_Asset__c WHERE Id = :newAsset.Id];
        System.assert(oAsset.BenchmarkDate__c == null, 'After Batch execution Benchmark Date values should be reset');
        System.assert(oAsset.BenchmarkScore__c == 0, 'After Batch execution Benchmark score values should be reset');
    }
}