src/main/default/objects/aforza__Outlet_Asset__c/fields/FocusFiveProduct__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveProduct__c</fullName>
    <formula>aforza__Product__r.FocusFiveProduct__c</formula>
    <label>Focus 5 Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/FocusFiveStatus__c.field-meta.xml
<CustomField>
    <fullName>FocusFiveStatus__c</fullName>
    <formula>IF (FocusFiveProduct__c,
CASE (
    aforza__Account__r.FieldSalesRegion__c,
				&quot;England North&quot;, IF($CustomMetadata.ProductSetting__mdt.OrgDefaultProductSettings.FocusFiveEngland__c + IF(ISBLANK(aforza__Purchase_Date__c), DATE(2022,01,01), aforza__Purchase_Date__c) &lt;= TODAY(), &quot;Lapsed&quot;, &quot;Not Lapsed&quot;),
				&quot;England South&quot;, IF($CustomMetadata.ProductSetting__mdt.OrgDefaultProductSettings.FocusFiveEngland__c + IF(ISBLANK(aforza__Purchase_Date__c), DATE(2022,01,01), aforza__Purchase_Date__c) &lt;= TODAY(), &quot;Lapsed&quot;, &quot;Not Lapsed&quot;),
				&quot;Scotland East&quot;, IF($CustomMetadata.ProductSetting__mdt.OrgDefaultProductSettings.FocusFiveScotland__c + IF(ISBLANK(aforza__Purchase_Date__c), DATE(2022,01,01), aforza__Purchase_Date__c) &lt;= TODAY(), &quot;Lapsed&quot;, &quot;Not Lapsed&quot;),
				&quot;Scotland West&quot;, IF($CustomMetadata.ProductSetting__mdt.OrgDefaultProductSettings.FocusFiveScotland__c + IF(ISBLANK(aforza__Purchase_Date__c), DATE(2022,01,01), aforza__Purchase_Date__c) &lt;= TODAY(), &quot;Lapsed&quot;, &quot;Not Lapsed&quot;),
				&quot;Unknown Sales Region&quot;
), &quot;Not Focus 5 Product&quot;)</formula>
    <label>Focus 5 Status</label>
    <type>Text</type>
</CustomField>

src/main/default/classes/ManageFocusAttributesBatch.cls
/**
 * Created by svatopluk.sejkora on 04.10.2022.
 */

public with sharing class ManageFocusAttributesBatch implements Database.Batchable<SObject>, Schedulable {

    public Iterable<SObject> start(Database.BatchableContext batchableContext) {
        String query = 'SELECT Id, aforza__Product_Code__c, FocusFiveStatus__c, aforza__Account__c, ' +
                'aforza__Outlet_Asset__c.aforza__Product_SKU__c ' +
                'FROM aforza__Outlet_Asset__c ' +
                'WHERE FocusFiveProduct__c = TRUE ' +
                'ORDER BY aforza__Account__c ASC';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext batchableContext, List<aforza__Outlet_Asset__c> outletAssets) {
        AttributesService.updateFocusAttributes(outletAssets);
    }

    public void finish(Database.BatchableContext param1) {
    }

    public void execute(SchedulableContext schedulableContext) {
        Database.executeBatch(this);
    }

}