src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductEngland__c.field-meta.xml
<CustomField>
    <fullName>PsProductEngland__c</fullName>
    <formula>aforza__Product__r.PsProductEngland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product England</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PsProductScotland__c.field-meta.xml
<CustomField>
    <fullName>PsProductScotland__c</fullName>
    <formula>aforza__Product__r.PsProductScotland__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PS Product Scotland</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/classes/ResetBenchmarkController.cls
public with sharing class ResetBenchmarkController {

    @AuraEnabled
    public static void resetOutletBenchmarkByAccount(String accountId) {
        try {
            if( String.isNotEmpty(accountId) ) {
                BenchmarkService.resetOutletBenchmark(
                    [SELECT Id FROM aforza__Outlet_Asset__c 
                     WHERE aforza__Account__c = :accountId 
                       AND (aforza__Product__r.PsProductEngland__c = true OR aforza__Product__r.PsProductScotland__c = true)]
                );
            } else {
                throw new IllegalArgumentException('Account Id cannot be empty, as it is used to load specific Outlet Assets');
            }
        } catch (Exception e) {
            throw PopulateAuraHandledException.newMessageException(e.getMessage());
        }
    }
}