src/main/default/objects/aforza__Inventory__c/aforza__Inventory__c.object-meta.xml
<CustomObject>
    <description>A building or vehicle used to store products.</description>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Inventory_Product__c/fields/JdeStockQuantity__c.field-meta.xml
<CustomField>
    <fullName>JdeStockQuantity__c</fullName>
    <description>Updated automatically via JDE System Integration.</description>
    <defaultValue>0</defaultValue>
    <label>JDE Stock Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Inventory_Product__c/fields/NonSalableStock__c.field-meta.xml
<CustomField>
    <fullName>NonSalableStock__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Updated automatically via JDE System Integration.</description>
    <label>Non-Salable Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Inventory_Product__c/fields/PickingLocation__c.field-meta.xml
<CustomField>
    <fullName>PickingLocation__c</fullName>
    <inlineHelpText>Picking location for this inventory product</inlineHelpText>
    <label>Picking Location</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/InventoryProductCalculationBatch.cls
public with sharing class InventoryProductCalculationBatch implements Database.Batchable < SObject > , Schedulable {

    public Iterable < SObject > start(Database.BatchableContext batchableContext) {
        // load all recurring records that has been modified
        String query = 'SELECT aforza__Stock_Quantity__c,Id,JDEStockQuantity__c, NonSalableStock__c,  ' +
            'Name, PickingLocation__c, aforza__Inventory__c,aforza__Product__c FROM aforza__Inventory_Product__c';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext batchableContext, List < aforza__Inventory_Product__c > inventoryProducts) {

        InventoryProductService.updateInventoryStock(inventoryProducts);
    }

    public void finish(Database.BatchableContext param1) {

    }

    public void execute(SchedulableContext schedulableContext) {
        Database.executeBatch(this);
    }


}