src/main/default/objects/aforza__Inventory__c/aforza__Inventory__c.object-meta.xml
<CustomObject>
    <description>A building or vehicle used to store products.</description>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Inventory__c/fields/InventoryCode__c.field-meta.xml
<CustomField>
    <fullName>InventoryCode__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>InventoryCode</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/InventorySetting__mdt/fields/DepotCode__c.field-meta.xml
<CustomField>
    <fullName>DepotCode__c</fullName>
    <label>DepotCode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/InventorySetting__mdt/fields/InventoryCode__c.field-meta.xml
<CustomField>
    <fullName>InventoryCode__c</fullName>
    <label>InventoryCode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/InventoryService.cls
/**
 * @description       : Service class for inventory
 **/

public with sharing class InventoryService {

    public static Map<String, Id> getDepotInventoryMapping(){
            Map<String, String> depotAndInventoryCodeMap = new Map<String, String>();
            Map<String, Id> inventoryCodeAndInventoryIdMap = new Map<String, Id>();
        	Map<String, Id> depotCodeAndInventoryIdMap = new Map<String, Id>();
            for (InventorySetting__mdt setting : InventorySetting__mdt.getAll().values()) {
                    depotAndInventoryCodeMap.put(setting.DepotCode__c, setting.InventoryCode__c);
            }
        	List<aforza__Inventory__c> inventoryList = [SELECT Id, InventoryCode__c FROM aforza__Inventory__c WHERE InventoryCode__c IN :depotAndInventoryCodeMap.values()];
        	
        	if(!inventoryList.isEmpty()){
            	for(aforza__Inventory__c inv : inventoryList){
                	inventoryCodeAndInventoryIdMap.put(inv.InventoryCode__c, inv.Id);
            	}
                for(String depotCode : depotAndInventoryCodeMap.keySet()){
                    if(inventoryCodeAndInventoryIdMap.containsKey(depotAndInventoryCodeMap.get(depotCode))){
                    	depotCodeAndInventoryIdMap.put(depotCode, inventoryCodeAndInventoryIdMap.get(depotAndInventoryCodeMap.get(depotCode)));
                	}
                }    
            }
			return depotCodeAndInventoryIdMap;
    }
}