src/main/default/objects/aforza__Inventory__c/aforza__Inventory__c.object-meta.xml
<CustomObject>
    <description>A building or vehicle used to store products.</description>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Inventory_Product__c/fields/JdeStockQuantity__c.field-meta.xml
<CustomField>
    <fullName>JdeStockQuantity__c</fullName>
    <description>Updated automatically via JDE System Integration.</description>
    <defaultValue>0</defaultValue>
    <label>JDE Stock Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Inventory_Product__c/fields/NonSalableStock__c.field-meta.xml
<CustomField>
    <fullName>NonSalableStock__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Updated automatically via JDE System Integration.</description>
    <label>Non-Salable Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/PushedtoJde__c.field-meta.xml
<CustomField>
    <fullName>PushedtoJde__c</fullName>
    <description>Updated automatically via JDE System Integration.</description>
    <defaultValue>false</defaultValue>
    <label>Pushed to JDE?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Order/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A linked Invoice.</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>aforza__Invoice__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/InventoryProductService.cls
public class InventoryProductService {

	public static void updateInventoryStock(List <aforza__Inventory_Product__c> inventoryProducts) {
	  Decimal totalQuantity;
	  Decimal stockUpdate;
  
	  List <aforza__Inventory_Product__c> inventoryProductsToUpdate = new List <aforza__Inventory_Product__c> ();
	  Map <String, Decimal> mapInventoryIdAndProductQuantitySum = new Map <String, Decimal> ();
	  
	  Set <ID> inventoryProductsId = new Set<Id>();
	  for (aforza__Inventory_Product__c inventoryProduct: inventoryProducts){
	  	inventoryProductsId.add(inventoryProduct.aforza__Product__c);
	}
	  
	   AggregateResult[] quantityInOrders = [SELECT Order.aforza__Inventory__c Inventory, Product2Id product, sum(quantity) summ FROM OrderItem WHERE 
	   Order.RecordType.DeveloperName IN: OrderService.RECORD_TYPES_FOR_STOCK_UPDATE AND Product2Id IN:inventoryProductsId AND ((Order.Status NOT IN: OrderService.UNFULFILLED_ORDER_STATUS) OR
	   (Order.Status = 'Receipted' AND Order.Invoice__r.PushedtoJde__c = FALSE))
           GROUP BY Order.aforza__Inventory__c, Product2Id
	  ];
  
  
	  for (AggregateResult aggResult: quantityInOrders) {
		mapInventoryIdAndProductQuantitySum.put((String) aggResult.get('inventory') + (String) aggResult.get('product'), (Decimal) aggResult.get('summ'));
	  }
  
	  for (aforza__Inventory_Product__c aip: inventoryProducts) {
		String thiskey = String.valueOf(aip.aforza__Inventory__c) + String.valueOf(aip.aforza__Product__c);
  
		  totalQuantity = mapInventoryIdAndProductQuantitySum.get(thisKey);
		if (totalQuantity == null) {
		  totalQuantity = 0;
		}
  
		Decimal JdeStock = aip.JdeStockQuantity__c == null ? 0 : aip.JdeStockQuantity__c;
		Decimal NonSalableStock = aip.NonSalableStock__c == null ? 0 : aip.NonSalableStock__c;
  
		stockUpdate = JdeStock - (NonSalableStock + totalQuantity);
  
		aip.aforza__Stock_Quantity__c = stockUpdate;
		inventoryProductsToUpdate.add(aip);
	  }
  
	  update inventoryProductsToUpdate;
	}
  
  }