src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectScoreProduct__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perfect Score Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectScoreRate__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreRate__c</fullName>
    <label>Perfect Score Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectScoreWeight__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreWeight__c</fullName>
    <label>Perfect Score Weight</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/PerfectStoreMet__c.field-meta.xml
<CustomField>
    <fullName>PerfectStoreMet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the perfect store condition is met</description>
    <inlineHelpText>Indicates if the perfect store condition is met</inlineHelpText>
    <label>Perfect Store Met?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Audit_Asset__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>IF(PsProductScotland__c = true, PsRateScotland__c * PsWeightScotland__c, IF(PsProductEngland__c = true, PsRateEngland__c * PsWeightEngland__c, 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectScoreProduct__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreProduct__c</fullName>
    <formula>IF(aforza__Account__r.ShippingState = &quot;England&quot;, aforza__Product__r.PsProductEngland__c, IF(aforza__Account__r.ShippingState = &quot;Scotland&quot;, aforza__Product__r.PsProductScotland__c, false))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Perfect Score Product</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectScoreRate__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreRate__c</fullName>
    <formula>IF(aforza__Account__r.ShippingState = &quot;England&quot;, aforza__Product__r.PsRateEngland__c, IF(aforza__Account__r.ShippingState = &quot;Scotland&quot;, aforza__Product__r.PsRateScotland__c, 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Perfect Score Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectScoreWeight__c.field-meta.xml
<CustomField>
    <fullName>PerfectScoreWeight__c</fullName>
    <formula>IF(aforza__Account__r.ShippingState = &quot;England&quot;, aforza__Product__r.PsWeightEngland__c, IF(aforza__Account__r.ShippingState = &quot;Scotland&quot;, aforza__Product__r.PsWeightScotland__c, 0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Perfect Score Weight</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/PerfectStoreMet__c.field-meta.xml
<CustomField>
    <fullName>PerfectStoreMet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the perfect store condition is met</description>
    <inlineHelpText>Indicates if the perfect store condition is met</inlineHelpText>
    <label>Perfect Store Met?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/aforza__Outlet_Asset__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>IF (PerfectStoreMet__c = TRUE, PerfectScoreRate__c * PerfectScoreWeight__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/main/default/classes/AuditAssetTriggerHandler.cls
/**
 * Created by svatopluk.sejkora on 03.11.2022.
 */

public with sharing class AuditAssetTriggerHandler {

    public static void populatePerfectScoreAttributes(List<aforza__Audit_Asset__c> auditAssets) {
        Set<Id> outletAssetIdsToGetDataFrom = new Set<Id>();
        List<aforza__Audit_Asset__c> assetsToUpdate = new List<aforza__Audit_Asset__c>();
        for (aforza__Audit_Asset__c auditAsset : auditAssets) {
            System.debug('outlet asset link' + auditAsset.aforza__Outlet_Asset__c);
            System.debug('perfect score met' + auditAsset.PerfectStoreMet__c);
            if (auditAsset.aforza__Outlet_Asset__c != null && auditAsset.PerfectStoreMet__c == true) {
                outletAssetIdsToGetDataFrom.add(auditAsset.aforza__Outlet_Asset__c);
                assetsToUpdate.add(auditAsset);
            }
        }

        Map<Id, aforza__Outlet_Asset__c> outletAssetMap = fetchOutletAssets(outletAssetIdsToGetDataFrom);
        System.debug('outlet asset selected' + outletAssetMap);

        for (aforza__Audit_Asset__c auditToUpdate : assetsToUpdate) {
            aforza__Outlet_Asset__c linkedOutletAsset = outletAssetMap?.get(auditToUpdate.aforza__Outlet_Asset__c);
            auditToUpdate.PerfectScoreRate__c = linkedOutletAsset.PerfectScoreRate__c;
            auditToUpdate.PerfectScoreProduct__c = linkedOutletAsset.PerfectScoreProduct__c;
            auditToUpdate.PerfectScoreWeight__c = linkedOutletAsset.PerfectScoreWeight__c;
            auditToUpdate.Score__c = linkedOutletAsset.Score__c;
        }
    }


    private static Map<Id, aforza__Outlet_Asset__c> fetchOutletAssets(Set<Id> outletAssetIds) {
        return new Map<Id, aforza__Outlet_Asset__c>([
                SELECT Id, PerfectScoreProduct__c, PerfectScoreRate__c, PerfectScoreWeight__c, Score__c
                FROM aforza__Outlet_Asset__c
                WHERE Id IN :outletAssetIds
        ]);
    }
}