src/main/default/objects/OrderSetting__mdt/OrderSetting__mdt.object-meta.xml
<CustomObject>
    <label>Order Setting</label>
    <pluralLabel>Order Settings</pluralLabel>
</CustomObject>

src/main/default/objects/OrderSetting__mdt/fields/CompletedOrderStatuses__c.field-meta.xml
<CustomField>
    <fullName>CompletedOrderStatuses__c</fullName>
    <label>Completed Order Statuses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OrderSetting__mdt/fields/RTsToCreateInvoice__c.field-meta.xml
<CustomField>
    <fullName>RTsToCreateInvoice__c</fullName>
    <label>RTs to Create Invoice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/OrderSetting__mdt/fields/RTsToUpdateAccOnOrderCompletion__c.field-meta.xml
<CustomField>
    <fullName>RTsToUpdateAccOnOrderCompletion__c</fullName>
    <label>RTs to Update Acc on Order Completion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/OrderService.cls
/**
 * Created by magdalena.stanciu on 19.09.2022.
 */

public with sharing class OrderService {
    public static final OrderSetting__mdt SETTINGS {
        get {
            if (SETTINGS == null) {
                SETTINGS = OrderSetting__mdt.getInstance('OrgDefaultOrderSettings');
            }
            return SETTINGS;
        }
        set;
    }

    public static final Set<String> COMPLETED_ORDER_STATUSES {
        get {
            if (COMPLETED_ORDER_STATUSES == null) {
                COMPLETED_ORDER_STATUSES = new Set<String>(SETTINGS.CompletedOrderStatuses__c.split(','));
            }
            return COMPLETED_ORDER_STATUSES;
        }
        set;
    }

    public static final Set<String> RECORD_TYPES_TO_UPDATE_ACCOUNT_ON_ORDER_COMPLETION {
        get {
            if (RECORD_TYPES_TO_UPDATE_ACCOUNT_ON_ORDER_COMPLETION == null) {
                RECORD_TYPES_TO_UPDATE_ACCOUNT_ON_ORDER_COMPLETION = new Set<String>(SETTINGS.RTsToUpdateAccOnOrderCompletion__c.split(','));
            }
            return RECORD_TYPES_TO_UPDATE_ACCOUNT_ON_ORDER_COMPLETION;
        }
        set;
    }

    public static final Set<String> RECORD_TYPES_TO_CREATE_INVOICE {
        get {
            if (RECORD_TYPES_TO_CREATE_INVOICE == null) {
                RECORD_TYPES_TO_CREATE_INVOICE = new Set<String>(SETTINGS.RTsToCreateInvoice__c.split(','));
            }
            return RECORD_TYPES_TO_CREATE_INVOICE;
        }
        set;
    }

    public static Boolean isOrderCompleted(String orderStatus) {
        return COMPLETED_ORDER_STATUSES.contains(orderStatus);
    }

    public static Boolean orderTypeCountsTowardsAccountLastOrderDate(Id orderRecordTypeId) {
        return RECORD_TYPES_TO_UPDATE_ACCOUNT_ON_ORDER_COMPLETION.contains(RecordTypes.ORDER_RT_INFO_BY_ID?.get(orderRecordTypeId)?.getDeveloperName());
    }

    public static Boolean orderTypeRequiresInvoiceCreation(Id orderRecordTypeId) {
        return RECORD_TYPES_TO_CREATE_INVOICE.contains(RecordTypes.ORDER_RT_INFO_BY_ID?.get(orderRecordTypeId)?.getDeveloperName());
    }

    public static void updateLastOrderDateAndStatusOnParentAccount(List<Order> newOrders) {
        Set<Id> relatedAccountIds = new Set<Id>();
        for (Order newOrder : newOrders) {
            relatedAccountIds.add(newOrder.AccountId);
        }
       AccountService.updateLastOrderDateAndAccountStatus(relatedAccountIds);
    }
}