src/main/default/objects/aforza__Route__c/fields/LoadId__c.field-meta.xml
<CustomField>
    <fullName>LoadId__c</fullName>
    <description>Used only on background to link proper locations and then route back to load. Used only when automation logic for route creation is ran.</description>
    <externalId>true</externalId>
    <label>Load Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/default/objects/aforza__Visit__c/aforza__Visit__c.object-meta.xml
<CustomObject>
    <description>A purposeful on-site meeting at an account.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>VIS-{00000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Visit__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the visit is taking place at.</description>
    <inlineHelpText>The account the visit is taking place at.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the visit.</description>
    <inlineHelpText>The current status of the visit.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Ring Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of visit.</description>
    <inlineHelpText>The type of visit.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outlet Visit</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
            <value>
                <fullName>Video Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/Load__c/Load__c.object-meta.xml
<CustomObject>
    <label>Load</label>
    <nameField>
        <label>Load ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Load__c/fields/CreateRoute__c.field-meta.xml
<CustomField>
    <fullName>CreateRoute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field controlling when a Route and visits should be created. Logic will be triggered once, when the field is set to true. This field will be set to true automatically when all orders linked to the load are set to &quot;Pending Deliver&quot;.</description>
    <label>Create Route</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Load__c/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DepotValues</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Load__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Load__c/fields/DriverFullName__c.field-meta.xml
<CustomField>
    <fullName>DriverFullName__c</fullName>
    <description>Populating full name of the driver to be used in dynamic input lookup component</description>
    <formula>Driver__r.FirstName + &apos; &apos; +  Driver__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver Full Name</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Load__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>aforza__Route__c</referenceTo>
    <relationshipLabel>Loads</relationshipLabel>
    <relationshipName>Loads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <description>Used for email templates.</description>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

src/main/default/objects/Order/fields/DeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDate__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/Order/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DepotValues</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Order/fields/Load__c.field-meta.xml
<CustomField>
    <fullName>Load__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Load</label>
    <referenceTo>Load__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <formula>MID( Grid__c , 3, 2)</formula>
    <label>Route</label>
    <type>Text</type>
</CustomField>

src/main/default/globalValueSets/DepotValues.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>D</fullName>
        <label>Dagenham</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>Wednesbury</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>Moston</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Scotland</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cranks</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>Bentleys</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Murdens</label>
    </customValue>
    <customValue>
        <fullName>Z</fullName>
        <label>Menzies</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Blacks</label>
    </customValue>
    <customValue>
        <fullName>Cumbernauld</fullName>
        <isActive>false</isActive>
        <label>Cumbernauld</label>
    </customValue>
    <masterLabel>Depot Values</masterLabel>
</GlobalValueSet>

src/main/default/classes/LoadTriggerHandlerTest.cls
/**
 * Created by svatopluk.sejkora on 20.10.2022.
 */

@IsTest
private class LoadTriggerHandlerTest {

    @IsTest
    private static void testGetNeededDepotCodesAndLabels() {
        Test.startTest();
        Map<String, String> labelsWithCode = LoadTriggerHandler.getNeededDepotCodesAndLabels();
        Test.stopTest();

        Assert.isTrue(labelsWithCode.size() > 0);
    }

    @IsTest
    private static void testCheckIfTerritoryExistsCreateNewIfNot() {
        Test.startTest();
        Map<String, Id> territories = LoadTriggerHandler.checkIfTerritoryExistsCreateNewIfNot();
        Test.stopTest();

        Map<String, String> labelsWithCode = LoadTriggerHandler.getNeededDepotCodesAndLabels();

        Assert.areEqual(labelsWithCode.size(), territories.size());
    }

    @IsTest
    private static void testPrepareLoadToOrdersMap() {
        // prepare orders and assign them to load
        Load__c load = (Load__c) TdfSObjectFactory.insertSObject(new Load__c());
        TdfSObjectFactory.insertSObjects(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID,
                Load__c = load.Id, Status = 'Pending Delivery'), 5);

        Test.startTest();
        Map<Id, List<Order>> loadToOrders = LoadTriggerHandler.prepareLoadToOrdersMap(new Set<Id>{
                load.Id
        });
        Test.stopTest();

        Assert.areEqual(1, loadToOrders.size());
        Assert.areEqual(5, loadToOrders.get(load.Id).size());
    }

    @IsTest
    private static void testMapDataToLoad() {
        Load__c load = (Load__c) TdfSObjectFactory.insertSObject(new Load__c());
        Test.startTest();
        Load__c loadMemory = LoadTriggerHandler.mapDataToLoad(load.Id);
        Test.stopTest();

        Assert.areEqual(load.Id, loadMemory.Id);
        Assert.areEqual(load.Id, loadMemory.Route__r.LoadId__c);
    }

    @IsTest
    private static void testMapDataToTask() {
        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID));

        Test.startTest();
        Task task = LoadTriggerHandler.mapDataToTask(order);
        Test.stopTest();

        Assert.areEqual(order.Id, task.aforza__Order__c);
        Assert.areEqual('Deliver Order', task.Subject);
        Assert.areEqual('Not Started', task.Status);
        Assert.areEqual('Order', task.aforza__Type__c);
        Assert.areEqual('High', task.Priority);
        Assert.areEqual(1, task.aforza__Sequence__c);
        Assert.areEqual(order.Id, task.WhatId);
    }

    @IsTest
    private static void testMapDataToVisit() {
        Load__c load = (Load__c) TdfSObjectFactory.insertSObject(new Load__c(DeliveryDate__c = System.today()));
        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID, Load__c = load.Id));

        Order orderWithNeededData = [
                SELECT Id, Load__c, AccountId, Load__r.Driver__c, Load__r.DeliveryDate__c,
                        Load__r.Depot__c, Load__r.Name, Load__r.DriverFullName__c, AccountName__c
                FROM Order
        ][0];

        Test.startTest();
        aforza__Visit__c visit = LoadTriggerHandler.mapDataToVisit(orderWithNeededData);
        Test.stopTest();

        Assert.areEqual(RecordTypes.VISIT_DIRECT_VISIT_ID, visit.RecordTypeId);
        Assert.areEqual('Outlet Visit', visit.aforza__Type__c);
        Assert.areEqual(orderWithNeededData.AccountId, visit.aforza__Account__c);
        Assert.areEqual(orderWithNeededData.Load__r.Driver__c, visit.aforza__Owner__c);
        Assert.areEqual('Not Started', visit.aforza__Status__c);
        Assert.areEqual(System.today(), visit.aforza__Planned_Time__c.date());
        Assert.areEqual(System.today(), visit.aforza__Planned_End_Time__c.date());
    }

    @IsTest
    private static void testMapDataToRouteLocation() {
        Integer count = 1;
        Load__c load = (Load__c) TdfSObjectFactory.insertSObject(new Load__c());
        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID, Load__c = load.Id));

        Test.startTest();
        aforza__Route_Location__c location = LoadTriggerHandler.mapDataToRouteLocation(order, load.Id, count);
        Test.stopTest();

        Assert.areEqual(order.AccountId, location.aforza__Account__c);
        Assert.areEqual(1, location.aforza__Distance_From_Last_Location__c);
        Assert.areEqual(900, location.aforza__Duration_From_Last_Location__c);
        Assert.areEqual(count, location.aforza__Sequence__c);
    }

    @IsTest
    private static void testMapDataToRoute() {
        Load__c load = (Load__c) TdfSObjectFactory.insertSObject(new Load__c());
        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID, Load__c = load.Id));
        Map<String, Id> territories = LoadTriggerHandler.checkIfTerritoryExistsCreateNewIfNot();
        Order orderWithNeededData = [
                SELECT Id, Load__c, AccountId, Load__r.Driver__c, Load__r.DeliveryDate__c,
                        Load__r.Depot__c, Load__r.Name, Load__r.DriverFullName__c, AccountName__c
                FROM Order
        ][0];

        Test.startTest();
        aforza__Route__c route = LoadTriggerHandler.mapDataToRoute(orderWithNeededData, territories, load.Id);
        Test.stopTest();

        Assert.areEqual(orderWithNeededData.Load__r.Name + ' - ' + orderWithNeededData.Load__r.DriverFullName__c, route.Name);
        Assert.areEqual('Active', route.aforza__Status__c);
        Assert.areEqual(territories.get('M'), route.aforza__Route_Territory__c);
        Assert.areEqual(load.Id, route.LoadId__c);
    }

    @IsTest
    private static void testUpdateDriver() {
        User newDriver = (User) TdfSObjectFactory.insertSObject(new User());

        Test.startTest();
        Load__c load = (Load__c) TdfSObjectFactory.insertSObject(new Load__c(CreateRoute__c = false));
        TdfSObjectFactory.insertSObjects(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID,
                Load__c = load.Id, Status = 'Pending Delivery'), 5);

        load.CreateRoute__c = true;
        update load;
        // update values
        load.Driver__c = newDriver.Id;
        update load;
        Test.stopTest();

        aforza__Route__c updatedRoute = [SELECT Id, Name FROM aforza__Route__c][0];

        Assert.isTrue(updatedRoute.Name.contains(newDriver.LastName));
        Assert.isTrue(updatedRoute.Name.contains(newDriver.FirstName));
    }

    @IsTest
    private static void testCreateRouteAndVisitsAndTasks() {
        Load__c load = (Load__c) TdfSObjectFactory.insertSObject(new Load__c(CreateRoute__c = false));
        TdfSObjectFactory.insertSObjects(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID,
                Load__c = load.Id, Status = 'Pending Delivery'), 5);

        Test.startTest();
        load.CreateRoute__c = true;
        update load;
        Test.stopTest();

        // check for route
        List<aforza__Route__c> routes = [SELECT Id FROM aforza__Route__c];
        Assert.isTrue(routes.size() == 1, 'There should be 1 route created');

        // check for location
        List<aforza__Route_Location__c> locations = [SELECT Id FROM aforza__Route_Location__c];
        System.debug('locations: ' + locations.size());
        Assert.isTrue(locations.size() == 1, 'There should be 1 location created');

        // check for visits
        List<aforza__Visit__c> visits = [SELECT Id FROM aforza__Visit__c];
        System.debug('visits: ' + visits.size());
        Assert.isTrue(visits.size() == 1, 'There should be 1 visit created');

        // check for tasks
        List<Task> tasks = [SELECT Id FROM Task];
        System.debug('tasks: ' + visits.size());
        Assert.isTrue(tasks.size() == 5, 'There should be 5 tasks created');

    }

}