src/main/default/objects/aforza__Recurring_Record__c/aforza__Recurring_Record__c.object-meta.xml
<CustomObject>
    <description>An object that controls when a record recurs.</description>
    <label>Recurring Record</label>
    <nameField>
        <label>Recurring Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Recurring_Record__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Account with Record Type of &quot;Outlet&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Outlet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Records</relationshipLabel>
    <relationshipName>Recurring_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Frequency__c.field-meta.xml
<CustomField>
    <fullName>aforza__Frequency__c</fullName>
    <description>The frequency at which this recurring record should happen.</description>
    <inlineHelpText>The frequency at which this recurring record should happen.</inlineHelpText>
    <label>Frequency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W</fullName>
                <label>Week-ly</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>Fortnightly</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1 fortnightly cycle</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Month-ly</label>
            </value>
            <value>
                <fullName>Annually</fullName>
                <isActive>false</isActive>
                <label>Annually</label>
            </value>
            <value>
                <fullName>Bi-Monthly</fullName>
                <isActive>false</isActive>
                <label>Bi-Monthly</label>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
                <isActive>false</isActive>
                <label>Bi-Weekly</label>
            </value>
            <value>
                <fullName>Daily</fullName>
                <isActive>false</isActive>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
                <isActive>false</isActive>
                <label>Quarterly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Number_Of_Recurrences__c.field-meta.xml
<CustomField>
    <fullName>aforza__Number_Of_Recurrences__c</fullName>
    <description>The number of recurrences the record should recur.</description>
    <inlineHelpText>The number of recurrences the record should recur.</inlineHelpText>
    <label>Number Of Recurrences</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of recurring record.</description>
    <inlineHelpText>The type of recurring record.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/CallDayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>CallDayOfWeek__c</fullName>
    <label>Call Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Date of the first visit planned for this recurrence.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/Call_Priority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <description>A call priority selection.</description>
    <masterLabel>Call Priority</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/WeekDays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Monday</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Tuesday</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Wednesday</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Thursday</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Friday</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Error</label>
    </customValue>
    <masterLabel>Week Days</masterLabel>
</GlobalValueSet>

src/main/default/classes/TdfAforzaRecurringRecordTemplate.cls
/**
 * Class provides functionality for creating default Account in test methods.
 *
 * Do not use this class directly.
 * Class is initialized in TDF_SObjectTemplateFactory and all its functionality is used through TDF_SObjectFactory.
 *
 * @see TdfSObjectFactory
 * @see TdfSObjectTemplate
 * @see TdfSObjectTemplateFactory
 *
 * @author  Svata Sejkoda
 * @date    2022-06-02
 *
 */
@IsTest
public with sharing class TdfAforzaRecurringRecordTemplate extends TdfSObjectTemplate {
    private Id accountId;

    /**
     * Instance is created dynamically. This method compensates a constructor.
     *
     * @author  Svata Sejkoda
     * @date    2022-06-02
     *
     */
    public override void init() {
        aforza__Recurring_Record__c userDefinedRecurringRecord = (aforza__Recurring_Record__c) userDefinedSObject;

        if (userDefinedRecurringRecord.Account__c == null) {
            accountId = TdfSObjectFactory.insertSObject(new Account(RecordTypeId = RecordTypes.ACCOUNT_OUTLET_ID)).Id;
        }
    }

    /**
     * Creates a template SObject. Every call returns a new instance.
     *
     * Because this method can be called multiple times, all operations as DML or SOQL has to be done in init().
     *
     * @return template with contact record
     *
     * @author  Svata Sejkora
     * @date    2021-11-01
     *
     */
    protected override SObject createTemplateSObject() {
        aforza__Recurring_Record__c template = new aforza__Recurring_Record__c(
                Name = 'My test record',
                Account__c = accountId,
                aforza__Type__c = RecurringRecordService.CALL_SETTINGS.CallType__c,
                Status__c = RecurringRecordService.CALL_SETTINGS.CallStatus__c,
                aforza__Frequency__c = 'W',
                StartDate__c = Date.parse('05/09/2022'),
                Priority__c = 'P1',
                CallDayOfWeek__c = '1',
                aforza__Number_Of_Recurrences__c = 12,
                OwnerId = UserInfo.getUserId()
        );

        return template;
    }
}