src/main/default/objects/aforza__Recurring_Record__c/aforza__Recurring_Record__c.object-meta.xml
<CustomObject>
    <description>An object that controls when a record recurs.</description>
    <label>Recurring Record</label>
    <nameField>
        <label>Recurring Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Recurring_Record__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Account with Record Type of &quot;Outlet&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Outlet</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring Records</relationshipLabel>
    <relationshipName>Recurring_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Last_Recurrence_Date__c.field-meta.xml
<CustomField>
    <fullName>aforza__Last_Recurrence_Date__c</fullName>
    <description>The date for the last recurring record to be scheduled on.</description>
    <inlineHelpText>The date for the last recurring record to be scheduled on.</inlineHelpText>
    <label>Last Recurrence Date</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of recurring record.</description>
    <inlineHelpText>The type of recurring record.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/CallDayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>CallDayOfWeek__c</fullName>
    <label>Call Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WeekDays</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/DaysBetweenRecurrence__c.field-meta.xml
<CustomField>
    <fullName>DaysBetweenRecurrence__c</fullName>
    <formula>CASE(
				aforza__Frequency__c,
				&apos;W&apos;, 7, 
				&apos;F&apos;, 14,
				&apos;M&apos;, 28,
				0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Number of days calculated from frequency: W - 7, F - 14, M - 28</inlineHelpText>
    <label>Days Between Recurrence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_Priority</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <inlineHelpText>Date of the first visit planned for this recurrence.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/main/default/objects/aforza__Recurring_Record__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Visit__c/aforza__Visit__c.object-meta.xml
<CustomObject>
    <description>A purposeful on-site meeting at an account.</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>VIS-{00000000}</displayFormat>
        <label>Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Visit__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the visit is taking place at.</description>
    <inlineHelpText>The account the visit is taking place at.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the visit.</description>
    <inlineHelpText>The current status of the visit.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Ring Back</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Visit__c/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of visit.</description>
    <inlineHelpText>The type of visit.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outlet Visit</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Customer Meeting</fullName>
            </value>
            <value>
                <fullName>Phone Call</fullName>
            </value>
            <value>
                <fullName>Video Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/CallRecurrenceSetting__mdt/CallRecurrenceSetting__mdt.object-meta.xml
<CustomObject>
    <description>Keeps settings used for creation of visits.</description>
    <label>Call Recurrence Setting</label>
    <pluralLabel>Call Recurrence Settings</pluralLabel>
</CustomObject>

src/main/default/objects/CallRecurrenceSetting__mdt/fields/GenerateVisitsForNextAmountOfDays__c.field-meta.xml
<CustomField>
    <fullName>GenerateVisitsForNextAmountOfDays__c</fullName>
    <inlineHelpText>Please insert number of days that the planed visits should be generated for.</inlineHelpText>
    <label>Generate Visits For Next Amount Of Days</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/globalValueSets/Call_Priority.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <description>A call priority selection.</description>
    <masterLabel>Call Priority</masterLabel>
</GlobalValueSet>

src/main/default/globalValueSets/WeekDays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Monday</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Tuesday</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>Wednesday</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>Thursday</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Friday</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Error</label>
    </customValue>
    <masterLabel>Week Days</masterLabel>
</GlobalValueSet>

src/main/default/classes/VisitCallService.cls
/**
 * Created by svatopluk.sejkora on 12.09.2022.
 */

public without sharing class VisitCallService {

    @TestVisible
    private static final CallRecurrenceSetting__mdt CALL_SETTINGS {
        get {
            if (CALL_SETTINGS == null) {
                CALL_SETTINGS = CallRecurrenceSetting__mdt.getInstance('OrgDefaultCallSettings');
            }
            return CALL_SETTINGS;
        }
        set;
    }

    public static void manageVisitCalls(List<aforza__Recurring_Record__c> recurringRecords) {
        // always look for items to delete, and delete anything in future.
        Date actualDate = System.today();
        List<aforza__Recurring_Record__c> filteredRecurringRecords = filterRecurringRecordsForVisitDeletion(recurringRecords);
        deleteFutureCalls(filteredRecurringRecords, actualDate);

        // recreate all visits for each recurring record from now on
        List<aforza__Visit__c> visits = createNewCalls(recurringRecords, actualDate);
        insert visits;
        determineLastVisitForEachAccount(visits);
    }

    private static List<aforza__Recurring_Record__c> filterRecurringRecordsForVisitDeletion(List<aforza__Recurring_Record__c> recurringRecords) {
        List<aforza__Recurring_Record__c> filteredRecurringRecords = new List<aforza__Recurring_Record__c>();
        for (aforza__Recurring_Record__c recurringRecord : recurringRecords) {
            if (recurringRecord.aforza__Last_Recurrence_Date__c == null) {
                filteredRecurringRecords.add(recurringRecord);
            }
        }

        return filteredRecurringRecords;
    }

    private static List<aforza__Visit__c> createNewCalls(List<aforza__Recurring_Record__c> recurringRecords, Date actualDate) {
        List<aforza__Visit__c> scheduledVisits = new List<aforza__Visit__c>();
        for (aforza__Recurring_Record__c recurring : recurringRecords) {
            Set<Date> scheduledDates = getScheduledCallDates(recurring, actualDate);
            dropDatesBeforeDate(scheduledDates, recurring.StartDate__c);
            if (recurring.aforza__Last_Recurrence_Date__c != null) {
                dropDatesBeforeDate(scheduledDates, recurring.aforza__Last_Recurrence_Date__c.date());
            }
            scheduledVisits.addAll(createVisitsFromDates(scheduledDates, recurring));
        }
        return scheduledVisits;
    }

    @TestVisible
    private static Set<Date> getScheduledCallDates(aforza__Recurring_Record__c recurringRecord, Date actualDate) {
        Date startDateMonday = toMonday(recurringRecord.StartDate__c);
        Date thisWeekMonday = toMonday(actualDate);

        Integer periodInDays = Integer.valueOf(recurringRecord.DaysBetweenRecurrence__c);

        Date mostRecentCallWeekStart;
        if (startDateMonday >= thisWeekMonday) {
            mostRecentCallWeekStart = startDateMonday; // startDate is in this week or later
        } else {
            // start date is in previous weeks, find latest week matching the period
            Integer daysBetweenMondays = startDateMonday.daysBetween(thisWeekMonday);
            mostRecentCallWeekStart = thisWeekMonday.addDays(-Math.mod(daysBetweenMondays, periodInDays));
        }
        Integer callingDay = Integer.valueOf(recurringRecord.CallDayOfWeek__c) - 1; // subtract 1 to get numbering based on SF numbering of week days (Sunday = 1)

        return findGivenWeekDaysInNextPeriod(mostRecentCallWeekStart, periodInDays, callingDay, actualDate);
    }

    @TestVisible
    private static void dropDatesBeforeDate(Set<Date> scheduledDates, Date startDate) {
        for (Date possibleDate : scheduledDates) {
            if (possibleDate < startDate) {
                scheduledDates.remove(possibleDate);
            }
        }
    }

    private static List<aforza__Visit__c> createVisitsFromDates(Set<Date> scheduledDates, aforza__Recurring_Record__c recurring) {
        List<aforza__Visit__c> visits = new List<aforza__Visit__c>();
        if (scheduledDates != null) {
            for (Date scheduledDate : scheduledDates) {
                visits.add(createVisit(recurring, scheduledDate));
            }
        }

        return visits;
    }

    @TestVisible
    private static void determineLastVisitForEachAccount(List<aforza__Visit__c> visits) {
        Map<Id, Datetime> recurringRecordToLastScheduledDateMap = new Map<Id, Datetime>();
        for (aforza__Visit__c visit : visits) {
            if (recurringRecordToLastScheduledDateMap.get(visit.aforza__Recurring_Record__c) == null) {
                recurringRecordToLastScheduledDateMap.put(visit.aforza__Recurring_Record__c, visit.aforza__Planned_Time__c);
            } else if (recurringRecordToLastScheduledDateMap.get(visit.aforza__Recurring_Record__c) < visit.aforza__Planned_Time__c) {
                recurringRecordToLastScheduledDateMap.put(visit.aforza__Recurring_Record__c, visit.aforza__Planned_Time__c);
            }
        }
        RecurringRecordService.updateRecurringRecordsLastScheduledDate(recurringRecordToLastScheduledDateMap);
    }

    public static void deleteFutureCalls(List<aforza__Recurring_Record__c> recurringRecords, Date actualDate) {
        List<aforza__Visit__c> visitsToDelete = [SELECT Id FROM aforza__Visit__c WHERE aforza__Recurring_Record__c IN :recurringRecords AND aforza__Planned_Time__c > :actualDate];

        delete visitsToDelete;
    }

    @TestVisible
    private static aforza__Visit__c createVisit(aforza__Recurring_Record__c recurringRecord, Date scheduledDate) {
        aforza__Visit__c visit = new aforza__Visit__c();
        visit.RecordTypeId = RecordTypes.VISIT_REMOTE_VISIT_ID;
        visit.aforza__Account__c = recurringRecord.Account__c;
        visit.aforza__Owner__c = recurringRecord.OwnerId;
        visit.aforza__Type__c = recurringRecord.aforza__Type__c;
        visit.aforza__Status__c = recurringRecord.Status__c;
        visit.aforza__Recurring_Record__c = recurringRecord.Id;

        addStartEndTime(visit, recurringRecord, scheduledDate);

        return visit;
    }

    @TestVisible
    private static void addStartEndTime(aforza__Visit__c visit, aforza__Recurring_Record__c recurringRecord, Date scheduledDate) {
        switch on recurringRecord.Priority__c {
            when 'P1' {
                visit.aforza__Planned_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(09, 00));
                visit.aforza__Planned_End_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(09, 06));
            }
            when 'P2' {
                visit.aforza__Planned_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(10, 00));
                visit.aforza__Planned_End_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(10, 06));
            }
            when 'P3' {
                visit.aforza__Planned_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(11, 00));
                visit.aforza__Planned_End_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(11, 06));
            }
            when else {
                visit.aforza__Planned_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(12, 00));
                visit.aforza__Planned_End_Time__c = combineDateAndDatetime(scheduledDate, buildStartEndDateTime(12, 06));
            }
        }
    }

    @TestVisible
    private static Datetime buildStartEndDateTime(Integer hour, Integer minute) {
        return Datetime.newInstance(2022, 09, 05, hour, minute, 00);
    }

    @TestVisible
    private static Datetime combineDateAndDatetime(Date visitDate, Datetime visitTime) {
        return Datetime.newInstance(visitDate, visitTime.time());
    }

    @TestVisible
    private static Set<Date> findGivenWeekDaysInNextPeriod(Date callWeekStart, Integer period, Integer callingDay, Date actualDate) {
        Set<Date> foundDates = new Set<Date>();
        Date day = actualDate;
        day = day.addDays(Integer.valueOf(CALL_SETTINGS.GenerateVisitsForNextAmountOfDays__c));

        // find limit day = as per settings (and last) working day since now (including today)
        Date limitDate = day.addDays(-1);
        while (callWeekStart <= limitDate) {
            Date candidate = callWeekStart.addDays(callingDay);
            if (isWorkingDay(candidate) && candidate >= actualDate && candidate <= limitDate) {
                foundDates.add(candidate);
            }
            callWeekStart = callWeekStart.addDays(period);
        }
        return foundDates;
    }

    @TestVisible
    private static Boolean isWorkingDay(Date day) {
        Integer dayOfWeek = dayOfWeek(day);
        if (dayOfWeek == 5 || dayOfWeek == 6) {
            return false;
        }
        return true;
    }

    @TestVisible
    private static Date toMonday(Date d) {
        return d.addDays(-dayOfWeek(d));
    }

    @TestVisible
    private static Integer dayOfWeek(Date d) {
        Integer day = Math.mod(Date.newInstance(2001, 1, 1).daysBetween(d), 7); // 1/1/2001 was a Monday
        return day;
    }
}