src/main/default/objects/CallCreationSettings__c/CallCreationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Keeps settings used for creation of visits.</description>
    <label>Call Creation Settings</label>
</CustomObject>

src/main/default/objects/CallCreationSettings__c/fields/AllowedStatuses__c.field-meta.xml
<CustomField>
    <fullName>AllowedStatuses__c</fullName>
    <inlineHelpText>Please fill in all statuses for which calls should be generated. They need to be delimited by comma.</inlineHelpText>
    <label>Allowed Statuses</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/CallCreationSettings__c/fields/CallStatus__c.field-meta.xml
<CustomField>
    <fullName>CallStatus__c</fullName>
    <inlineHelpText>Please enter name of the status of the visit.</inlineHelpText>
    <label>Call Status</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/CallCreationSettings__c/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <inlineHelpText>Please enter a call type that should be used for generated recurring calls.</inlineHelpText>
    <label>Call Type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/TdfCallCreationSettingsTemplate.cls
/**
 * Class provides functionality for creating default Account in test methods.
 *
 * Do not use this class directly.
 * Class is initialized in TDF_SObjectTemplateFactory and all its functionality is used through TDF_SObjectFactory.
 *
 * @see TdfSObjectFactory
 * @see TdfSObjectTemplate
 * @see TdfSObjectTemplateFactory
 * @author  Svata Sejkora
 * @date    2021-11-01
 *
 */
@IsTest
public class TdfCallCreationSettingsTemplate extends TdfSObjectTemplate {

    /**
     * Instance is created dynamically. This method compensates a constructor.
     *
     * @author  Svata Sejkora
     * @date    2021-11-01
     *
     */
    public override void init() {
    }

    /**
     * Creates a template SObject. Every call returns a new instance.
     *
     * Because this method can be called multiple times, all operations as DML or SOQL has to be done in init().
     *
     * @return account template with default values
     *
     * @author  Svata Sejkora
     * @date    2021-11-01
     *
     */
    protected override SObject createTemplateSObject() {
        CallCreationSettings__c template = new CallCreationSettings__c();
        template.AllowedStatuses__c = 'Traders, At Risk, Win Back, Lapsed';
        template.CallStatus__c = 'Not Started';
        template.CallType__c = 'Call';
        template.SetupOwnerId = UserInfo.getOrganizationId();

        return template;
    }
}