src/main/default/objects/aforza__Invoice__c/aforza__Invoice__c.object-meta.xml
<CustomObject>
    <description>A summary of a customer&apos;s invoice information.</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account responsible for paying the invoice.</description>
    <inlineHelpText>The account responsible for paying the invoice.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Billing_Statements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the invoice.</description>
    <inlineHelpText>The current status of the invoice.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Attempt Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Approved for Payment</fullName>
                <default>true</default>
                <label>Approved for Payment</label>
            </value>
            <value>
                <fullName>Cash in Transit</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>true</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Invoice__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethod</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/aforza__Payment_Transaction__c.object-meta.xml
<CustomObject>
    <description>A monetary transaction against a specific account.</description>
    <label>Payment Transaction</label>
    <nameField>
        <displayFormat>PTR-{00000000}</displayFormat>
        <label>Payment Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Account__c.field-meta.xml
<CustomField>
    <fullName>aforza__Account__c</fullName>
    <description>The account the payment transaction has been enacted against.</description>
    <inlineHelpText>The account the payment transaction has been enacted against.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>Payment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Method__c.field-meta.xml
<CustomField>
    <fullName>aforza__Method__c</fullName>
    <description>The method of payment.</description>
    <inlineHelpText>The method of payment.</inlineHelpText>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adjustment Credit</fullName>
            </value>
            <value>
                <fullName>Adjustment Debit</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
            <value>
                <fullName>Bacs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/aforza__Status__c.field-meta.xml
<CustomField>
    <fullName>aforza__Status__c</fullName>
    <description>The current status of the transaction.</description>
    <inlineHelpText>The current status of the transaction.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Authorization</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/objects/aforza__Payment_Transaction__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payment Transactions</relationshipLabel>
    <relationshipName>PaymentTransactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Order/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentMethod</valueSetName>
    </valueSet>
</CustomField>

src/main/default/globalValueSets/PaymentMethod.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>Bacs</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>Card Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
        <isActive>false</isActive>
        <label>Credit</label>
    </customValue>
    <customValue>
        <fullName>Buying Group Central Billing</fullName>
        <isActive>false</isActive>
        <label>Buying Group Central Billing</label>
    </customValue>
    <description>Global value set defining the possible payment methods - used on the account level</description>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

src/main/default/classes/PaymentTransactionService.cls
public with sharing class PaymentTransactionService {

    private static final String PAID_INVOICE_STATUS = 'Paid';
    private static final String APPLIED_TRANSACTION_STATUS = 'Applied';
    private static final String REJECTED_TRANSACTION_STATUS = 'Rejected';
    private static final String PENDING_TRANSACTION_STATUS = 'Pending';
    private static final String CUSTOMER_PAYMENT_TRANSACTION_TYPE = 'Customer Payment';
    private static final String UNSUCCESSFUL_INVOICE_STATUS = 'Payment Attempt Unsuccessful';

    private static final Set<String> PAYMENT_METHOD_RT_IDS = new Set<String>{
        RecordTypes.PAYMENT_METHOD_DIRECT_CARD_ID, RecordTypes.PAYMENT_METHOD_BANK_ACCOUNT_ID
    };

    public static void createPaymentTransactionFromOrders(Set<Id> orderIdsToCreatePaymentTransactionFrom) {
        Map<Id, Order> parentOrders = new Map<Id, Order>([
            SELECT Id, AccountId, PaymentMethod__c, Status, TotalAmount FROM Order 
            WHERE Id IN :orderIdsToCreatePaymentTransactionFrom
        ]);

        List<aforza__Payment_Transaction__c> newPaymentTransactions = new List<aforza__Payment_Transaction__c>();
        
        Set<Id> parentAccountIds = new Set<Id>();
        for(Order ord: parentOrders.values() ){
            parentAccountIds.add(ord.AccountId);
        }
        Map<String, aforza__Payment_Method__c> primaryMethodToPaymentRecord = new Map<String, aforza__Payment_Method__c>();
        for(aforza__Payment_Method__c pMethod: [SELECT Id, aforza__Account__c, RecordTypeId FROM aforza__Payment_Method__c
                                                WHERE aforza__Account__c IN: parentAccountIds AND 
                                                      aforza__Active__c = TRUE AND
                                                      RecordTypeId IN :PAYMENT_METHOD_RT_IDS])
        {
            if (pMethod.RecordTypeId == RecordTypes.PAYMENT_METHOD_DIRECT_CARD_ID) {
                primaryMethodToPaymentRecord.put((pMethod.aforza__Account__c+'Direct Debit'), pMethod);
            }
            if (pMethod.RecordTypeId == RecordTypes.PAYMENT_METHOD_BANK_ACCOUNT_ID) {
                primaryMethodToPaymentRecord.put((pMethod.aforza__Account__c+'Bacs'), pMethod);
            }
            if (pMethod.RecordTypeId == RecordTypes.PAYMENT_METHOD_JDE_DD_ID) {
                primaryMethodToPaymentRecord.put((pMethod.aforza__Account__c+'JDE DD'), pMethod);
            }
        }

        for( Order ord: parentOrders.values() ) {
            String uniqueKey = ord.AccountId + ord.PaymentMethod__c;
            aforza__Payment_Transaction__c pt = prepareDDAndBacsTransactionFromOrder(ord);
            pt.aforza__Payment_Method__c = primaryMethodToPaymentRecord.containsKey(uniqueKey) ? primaryMethodToPaymentRecord.get(uniqueKey).Id : null;
            newPaymentTransactions.add(pt);
        }
        insert newPaymentTransactions;
    }

    private static aforza__Payment_Transaction__c prepareDDAndBacsTransactionFromOrder(Order ord) {
        aforza__Payment_Transaction__c pt = new aforza__Payment_Transaction__c();
        pt.aforza__Amount__c = ord.TotalAmount;
        pt.aforza__Status__c = PENDING_TRANSACTION_STATUS;
        pt.OrderNumber__c = ord.Id;
        pt.aforza__Account__c = ord.AccountId;
        pt.aforza__Type__c = CUSTOMER_PAYMENT_TRANSACTION_TYPE; 
        pt.aforza__Method__c = ord.PaymentMethod__c;
        return pt;
    }

    public static void updatePaymentTransactionStatusForInvoices(Set<Id> invoiceIds) {
        List<aforza__Payment_Transaction__c> pTransactionsToUpdate = new List<aforza__Payment_Transaction__c>();
        for(aforza__Payment_Transaction__c pTransaction : [SELECT aforza__Invoice__r.aforza__Status__c  FROM aforza__Payment_Transaction__c 
                                                           WHERE aforza__Invoice__c IN :invoiceIds]) 
        {
            pTransactionsToUpdate.add(new aforza__Payment_Transaction__c(
                Id = pTransaction.Id,
                aforza__Status__c = getPaymentTransactionStatusByInvoiceStatus(pTransaction.aforza__Invoice__r.aforza__Status__c)
            ));
        }
        update pTransactionsToUpdate;
    }

    private static String getPaymentTransactionStatusByInvoiceStatus(String invoiceStatus) {
        switch on invoiceStatus {
            when 'Payment Attempt Unsuccessful' {
                return REJECTED_TRANSACTION_STATUS;
            }
            when 'Paid' {
                return APPLIED_TRANSACTION_STATUS;
            }
        }
        return null;
    }
}