src/main/default/objects/Order/fields/Clone__c.field-meta.xml
<CustomField>
    <fullName>Clone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clone?</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Product2/fields/aforza__Type__c.field-meta.xml
<CustomField>
    <fullName>aforza__Type__c</fullName>
    <description>The type of product.</description>
    <inlineHelpText>The type of product.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Family</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Still</fullName>
            </value>
            <value>
                <fullName>Sparkling</fullName>
            </value>
            <value>
                <fullName>Baby</fullName>
                <isActive>false</isActive>
                <label>Baby</label>
            </value>
            <value>
                <fullName>Beer, Wine &amp; Spirits</fullName>
                <isActive>false</isActive>
                <label>Beer, Wine &amp; Spirits</label>
            </value>
            <value>
                <fullName>Bins &amp; Fridges</fullName>
                <isActive>false</isActive>
                <label>Bins &amp; Fridges</label>
            </value>
            <value>
                <fullName>Bread &amp; Bakery</fullName>
                <isActive>false</isActive>
                <label>Bread &amp; Bakery</label>
            </value>
            <value>
                <fullName>Breakfast &amp; Cereal</fullName>
                <isActive>false</isActive>
                <label>Breakfast &amp; Cereal</label>
            </value>
            <value>
                <fullName>Brochures &amp; Handouts</fullName>
                <isActive>false</isActive>
                <label>Brochures &amp; Handouts</label>
            </value>
            <value>
                <fullName>Canned Goods &amp; Soups</fullName>
                <isActive>false</isActive>
                <label>Canned Goods &amp; Soups</label>
            </value>
            <value>
                <fullName>Cleaning Supplies</fullName>
                <isActive>false</isActive>
                <label>Cleaning Supplies</label>
            </value>
            <value>
                <fullName>Condiments/Spices &amp; Bake</fullName>
                <isActive>false</isActive>
                <label>Condiments/Spices &amp; Bake</label>
            </value>
            <value>
                <fullName>Cookies, Snacks &amp; Candy</fullName>
                <isActive>false</isActive>
                <label>Cookies, Snacks &amp; Candy</label>
            </value>
            <value>
                <fullName>Dairy, Eggs &amp; Cheese</fullName>
                <isActive>false</isActive>
                <label>Dairy, Eggs &amp; Cheese</label>
            </value>
            <value>
                <fullName>Deli &amp; Signature Cafe</fullName>
                <isActive>false</isActive>
                <label>Deli &amp; Signature Cafe</label>
            </value>
            <value>
                <fullName>Fixtures</fullName>
                <isActive>false</isActive>
                <label>Fixtures</label>
            </value>
            <value>
                <fullName>Flowers</fullName>
                <isActive>false</isActive>
                <label>Flowers</label>
            </value>
            <value>
                <fullName>Frozen Foods</fullName>
                <isActive>false</isActive>
                <label>Frozen Foods</label>
            </value>
            <value>
                <fullName>Fruits &amp; Vegetables</fullName>
                <isActive>false</isActive>
                <label>Fruits &amp; Vegetables</label>
            </value>
            <value>
                <fullName>Gondolas</fullName>
                <isActive>false</isActive>
                <label>Gondolas</label>
            </value>
            <value>
                <fullName>Grains, Pasta &amp; Sides</fullName>
                <isActive>false</isActive>
                <label>Grains, Pasta &amp; Sides</label>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
                <isActive>false</isActive>
                <label>Health &amp; Beauty</label>
            </value>
            <value>
                <fullName>International Cuisine</fullName>
                <isActive>false</isActive>
                <label>International Cuisine</label>
            </value>
            <value>
                <fullName>Meat &amp; Seafood</fullName>
                <isActive>false</isActive>
                <label>Meat &amp; Seafood</label>
            </value>
            <value>
                <fullName>Paper Products</fullName>
                <isActive>false</isActive>
                <label>Paper Products</label>
            </value>
            <value>
                <fullName>Personal Care &amp; Pharmacy</fullName>
                <isActive>false</isActive>
                <label>Personal Care &amp; Pharmacy</label>
            </value>
            <value>
                <fullName>Pet Care</fullName>
                <isActive>false</isActive>
                <label>Pet Care</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/default/classes/OrderItemTriggerHandlerTest.cls
/**
 * Created by magdalena.stanciu on 23.11.2022.
 */

@IsTest
private with sharing class OrderItemTriggerHandlerTest {
    @IsTest
    private static void testCalculateVatOnOrderItemLevel_InsertOrderItemNullTaxPercent() {
        Product2 newProduct = (Product2) TdfSObjectFactory.insertSObject(new Product2());
        PricebookEntry newPricebookEntry = (PricebookEntry) TdfSObjectFactory.insertSObject(
            new PricebookEntry(Product2Id = newProduct.Id, Pricebook2Id = TdfPricebook2Template.standardPricebookId, aforza__Tax_Percent__c = null)
        );

        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));

        Test.startTest();
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(Product2Id = newProduct.Id, PricebookEntryId = newPricebookEntry.Id, OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10, aforza__Tax__c = 1)
        );
        Test.stopTest();

        OrderItem insertedOrderItem = [
            SELECT Id, aforza__Tax__c
            FROM OrderItem
            WHERE Id = :newOrderItem.Id
        ];

        Assert.areEqual(0, insertedOrderItem.aforza__Tax__c);
    }

    @IsTest
    private static void testCalculateVatOnOrderItemLevel_InsertOrderNotNullTaxPercent() {
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));

        Test.startTest();
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 12, UnitPrice = 10.43, aforza__Tax__c = 12)
        );
        Test.stopTest();

        OrderItem insertedOrderItem = [
            SELECT Id, aforza__Tax__c, aforza__Tax_Percent__c
            FROM OrderItem
            WHERE Id = :newOrderItem.Id
        ];

        Decimal expectedVat = newOrderItem.Quantity * newOrderItem.UnitPrice * insertedOrderItem.aforza__Tax_Percent__c / 100;
        Decimal expectedVatRounded = expectedVat.setScale(2, RoundingMode.HALF_UP);
        Assert.areEqual(expectedVatRounded, insertedOrderItem.aforza__Tax__c);
    }

    @IsTest
    private static void testCalculateVatOnOrderItemLevel_UpdateOrderItemQuantity() {
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10.45, aforza__Tax__c = 23)
        );

        OrderItem insertedOrderItem = [
            SELECT Id, Quantity, UnitPrice, aforza__Tax_Percent__c, aforza__Tax__c
            FROM OrderItem
            WHERE Id = :newOrderItem.Id
        ];

        Decimal expectedVat = newOrderItem.Quantity * newOrderItem.UnitPrice * insertedOrderItem.aforza__Tax_Percent__c / 100;
        Decimal expectedVatRounded = expectedVat.setScale(2, RoundingMode.HALF_UP);
        Assert.areEqual(expectedVatRounded, insertedOrderItem.aforza__Tax__c);

        Test.startTest();
        insertedOrderItem.Quantity = 20;
        update insertedOrderItem;
        Test.stopTest();

        OrderItem updatedOrderItem = [
            SELECT Id, aforza__Tax__c
            FROM OrderItem
            WHERE Id = :insertedOrderItem.Id
        ];

        expectedVat = insertedOrderItem.Quantity * insertedOrderItem.UnitPrice * insertedOrderItem.aforza__Tax_Percent__c / 100;
        Assert.areEqual(expectedVat, updatedOrderItem.aforza__Tax__c);
    }

    @IsTest
    private static void testCalculateVatOnOrderItemLevel_UpdateOrderItemUnitPrice() {
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10.45, aforza__Tax__c = 9)
        );

        OrderItem insertedOrderItem = [
            SELECT Id, Quantity, UnitPrice, aforza__Tax_Percent__c, aforza__Tax__c
            FROM OrderItem
            WHERE Id = :newOrderItem.Id
        ];

        Decimal expectedVat = newOrderItem.Quantity * newOrderItem.UnitPrice * insertedOrderItem.aforza__Tax_Percent__c / 100;
        Decimal expectedVatRounded = expectedVat.setScale(2, RoundingMode.HALF_UP);
        Assert.areEqual(expectedVatRounded, insertedOrderItem.aforza__Tax__c);

        Test.startTest();
        insertedOrderItem.UnitPrice = 20;
        update insertedOrderItem;
        Test.stopTest();

        OrderItem updatedOrderItem = [
            SELECT Id, aforza__Tax__c
            FROM OrderItem
            WHERE Id = :insertedOrderItem.Id
        ];

        expectedVat = insertedOrderItem.Quantity * insertedOrderItem.UnitPrice * insertedOrderItem.aforza__Tax_Percent__c / 100;
        Assert.areEqual(expectedVat, updatedOrderItem.aforza__Tax__c);
    }

    @IsTest
    private static void testCalculateVatOnOrderItemLevel_InsertNonProductOrderItem() {
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));

        Test.startTest();
        OrderItem newOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10, aforza__Tax__c = null, aforza__Type__c = 'Discount')
        );
        Test.stopTest();

        OrderItem insertedOrderItem = [
            SELECT Id, aforza__Tax__c
            FROM OrderItem
            WHERE Id = :newOrderItem.Id
        ];

        Assert.areEqual(null, insertedOrderItem.aforza__Tax__c);
    }

    @IsTest
    private static void testCalculateVatOnOrderLevel_InsertOrderItems() {
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));
        OrderItem newTaxOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, aforza__Type__c = 'Tax', Quantity = 1, UnitPrice = -1, aforza__Tax__c = 0)
        );

        Test.startTest();
        OrderItem newProductOrderItem1 = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10, aforza__Tax__c = 1)
        );
        OrderItem newProductOrderItem2 = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10, aforza__Tax__c = 1)
        );
        Test.stopTest();

        Map<Id, OrderItem> insertedOrderItems = new Map<Id, OrderItem>([
            SELECT Id, UnitPrice, Quantity, aforza__Tax_Percent__c, aforza__Type__c, aforza__Tax__c
            FROM OrderItem
            WHERE OrderId = :newOrder.Id
        ]);

        Decimal expectedVat1 = insertedOrderItems.get(newProductOrderItem1.Id).Quantity * insertedOrderItems.get(newProductOrderItem1.Id).UnitPrice * insertedOrderItems.get(newProductOrderItem1.Id).aforza__Tax_Percent__c / 100;
        Decimal expectedVat2 = insertedOrderItems.get(newProductOrderItem2.Id).Quantity * insertedOrderItems.get(newProductOrderItem2.Id).UnitPrice * insertedOrderItems.get(newProductOrderItem2.Id).aforza__Tax_Percent__c / 100;
        Decimal totalVat = expectedVat1 + expectedVat2;
		
        Assert.areEqual(totalVat, insertedOrderItems.get(newTaxOrderItem.Id).UnitPrice);
    }

    @IsTest
    private static void testCalculateVatOnOrderLevel_UpdateOrderItems() {
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));
        OrderItem newTaxOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, aforza__Type__c = 'Tax', Quantity = 1, UnitPrice = 0)
        );
        OrderItem newProductOrderItem1 = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10)
        );
        OrderItem newProductOrderItem2 = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10)
        );

        Map<Id, OrderItem> insertedOrderItems = new Map<Id, OrderItem>([
            SELECT Id, UnitPrice, Quantity, aforza__Tax_Percent__c, aforza__Type__c, aforza__Tax__c
            FROM OrderItem
            WHERE OrderId = :newOrder.Id
        ]);

        // check calculations before update
        Decimal expectedVat1 = insertedOrderItems.get(newProductOrderItem1.Id).Quantity * insertedOrderItems.get(newProductOrderItem1.Id).UnitPrice * insertedOrderItems.get(newProductOrderItem1.Id).aforza__Tax_Percent__c / 100;
        Decimal expectedVat2 = insertedOrderItems.get(newProductOrderItem2.Id).Quantity * insertedOrderItems.get(newProductOrderItem2.Id).UnitPrice * insertedOrderItems.get(newProductOrderItem2.Id).aforza__Tax_Percent__c / 100;
        Decimal totalVat = expectedVat1 + expectedVat2;

        Assert.areEqual(totalVat, insertedOrderItems.get(newTaxOrderItem.Id).UnitPrice);

        Test.startTest();
        newProductOrderItem1.Quantity = 10;
        newProductOrderItem2.UnitPrice = 20;
        update new List<OrderItem>{newProductOrderItem1, newProductOrderItem2};
        Test.stopTest();

        Map<Id, OrderItem> updatedOrderItems = new Map<Id, OrderItem>([
            SELECT Id, UnitPrice, Quantity, aforza__Tax_Percent__c, aforza__Type__c, aforza__Tax__c
            FROM OrderItem
            WHERE OrderId = :newOrder.Id
        ]);

        System.debug(updatedOrderItems.get(newProductOrderItem1.Id));
        System.debug(updatedOrderItems.get(newProductOrderItem2.Id));

        expectedVat1 = updatedOrderItems.get(newProductOrderItem1.Id).Quantity * updatedOrderItems.get(newProductOrderItem1.Id).UnitPrice * updatedOrderItems.get(newProductOrderItem1.Id).aforza__Tax_Percent__c / 100;
        expectedVat2 = updatedOrderItems.get(newProductOrderItem2.Id).Quantity * updatedOrderItems.get(newProductOrderItem2.Id).UnitPrice * updatedOrderItems.get(newProductOrderItem2.Id).aforza__Tax_Percent__c / 100;
        totalVat = expectedVat1 + expectedVat2;

        Assert.areEqual(totalVat, updatedOrderItems.get(newTaxOrderItem.Id).UnitPrice);
    }

    @IsTest
    private static void testCalculateVatOnOrderLevel_DeleteOrderItems() {
        Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID));
        OrderItem newTaxOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, aforza__Type__c = 'Tax', Quantity = 1, UnitPrice = 0)
        );
        OrderItem newProductOrderItem1 = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10, aforza__Tax__c = 0)
        );
        OrderItem newProductOrderItem2 = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10, aforza__Tax__c = 0)
        );

        Map<Id, OrderItem> insertedOrderItems = new Map<Id, OrderItem>([
            SELECT Id, UnitPrice, Quantity, aforza__Tax_Percent__c, aforza__Type__c, aforza__Tax__c
            FROM OrderItem
            WHERE OrderId = :newOrder.Id
        ]);

        // check calculations before update
        Decimal expectedVat1 = insertedOrderItems.get(newProductOrderItem1.Id).Quantity * insertedOrderItems.get(newProductOrderItem1.Id).UnitPrice * insertedOrderItems.get(newProductOrderItem1.Id).aforza__Tax_Percent__c / 100;
        Decimal expectedVat2 = insertedOrderItems.get(newProductOrderItem2.Id).Quantity * insertedOrderItems.get(newProductOrderItem2.Id).UnitPrice * insertedOrderItems.get(newProductOrderItem2.Id).aforza__Tax_Percent__c / 100;
        Decimal totalVat = expectedVat1 + expectedVat2;

        Assert.areEqual(totalVat, insertedOrderItems.get(newTaxOrderItem.Id).UnitPrice);

        Test.startTest();
        delete newProductOrderItem2;
        Test.stopTest();

        Map<Id, OrderItem> updatedOrderItems = new Map<Id, OrderItem>([
            SELECT Id, UnitPrice, Quantity, aforza__Tax_Percent__c, aforza__Type__c, aforza__Tax__c
            FROM OrderItem
            WHERE OrderId = :newOrder.Id
        ]);

        totalVat = updatedOrderItems.get(newProductOrderItem1.Id).Quantity * updatedOrderItems.get(newProductOrderItem1.Id).UnitPrice * updatedOrderItems.get(newProductOrderItem1.Id).aforza__Tax_Percent__c / 100;
        Assert.areEqual(totalVat, updatedOrderItems.get(newTaxOrderItem.Id).UnitPrice);
    }
    
    @IsTest
    private static void testCalculateVatOnOrderLevel_PreventCloneOrderVatCalculation(){
        
        Test.startTest();
		Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID, Clone__c = true));
        OrderItem newTaxOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, aforza__Type__c = 'Tax', Quantity = 1, UnitPrice = 1, aforza__Tax__c = 0)
        );
        TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10)
        );
        TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10)
        );
        Test.stopTest();
                                                                 
		OrderItem orderItem = [SELECT Id, UnitPrice FROM OrderItem WHERE Id = :newTaxOrderItem.Id];
        
        Assert.areEqual(newTaxOrderItem.UnitPrice, orderItem.UnitPrice);
    }
    
    @IsTest
    private static void testCalculateVatOnOrderLevel_OriginalOrderVatCalculation(){
        
        Test.startTest();
		Order newOrder = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_TELESALES_ID, Clone__c = false));
        OrderItem newTaxOrderItem = (OrderItem) TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, aforza__Type__c = 'Tax', Quantity = 1, UnitPrice = 1, aforza__Tax__c = 0)
        );
        TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10)
        );
        TdfSObjectFactory.insertSObject(
            new OrderItem(OrderId = newOrder.Id, Quantity = 10, UnitPrice = 10)
        );
        Test.stopTest();
                                                                 
		OrderItem orderItem = [SELECT Id, UnitPrice FROM OrderItem WHERE Id = :newTaxOrderItem.Id];
        
        Assert.areEqual(20, orderItem.UnitPrice);
        
    }
}