src/main/default/objects/Order/fields/DeliveryFailed__c.field-meta.xml
<CustomField>
    <fullName>DeliveryFailed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Populated when order is cancelled from Delivery Failed status. Only during operation done from Logistic Update Screen.</inlineHelpText>
    <label>Delivery Failed</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/Order/fields/Depot__c.field-meta.xml
<CustomField>
    <fullName>Depot__c</fullName>
    <label>Depot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DepotValues</valueSetName>
    </valueSet>
</CustomField>

src/main/default/objects/Order/fields/Replanned__c.field-meta.xml
<CustomField>
    <fullName>Replanned__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Field populated to true when order changed status from Delivery Failed to Unplanned. Populated only by action from Logistic Update Screen.</inlineHelpText>
    <label>Replanned</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/globalValueSets/DepotValues.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>D</fullName>
        <label>Dagenham</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>Wednesbury</label>
    </customValue>
    <customValue>
        <fullName>M</fullName>
        <label>Moston</label>
    </customValue>
    <customValue>
        <fullName>S</fullName>
        <label>Scotland</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cranks</label>
    </customValue>
    <customValue>
        <fullName>B</fullName>
        <label>Bentleys</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Murdens</label>
    </customValue>
    <customValue>
        <fullName>Z</fullName>
        <label>Menzies</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Blacks</label>
    </customValue>
    <customValue>
        <fullName>Cumbernauld</fullName>
        <isActive>false</isActive>
        <label>Cumbernauld</label>
    </customValue>
    <masterLabel>Depot Values</masterLabel>
</GlobalValueSet>

src/main/default/classes/LogisticUpdateScreenControllerTest.cls
/**
 * Created by svatopluk.sejkora on 07.10.2022.
 */

@IsTest
private class LogisticUpdateScreenControllerTest {

    @IsTest
    private static void testFetchNeededPicklistValues() {
        Test.startTest();
        List<LogisticUpdateScreenController.PicklistDto> picklists = LogisticUpdateScreenController.fetchNeededPicklistValues('Order', new List<String>{'Status', 'Depot__c'});
        Test.stopTest();

        System.assert(!picklists.isEmpty(), 'There should be values in the returned list of picklists');
    }

    @IsTest
    private static void testUpdateOrderStatus() {
        String newStatus = 'Picking in Progress';
        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID));

        Test.startTest();
        LogisticUpdateScreenController.updateOrderStatus(new List<String>{order.Id}, newStatus);
        Test.stopTest();

        List<Order> updatedOrder = [ SELECT Id, Status FROM Order];

        System.assertEquals(1, updatedOrder.size());
        System.assertEquals(newStatus, updatedOrder[0].Status);
    }

    @IsTest
    private static void testUpdateOrderStatus_Cancelled() {
        String newStatus = 'Cancelled';
        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID));

        Test.startTest();
        LogisticUpdateScreenController.updateOrderStatus(new List<String>{order.Id}, newStatus);
        Test.stopTest();

        List<Order> updatedOrder = [ SELECT Id, Status, DeliveryFailed__c FROM Order];

        System.assertEquals(1, updatedOrder.size());
        System.assertEquals(newStatus, updatedOrder[0].Status);
        System.assertEquals(true, updatedOrder[0].DeliveryFailed__c);
    }

    @IsTest
    private static void testUpdateOrderStatus_Unplanned() {
        String newStatus = 'Unplanned';
        Order order = (Order) TdfSObjectFactory.insertSObject(new Order(RecordTypeId = RecordTypes.ORDER_ECOMMERCE_ID));

        Test.startTest();
        LogisticUpdateScreenController.updateOrderStatus(new List<String>{order.Id}, newStatus);
        Test.stopTest();

        List<Order> updatedOrder = [ SELECT Id, Status, Replanned__c FROM Order];

        System.assertEquals(1, updatedOrder.size());
        System.assertEquals(newStatus, updatedOrder[0].Status);
        System.assertEquals(true, updatedOrder[0].Replanned__c);
    }
}